//Tags are used and shared in these file:
//  * flex-gateway-k8-getting-started.adoc
//  * flex-troubleshoot-docker.adoc
//  * flex-troubleshoot-helm.adoc 
//
//
//DOCKER
//tag::troubleshoot-docker-intro[]

Troubleshoot errors returned by a `docker` command:

* <<daemon-bad-response>>
* <<bad-request>>

//end::troubleshoot-docker-intro[]
//
//
//tag::troubleshoot-docker-daemon-bad-response[]

If Docker is not started, a `docker` command returns an error message similar to the following ones:

* {empty}
+
----
Error response from daemon: Bad response from Docker engine
----

* {empty}
+
----
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. 
       Is the docker daemon running?
----

If you get this error, start Docker.

//end::troubleshoot-docker-daemon-bad-response[]
//
//
//tag::troubleshoot-docker-bad-request[]

The following error can occur when you use `docker run` to register your gateway:

----
[flexctl][error] reg facade call returned error response:
HTTP/1.1 400 Bad Request
----

The reason for this error is available within the error message. Common causes include: 

[[name-already-exists]]
* `an active target with the same name already exists in this organization and environment`
+
To avoid this issue, provide a _unique name_ for your gateway when running the registration command. Note that you _cannot reuse the same name_ even if a previous registration with that name was successful. When this error occurs, the command generates an _empty_ `registration.yaml`, which prevents re-registration _and_ produces an error when you try to use the file when deploying the gateway to your cluster. 
+
[[no-token]]
* `no valid registration token was found`
+
To avoid this issue, generate a new token for the command by refreshing the *Add a Flex Gateway* page for Kubernetes and rerun the registration command.

//end::troubleshoot-docker-bad-request[]
//
//
//
//HELM (for k8 & openshift)
//tag::troubleshoot-helm-intro[]

Troubleshoot errors returned by a `helm` command for Kubernetes and OpenShift clusters:

* <<troubleshoot-helm-yaml-empty>>
* <<troubleshoot-helm-cluster-unreachable>>
* <<troubleshoot-helm-upgrade-failed>>
* <<troubleshoot-helm-openshift-rbac>>

//end::troubleshoot-helm-intro[]
//
//tag::troubleshoot-helm-yaml-empty[]

[[yaml-empty]]
If the `registration.yaml` file is invalid when you pass it to the Helm command during deployment of Flex Gateway, the following error results:

----
Error: UPGRADE FAILED: execution error at (flex-gateway/templates/deployment.yaml:4:10):
registerSecretName, registration.content or registration.secretName is required!
----

When this error occurs, make sure that the `registration.yaml` file is not empty. If the file is empty, reregister your gateway with a new, unique name to generate a new `registration.yaml` and rerun the procedures that follow the registration step. See  xref:flex-gateway-k8-getting-started.adoc#register-flex[Register Flex Gateway] for an example of the registration command.

//end::troubleshoot-helm-yaml-empty[]
//
//
//tag::troubleshoot-helm-cluster-unreachable[]

[[cluster-unreachable]]
If your Kubernetes cluster is not running when you attempt to deploy Flex Gateway using `helm`, the following error might occur:

----
Error: Kubernetes cluster unreachable: 
the server could not find the requested resource
----

Start the service that runs your cluster. 

Check that your Kubernetes cluster host is running your cluster, for example:

[source,kubectl]
----
kubectl cluster-info
----

* If the cluster is running, the command returns a result similar to this one:
+
----
Kubernetes control plane is running at https://34.30.50.119
GLBCDefaultBackend is running at https://34.30.50.119/api/v1/namespaces/kube-system/services/default-http-backend:http/proxy
KubeDNS is running at https://34.30.50.119/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
Metrics-server is running at https://34.30.50.119/api/v1/namespaces/kube-system/services/https:metrics-server:/proxy
----

* If the cluster is not up, the command can return a result similar to this one:
+
----
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
error: the server doesn't have a resource type "services"
----

//end::troubleshoot-helm-cluster-unreachable[]
//
//
//tag::troubleshoot-helm-upgrade-failed[]

[[upgrade-failed]]
Some issues can cause the Helm upgrade command to hang for up to 5 minutes (due to the `--wait` flag in the command) before producing the following timeout error:

----
Error: UPGRADE FAILED: timed out waiting for the condition
----

This error typically means that your cluster configuration is incorrect or that your cluster configuration tool does not support this process. One potential cause is the failure to generate a `Service` resource of the `LoadBalancer` type. You can troubleshoot further by running the following commands:

* {empty}
+
[source,kubectl]
----
kubectl -n gateway describe deployment
----

* {empty}
+
[source,kubectl]
----
kubectl -n gateway describe service
----

//end::troubleshoot-helm-upgrade-failed[]
//
//
//tag::troubleshoot-helm-openshift-rbac[]

//cluster-level access when rbac enabled, as for OpenShift
[[rbac-openshift]]
include::partial$prerequisites.adoc[tags=rbac-permission-k8;rbac-role-openshift]

Without the required access, you receive an error similar to the following one:

----
Error: failed to install CRD crds/apiinstance.yaml:
customresourcedefinitions.apiextensions.k8s.io is forbidden: 
User "user1" cannot create resource "customresourcedefinitions" 
in API group "apiextensions.k8s.io" at the cluster scope
----

//end::troubleshoot-helm-openshift-rbac[]