= Configuring Message Logging for Flex Gateway in Connected Mode

Applying a Message Logging policy to your API instance in API Manager allows you to view basic logs for APIs managed by Flex Gateway within API Manager. Logging for an API instance only happens if you configure and apply a Message Logging policy. 

== Message Logging Limits and Features

API Manager stores up to 100 MB of logs per API instance for 30 days. Runtime Manager automatically purges logs that go beyond 100 MB per API instance. If you need more storage, you can either use a third-party service (configured through a policy) or sign up for a Titanium subscription. 

For each API instance configured through a policy, basic logs report the following:

* The inbound and outbound API calls being made as well as the packet contents.
* The headers and any other information of the request. 

NOTE: In non-production environments all users can have access to the logs, while in production only admin users will have access to logs.

== Before You Begin

Before configuring the TLS context for a Flex Gateway, you must complete the following tasks:

* xref:flex-install.adoc[Install Flex Gateway]
* xref:flex-conn-reg-run.adoc[Register and Run Flex Gateway]
* xref:api-manager::create-instance-task.adoc[Add an API Instance]

== Configure Message Logging in Connected Mode

. From API Administration in API Manager, select the name of the API Instance.
. Click *Policies*.
. Click *+ Add policy*.
. Click *Message Logging*, under the *Troubleshooting* category.
. Click *Next*.
. Click *+ Add*.
. Enter a *Configuration Name*, for example, Info messages before calling API.
. Enter a Mule expression that selects what information you want to see.
+
For example, `#[attributes.header['id']]` will extract the ids from the headers of
the messages. See xref:dataweave::dataweave-variables-context.adoc[Predefined Variables]
in the Dataweave documentation for more information.
. If you want to filter the messages that are logged, you can enter a Mule expression.
+
For example, `#[attributes.headers['id']==1]` will only display log messages that have
an id of 1 in the header.

. If you want to affix a prefix to your logs, enter a *Category*.
. Enter the severity level.
+
You can only enter one level. See <<severity-levels, Message Logging Severity Levels>>
for a description of each severity level and the hierarchy for the levels.

. If you want messages for after the API is called, select the *After Calling API* checkbox.
. If you want to add additional configurations, click *+ Add*.
. Click *Save*.
+
Afterward, you should see a *Message Log* option for the API instance.
+
You can use the search field to search for specific logs based on the time and log severity (INFO, ERROR, WARN, DEBUG, TRACE). Additionally, you can download these logs for further analysis.

[[severity-levels]]
== Message Logging Severity Levels

When you configure a Message Logging policy for your API instance you can assign a severity level. 

=== Severity Levels Description

Each severity level will include a specific set of information in the log report. The following table
describes the type of information that will be included in the logs for each severity level.

[%header,cols='1a,5a'] 
|===
|Log Severity Level
|Description

|ERROR
|Error events that prevent normal program execution, but might allow the application to continue running.

|WARN
|Potentially harmful situations that indicate potential problems.

|INFO
|Informational messages that highlight the progress of the application.

|DEBUG
|Relatively detailed tracing used by application developers.

|TRACE
|Information broadly interesting to developers who do not have a specialized interest in the specific subsystem. Might include minor (recoverable) failures and issues indicating potential performance problems.
|===

=== Severity Levels Hierarchy

Only the severity level you select and the subsequent levels on the hierarchy will be included in the log reports.
For example, if you select INFO, the WARN and ERROR severity levels will be included in the log reports.
However, if you select ERROR, only the error messages will be included. The following table describes the hierarchy of the different severity levels.

[%header,cols='1h,1a,1a,1a,1a,1a',frame=all] 
|===
|
|ERROR
|WARN
|INFO
|DEBUG
|TRACE

|ERROR
|&#10004;
|
|
|
|

|WARN
|&#10004;
|&#10004;
|
|
|

|INFO
|&#10004;
|&#10004;
|&#10004;
|
|

|DEBUG
|&#10004;
|&#10004;
|&#10004;
|&#10004;
|

|TRACE
|&#10004;
|&#10004;
|&#10004;
|&#10004;
|&#10004;
|===