= Install and Run as a Linux Service
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

The following procedure demonstrates how to install and run Flex Gateway as a service on a Debian-based distribution.

== Procedure 

. Retrieve the public package keys, add the package repository, update the package list, and install the package via the commands in the following block: 
+
----
curl -XGET https://peregrine:48bcfd4617c9cce@d8wbbsqfcfi8u.cloudfront.net/ubuntu/pubkey.gpg | sudo apt-key add -
echo "deb https://peregrine:48bcfd4617c9cce@d8wbbsqfcfi8u.cloudfront.net/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/mulesoft.list
sudo apt update
sudo apt install -y peregrine
----

. Run Flex Gateway by executing the following command:
+
----
sudo service peregrine start
----

. Verify that the Flex Gateway service is running successfully by executing the following command: 
+
----
service --status-all
----
+
A list of all services displays. Locate the `peregrine` service, which will be successfully running if the value of its `status` is `+`, as in the following:   
+
----
[ + ]  peregrine
----

. Create a configuration file called `app.yaml` and save it in the Flex Gateway configuration directory: `/etc/peregrine/conf.d/custom/`. This directory can contain multiple configuration files.

. Copy and paste the following into `app.yaml`, then save:
+
----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: ApiInstance
metadata:
  name: jsonplaceholder-api
spec:
  address: http://0.0.0.0:8080
  services:
    jsonplaceholder:
      address: https://jsonplaceholder.typicode.com:443/
      routes:
        - rules:
            - path: /api(/users/.*)
            - path: /api(/comments/.*)
  policies:
    - policyRef:
        name: basic-authentication
      config:
        username: foo
        password: bar
----
+
The configuration creates a service called `jsonplaceholder`, specifies its implementation address, and then defines path rules.
+
Additionally, the configuration applies a policy called `basic-authentication`, and specifies credentials that incoming requests use when accessing the `jsonplaceholder` service.

. Verify that the API is protected by requesting access without the authentication credentials:
+
----
curl -v http://127.0.0.1:8080/api/users/1
---- 
+
The result includes the following: 
+
----
HTTP/1.1 401 Unauthorized
----

. Verify that the API returns correct data when authentication credentials are included: 
+
----
curl -v -u foo:bar http://127.0.0.1:8080/api/users/1
----
+
The result should include the following: 
+
----
[
  {
    "id": 1,
    "name": "Leanne Graham",
    "username": "Bret",
    "email": "Sincere@april.biz",
    "address": {
      "street": "Kulas Light",
      "suite": "Apt. 556",
      "city": "Gwenborough",
      "zipcode": "92998-3874",
      "geo": {
        "lat": "-37.3159",
        "lng": "81.1496"
      }
    },
    "phone": "1-770-736-8031 x56442",
    "website": "hildegard.org",
    "company": {
      "name": "Romaguera-Crona",
      "catchPhrase": "Multi-layered client-server neural-net",
      "bs": "harness real-time e-markets"
    }
  },
  ...
----

A secured service is now running behind Flex Gateway.

== Next Steps

* xref:flex-local-viewing-and-managing-logs.adoc[View and Manage Log Output].
* Refer to the xref:flex-local-configuration-reference-guide.adoc[Declarative Configuration Reference Guide].