= Viewing Key Metrics for a Flex API
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

//not married to the idea of this being a whole topic.

APIs that are deployed through Flex Gateway are managed in API Manager. API Manager and Anypoint Monitoring collect metrics on active, deployed APIs. You can view charts related to these metrics or create alerts against them.

== Viewing Key Metrics in an API Instance

include::partial$include-nav-steps-api-instance.adoc[]
The *Key Metrics* section shows four dashboards. If key metrics do not appear for your API instance, refresh your browser.

== Identify Key Metrics

The *Key Metrics* section of the API summary contains the following dashboards:

Average Response Time::
Average response time of requests in the selected time period for the given API.
+
Data is aggregated in one minute increments.

Total Requests::
Sum of requests in the selected time period for the given API.
+
Data is aggregated in one minute increments.

Total Errors::
Sum of HTTP response codes that occur in the selected time period. The response codes counted in this metric are 301, 400, 401, 402, 403, 404, 405, 408, 409, 410, 411, 412, 413, 415, 416, 417, 420, 422, 429, 500, 502, 503, 504, 504, 510, and 511.
+
Data is aggregated in one minute increments.

Total Policy Violations::
Sum of requests that return policy violations.
+
Data is aggregated in one minute increments.

== What's Next?

Create alerts using the metrics related to an API instance with the xref:flex-alerts.adoc[*Alerts* feature in API Manager] or with the xref:anypoint-monitoring::basic-alerts.adoc[*Basic Alerts* feature in Anypoint Monitoring].
