= Managing Flex Gateway in Connected Mode
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

Connected Mode enables you to manage all of your non-Mule APIs from a single unified
control plane, and grants you all the other benefits of Anypoint Platform, such as
monitoring through API Analytics and reusability through Exchange.

Get started using Flex Gateway in Connected Mode with the following tasks:

* xref:flex-gateway-replicas.adoc[Manage Flex Replicas]
+
A Flex Replica is an instance of the Flex Gateway. By default, Flex Gateway runs a
single replica. Running multiple replicas enables scaling, load balancing,
and high availability.
* xref:api-manager::create-instance-task.adoc[Add an API Instance in API Manager]
+
An API Instance is a proxy of an API that serves the upstream. API instances support the application of policies
and can be deployed to an API gateway. 
* xref:api-manager::configure-api-task.adoc[Configure an API Instance Endpoint in API Manager]
+
There are several optional configurations you can use to customize your API Instance to fit your specific situation. Not all options are available depending on the runtime as well as the API.
* xref:policies-included-apply.adoc[Apply a Policy in API Manager]
+
A policy extends the functionality of an API and enforces certain capabilities such as security. A policy
can control access and traffic. For example, a policy can generally control authentication, access,
allotted consumption, and service level access (SLA).
* xref:flex-use-api-alerts.adoc[Use API Alerts]
+
Using API alerts for Flex Gateway in Connected Mode, you can add and configure email
notifications that flag unusual API behavior.
* xref:flex-view-api-metrics.adoc[View Key Metrics for Flex Gateway APIs]
+
API Manager and Anypoint Monitoring collect metrics on active Flex Gateway APIs. You can view charts related to these metrics and filter the data by date.