= Viewing and Managing Log Output
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

Anypoint Flex Gateway enables you to push metrics to https://docs.fluentbit.io/manual/v/1.7/[Fluentbit 1.7.9^] logging services. Supported outputs can be found in Fluentbit's https://docs.fluentbit.io/manual/v/1.7/pipeline/outputs[Outputs^] reference. Refer to the xref:flex-local-configuration-reference-guide.adoc#logging[Declarative Configuration Reference Guide] for information on how to configure Flex Gateway for any of these supported outputs.

The following examples describe how to configure Flex Gateway for use with the File and HTTP outputs.

[NOTE]
====
To enable access logging, you must: 

. Configure the File or HTTP output.
. Apply the `access-log` policy via policy binding. See xref:flex-local-view-manage-logs.adoc#access-logs[Access Logs].
====

== File Configuration Example

Configure Flex Gateway to send formatted runtime and access logs to a file called `log.txt` (Fluentbit https://docs.fluentbit.io/manual/v/1.7/pipeline/outputs/file[File^] output), located within `/var/log` directory. As an example, the following definition specifies a `spec.logging.outputs.type` value of `file`:

NOTE: For Docker, in `spec.logging.output.parameters.path`, replace `/var/log` with the absolute path to the mounted configuration directory.

----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Configuration
metadata:
  name: metrics-config
spec:
  logging:
    outputs:
    - name: default
      type: file
      parameters:
        path: /var/log  # Docker: replace this value with the absolute path to the mounted configuration directory
        file: log.txt
        format: template
        template: |
          [{runtime}][{loglevel}][{kind}] {message}
    runtimeLogs:
      logLevel: info
      outputs:
      - default
    accessLogs:
      outputs:
      - default
----

== HTTP Configuration Example

In addition to configuring logging for Fluentbit File output, you can also configure for Fluentbit https://docs.fluentbit.io/manual/v/1.7/pipeline/outputs/http[HTTP^] output. As an example, the following definition specifies a `spec.logging.outputs.type` value of `http`:

----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Configuration
metadata:
  name: metrics-config
spec:
  logging:
    outputs:
    - name: default
      type: http
      parameters:
        host: collectors.au.sumologic.com
        port: 443
        URI: /receiver/v1/http/[PrivateKey]
        format: json_lines
        json_date_key: timestamp
        json_date_format: iso8601
    runtimeLogs:
      logLevel: info
      outputs:
      - default
    accessLogs:
      outputs:
      - default
----

== Access Logs

After specifying access log output (as described in the previous configuration examples), you must enable access logs via policy binding. 

For inline configurations, enable access logs by adding `access-log` to the `spec.policies` section of `ApiInstance`. The following is an inline configuration example:

----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: ApiInstance
metadata:
  name: jsonplaceholder-api
spec:
  address: http://0.0.0.0:8080
  services:
    jsonplaceholder:
      address: https://jsonplaceholder.typicode.com:443/
      routes:
        - rules:
            - path: /api(/users/.*)
  policies:
    - policyRef:
        name: access-log
----

For resource-based configurations, enable access logs by adding `access-log` to the `spec.policyRef` section of `PolicyBinding`. The following is a resource-based configuration example: 

----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: PolicyBinding
metadata:
  name: ingress-http-access-logs
spec:
  targetRef:
    name: ingress-http
  policyRef:
    name: access-log
----


