= Registering and Running in Local Mode
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

When using Anypoint Flex Gateway in local mode, your gateway will mostly be disconnected
from the Anypoint control plane and you will manage it using local declarative configuration files.

Before you can use your Flex Gateway to manage API instances, you must register and start it.

There are three options for registering Flex Gateway in local mode including the following:

* xref:flex-local-reg-run-up.adoc[Register and Run using a Username and Password]: If you have
a username and password for Anypoint Platform, you can use these credentials to register
your Flex Gateway.
* xref:flex-local-reg-run-app.adoc[Register and Run using a Connected App]: If you do not have
a username or password for Anypoint Platform, you can use connected app credentials to register
your Flex Gateway.
* xref:flex-local-reg-run-token.adoc[Register and Run using a Token]: If you do not have a username
or password for Anypoint Platform, you can use a registration token generated by the Runtime Manager UI.

== See Also

* xref:flex-gateway-getting-started.adoc[Getting Started with Flex Gateway]
* xref:flex-local-manage.adoc[Managing Flex Gateway in Local Mode]