= Getting Started with Flex Gateway
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

Flex Gateway is a performant API Gateway that can secure both Mule and non-Mule APIs.
It is easily integrated into CI/CD workflows while offering enterprise security and manageability.

You can run Flex Gateway in two different modes: 

* **Local Mode:** Run Flex Gateway in local mode if you want to run it mostly disconnected
from the Anypoint control plane, and manage it with locally stored declarative configuration files.
* **Connected Mode:** Run Flex Gateway in connected mode if you want it fully connected to the Anypoint
control plane for centralized management, observability, and security.

Get started with Flex Gateway by performing the following tasks: 

. **xref:flex-review-prerequisites.adoc[Review Prerequisites]:** Before setting up Flex Gateway, you will need to ensure certain ports are available.
. **xref:flex-install.adoc[Install Flex Gateway]:** You can install Flex Gateway as a Linux
service, in a Docker container, or as a Kubernetes Ingress controller.
. **Register and Run Flex Gateway:** Once you have installed your Flex Gateway, you will need to register it
so that you can start using it to manage API instances. 
* xref:flex-conn-reg-run.adoc[Register and Run in Connected Mode]
* xref:flex-local-reg-run.adoc[Register and Run in Local Mode]
. **Manage an API with Flex Gateway:** Use your Flex Gateway to manage API instances and apply both included,
automated, and custom policies. 
* xref:flex-conn-manage.adoc[Manage an API in Connected Mode]
* xref:flex-local-manage.adoc[Manage an API in Local Mode]
