= Install and Run Flex Gateway
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

== Install and Run as a Docker Container Image

A Docker container image is a package of software that includes everything needed to run an application. You install and run Flex Gateway as a container image in your local environment during application development - enabling you to test and iterate quickly within Continuous-Integration and Continuous Delivery (CI/CD) workflows. 

The following procedure demonstrates how to install and run a "containerized" Flex Gateway in your local environment.

=== Procedure

. https://drive.google.com/file/d/1xR2kQqV5BUdIqk8LUbdW8LSdjlF2dP8P/view?usp=sharing[Download the Flex Gateway container image^].
. Copy the container image tar archive into a directory of your choice.
. Open a command line client and navigate to the directory containing the container image tar archive.
. Load ("install") the Flex Gateway container image by executing the following command:
+
----
docker load --input anypoint-flex-gateway.tar
----

. Verify the installation was successful by executing the following command: 
+
----
docker images
----
+
The Flex Gateway container image should appear in the resulting list: 
+
----
REPOSITORY                                TAG       IMAGE ID       CREATED        SIZE
mulesoft/anypoint-flex-gateway            latest    1c1fbdbf819b   9 days ago     279MB
----

. https://drive.google.com/file/d/1Uq1YA8UZCRCLhmg7-nMsUPjafNjFzAPQ/view?usp=sharing[Download the sample Flex Gateway configuration file^].
. Copy the sample configuration `.yaml` file into a directory of your choice (typically the same directory as the container image tar archive.)
. Run the Flex Gateway by executing the following command: 
+
----
docker run -it -p 8080:8080 -v /absolute/path/to/sample/config.yaml:/etc/peregrine/conf.d/custom/config.yaml mulesoft/anypoint-flex-gateway
----

. Verify that the container image is running successfully by executing the following command: 
+
----
docker ps
----
+
The Flex Gateway process should appear in the resulting list: 
+
----
CONTAINER ID   IMAGE                            COMMAND   CREATED      STATUS      PORTS                                       
c2a360f8c9ed   mulesoft/anypoint-flex-gateway   "/init"   8 days ago   Up 8 days   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp 
----

== Install and Run as a Linux Service

In addition to "sandboxing" Flex Gateway as a Docker container image, you can install and run Flex Gateway as a Linux service. The Linux instance is typically run virtually as a node in a virtual machine cluster, thereby guaranteeing that each virtual machine (with its associated Flex Gateway) is standalone and encapsulated. 

The following procedure demonstrates how to install and run Flex Gateway as a service in a Linux instance.

=== Procedure

. Retrieve the required Flex Gateway public package keys and add them to the `apt` key server:
----
wget -qO- https://peregrine-repos.s3.us-west-2.amazonaws.com/ubuntu/pubkey.gpg | sudo apt-key add -
----

----
echo "deb https://peregrine-repos.s3.us-west-2.amazonaws.com/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/mulesoft.list

sudo apt update

sudo apt install peregrine
----



----
sudo service peregrine start
----

== Install and Run as a Kubernetes Application

== Install and Run as a Kubernetes Ingress Controller

