= Configuration Reference
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

Anypoint Flex Gateway supports two YAML configuration models: inline, and resource-based. Inline configurations enable you to nest objects, thereby simplifying entity definitions. Resource-based configurations enable you to separate objects into multiple files or resources, thereby assisting with modularity.

Examples of inline configuration definitions are included in the following installation procedures: 

* xref:microgateway-linux.adoc[Install and Run as an Ubuntu Service]
* xref:microgateway-docker.adoc[Install and Run as a Docker Container Image]

The following reference describes the available configuration resources.

== API Instance

----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: ApiInstance
metadata:
  name: <api instance name>  
  namespace: <namespace name>
spec:
  address: <proxy address including port>
----

[cols="2,1,1,3"]
|===
|Parameter |Required or Optional |Default Value |Description

|`metadata.name`
|Required
|N/A
|The API instance identifier that is used as a target reference for other resources, such as policy bindings.

|`metadata.namespace`
|Optional
|`default`
|

|`spec.address`
|Required
|N/A
|The proxy address (and port) of the API implementation.

|===

=== API Instance Example

The following resource specifies an `ApiInstance` with metadata that describes the instance identifier. The `metadata.name` value is used as the target reference for other resources, such as policy bindings: 

----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: ApiInstance
metadata:
  name: hello-flex-gateway-instance
  namespace: e-commerce
spec:
  address: http://0.0.0.0:8080/
----

== Policy Binding 

----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: PolicyBinding
metadata:
  name: <policy binding name>
  namespace: <namespace name>
spec:
  targetRef:
    kind: ApiInstance
    name: <api instance name>  
    namespace: <namespace name> 
  policyRef:
    kind: Extension
    name: <policy name>     
    namespace: <policy namespace>
  config: <Policy configuration>
  rules:
  - path: <rule path> 
----

[cols="2,1,1,3"]
|===
|Parameter |Required or Optional |Default Value |Description

|`metadata.name`
|Required
|N/A
|The identifier of the policy binding.

|`metadata.namespace`
|Optional
|`default`
|

|`spec.targetRef.name`
|Required
|N/A
|The API instance identifier to which the policy is bound to.

|`spec.targetRef.namespace`
|Optional
|The value of `metadata.namespace`
|The namespace where the target is defined.

|`spec.policyRef.name`
|Required
|N/A
|The policy name. See the list of available policies.

|`spec.policyRef.namespace`
|Optional
|The value of `metadata.namespace`
|The namespace where the policy is defined. For provided policies, the value of this field should be `gateway`.

|`spec.config`
|Optional
|`{}`
|The policy configuration. The content of this field depends on the specified policy. See the list of available policies.

|`spec.rules`
|
|
|

|===

=== Policy Binding Examples 

The following resource binds an `ingress-http-route` policy to the API instance, routing traffic specified in `rules.path` to the proxy address specified in the `Service` configuration snippet: 

----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: PolicyBinding
metadata:
  name: ingress-http-route
  namespace: e-commerce
spec:
  targetRef:
    kind: ApiInstance
    name: hello-flex-gateway-instance
    namespace: e-commerce
  policyRef:
    kind: Extension
    name: route
    namespace: gateway
  config:
    destinationRef:
      kind: Service
      name: helloworld-v1
      namespace: e-commerce
  rules:
  - path: /api/jsonplaceholder(/.*)
----

The following resource binds an `ingress-http-auth` policy to the API instance -  requiring requests to include the basic credentials defined in `config.username` and `config.password`:

----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: PolicyBinding
metadata:
 name: ingress-http-auth
 namespace: e-commerce
spec:
 targetRef:
   kind: ApiInstance
   name: hello-flex-gateway-instance
   namespace: e-commerce
 policyRef:
   kind: Extension
   name: basic-authentication
   namespace: gateway
 config:
   username: foo
   password: bar
----

== Service

----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Service
metadata:
  name: <service name>        
  namespace: <namespace name> 
spec:
  address: <service address including port> 
----

[cols="2,1,1,3"]
|===
|Parameter |Required or Optional |Default Value |Description

|`metadata.name`
|Required
|N/A
|The service identifier.

|`metadata.namespace`
|Optional
|`default`
|

|`spec.address`
|Required
|N/A
|The service address (and port).

|===

=== Service Example

The following resource defines a `Service` with metadata that describes the service identifier. The `metadata.namespace` value matches the namespace specified in the `ApiInstance` configuration. The `spec.address` is the address of the API implementation: 

----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Service
metadata:
  name: helloworld-v1
  namespace: e-commerce
spec:
  address: https://jsonplaceholder.typicode.com:443/
----

== Configuration

Define a desired gateway state by creating a `Configuration` entity. `Configuration` entities specify the runtime behavior of APIs managed by the instance. The definition includes the following: 

----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Configuration
metadata:
  name: <value>           
  namespace: <namespace name>      
spec: 
  <spec object> 
----

[cols="2,1,1,3"]
|===
|Parameter |Required or Optional |Default Value |Description

|`metadata.name`
|Required
|N/A
|The Configuration entity.

|`metadata.namespace`
|Optional
|`default`
|The namespace value used to isolate Configuration entities.

|`spec`
|Required
|N/A
|The persistent configuration object that defines gateway characteristics. Objects include: `logging`, `sharedStorage`, `tls`, `platformConnection`, `forwardProxy`, `automatedPolicy`.

|===

=== Logging

The `logging` object configures the delivery of runtime/access logs enabled via the message logging policy. Logs are delivered to any supported https://fluentbit.io/[Fluentbit^] output.

----
apiVersion: config.mulesoft.com/v1alpha1
kind: Configuration
metadata:
  name: <value>
  namespace: <namespace name>
spec:
  logging:
    outputs:
    - name:
      type: 
      [type_parameters]: 
  runtimeLog:
    logLevel: 
    outputs: <value>
  accessLog:
    outputs: <value>
----

=== Shared Storage

The `sharedStorage` object configures running the gateway in high availability environments. Shared storage requires a https://redis.io/[redis database^] to be installed, running, and accessible.