= Install and Run as a Kubernetes Ingress Controller
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

The following procedures demonstrate how to install and run Flex Gateway as an ingress controller.

== Dependencies

* https://kubernetes.io/docs/tasks/tools/#kubectl[kubectl,^] a tool used to interact with Kubernetes clusters.
* https://helm.sh/docs/intro/install/[Helm,^] a tool used to install Flex Gateway, monitoring tools and applications. A minimum Helm version of 3.0.0 is required.

== Prepare the Environment

. Create a new Kubernetes cluster with a single server node: 
+
----
k3d cluster create flex-gateway-1 --k3s-arg "--disable=traefik@server:*" --port '80:80@server:*' --port '443:443@server:*'
----
+
The command should return the following: 
+
----
INFO[0042] Cluster 'flex-gateway-1' created successfully!
----

. Download the Flex Gateway container image: 
+
----
curl -o flex-gateway-1.0.0-beta.3.tar https://peregrine:48bcfd4617c9cce@d8wbbsqfcfi8u.cloudfront.net/docker/flex-gateway-1.0.0-beta.3.tar
----

. Import the container image: 
+
----
k3d image import -c flex-gateway-1 flex-gateway-1.0.0-beta.3.tar
----
+
The command should return the following: 
+
----
INFO[0016] Successfully imported image(s)
INFO[0016] Successfully imported 1 image(s) into 1 cluster(s)
----

== Procedure 
. Add the helm repository: 
+
----
helm repo add flex-gateway https://peregrine:48bcfd4617c9cce@d8wbbsqfcfi8u.cloudfront.net/helm
----

. Update the helm repository:
+
----
helm repo up
----

. Install the *flex-gateway* helm chart into namespace *gateway* with ingress:  
+
----
helm -n gateway upgrade -i --wait --create-namespace ingress flex-gateway/flex-gateway
----
+
The command should return something like the following: 
+
----
NAME: ingress
LAST DEPLOYED: Tue Oct 19 13:08:07 2021
NAMESPACE: gateway
STATUS: deployed
REVISION: 1
TEST SUITE: None
----

. Execute the following command to verify *apiinstances* created during installation: 
+
----
kubectl -n gateway get apiinstances
---- 
+
The command returns output similar to the following: 
+
----
NAME            ADDRESS
ingress-http    http://0.0.0.0:80
ingress-https   http://0.0.0.0:443
----

. Install a sample application named "jsonplaceholder", and create the ingress to route traffic: 
+
----
cat <<EOF | kubectl apply -f -
---
apiVersion: v1
kind: Service
metadata:
  name: jsonplaceholder
  labels:
    app: jsonplaceholder
    service: jsonplaceholder
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: jsonplaceholder
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsonplaceholder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jsonplaceholder
      version: v1
  template:
    metadata:
      labels:
        app: jsonplaceholder
        version: v1
    spec:
      containers:
      - image: svenwal/jsonplaceholder
        imagePullPolicy: IfNotPresent
        name: jsonplaceholder
        ports:
        - name: http
          containerPort: 3000
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jsonplaceholder
spec:
  ingressClassName: ingress-http.gateway
  rules:
  - http:
      paths:
      - path: /api(/users/.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: jsonplaceholder
            port:
              number: 80
EOF
----

. Apply the *basic-authentication* policy to the `ingress-http` API Instance, using `foo` as the username and `bar` as the password
+
----
cat <<EOF | kubectl -n gateway apply -f -
---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: PolicyBinding
metadata:
  name: ingress-http-auth
spec:
  targetRef:
    name: ingress-http
  policyRef:
    name: basic-authentication
  config:
    username: foo
    password: bar
EOF
----

. Verify that the API Instance is protected by requesting access without the authentication credentials:
+
----
curl -v http://127.0.0.1/api/users/1
---- 
+
The result includes the following: 
+
----
HTTP/1.1 401 Unauthorized
----

. Verify that the API Instance returns correct data when authentication credentials are included: 
+
----
curl -v -u foo:bar http://127.0.0.1/api/users/1
----
+
The result should include the following: 
+
----
[
  {
    "id": 1,
    "name": "Leanne Graham",
    "username": "Bret",
    "email": "Sincere@april.biz",
    "address": {
      "street": "Kulas Light",
      "suite": "Apt. 556",
      "city": "Gwenborough",
      "zipcode": "92998-3874",
      "geo": {
        "lat": "-37.3159",
        "lng": "81.1496"
      }
    },
    "phone": "1-770-736-8031 x56442",
    "website": "hildegard.org",
    "company": {
      "name": "Romaguera-Crona",
      "catchPhrase": "Multi-layered client-server neural-net",
      "bs": "harness real-time e-markets"
    }
  },
  ...
----

A secured service is now running behind Flex Gateway.

== Next Steps

* xref:microgateway-view-manage-log-output.adoc[View and Manage Log Output].
* Refer to the xref:microgateway-configuration-reference.adoc[Declarative Configuration Reference Guide].