= Install and Run on a Docker Container Image
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

A Docker container image is a package of software that includes everything needed to run an application. You install and run Flex Gateway as a container image in your local environment during application development - enabling you to test and iterate quickly within Continuous-Integration and Continuous Delivery (CI/CD) workflows. 

The following procedure demonstrates how to install and run a "containerized" Flex Gateway in your local environment.

== Dependencies

Installation requires a Docker-enabled environment with appropriate Docker permissions. See https://docs.docker.com/compose/install/[Install Docker Compose^].

== Procedure

. https://drive.google.com/file/d/1lWC0aDvaVVD6RhkqeEt1u5ZVPlP9kyZT/view?usp=sharing[Download the Flex Gateway container image^].
. Copy the container image tar archive into a directory of your choice.
. Open a command line client and navigate to the directory containing the container image tar archive.
. Install the Flex Gateway container image by executing the following command:
+
----
docker load --input flex-gateway-1.0.0-alpha.1.tar
----

. Verify the installation was successful by executing the following command: 
+
----
docker images
----
+
The Flex Gateway container image should appear in the resulting list: 
+
----
REPOSITORY                      TAG       IMAGE ID       CREATED        SIZE
mulesoft/flex-gateway           latest    1c1fbdbf819b   9 days ago     333MB
----

. Create a configuration file called `app.yaml` and save it in the same directory as your container image tar archive.

. Copy the following into `app.yaml`, then save:
+
----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: ApiInstance
metadata:
  name: ingress-http
spec:
  address: http://0.0.0.0:8080
  services:
    jsonplaceholder:
      address: https://jsonplaceholder.typicode.com:443/
      routes:
        - rules:
            - path: /api(/users/.*)
            - path: /api(/comments/.*)
  policies:
    - policyRef:
        name: basic-authentication
      config:
        username: foo
        password: bar
----
+
The configuration creates a service called `jsonplaceholder`, specifies its implementation address, and then defines path rules.
+
Additionally, the configuration applies a policy called `basic-authentication`, and specifies credentials that incoming requests use when accessing the `jsonplaceholder` service.

. Run Flex Gateway by executing the following command. Include the absolute path to the `app.yaml` file created in the previous step (the file typically resides in the same directory as the downloaded container image tar archive.) 
+
----
docker run -it -p 8080:8080 -v /absolute/path/to/app.yaml:/etc/peregrine/conf.d/custom/app.yaml mulesoft/flex-gateway:1.0.0-alpha.1
----
+
In addition to running Docker, the command instructs the running instance to listen at a given port, and to mount the port on the image in the directory path.

. Verify that the container image is running successfully by opening a new terminal and executing the following command: 
+
----
docker ps
----
+
The Flex Gateway process should appear in the resulting list: 
+
----
CONTAINER ID   IMAGE                                     COMMAND   CREATED      STATUS      PORTS                                       
c2a360f8c9ed   mulesoft/flex-gateway:1.0.0-alpha.1       "/init"   8 days ago   Up 8 days   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp 
----

. Test the service by executing the following command: 
+
----
curl -v -u foo:bar http://127.0.0.1:8080/api/users/1
----
+
The result should include the following: 
+
----
[
  {
    "id": 1,
    "name": "Leanne Graham",
    "username": "Bret",
    "email": "Sincere@april.biz",
    "address": {
      "street": "Kulas Light",
      "suite": "Apt. 556",
      "city": "Gwenborough",
      "zipcode": "92998-3874",
      "geo": {
        "lat": "-37.3159",
        "lng": "81.1496"
      }
    },
    "phone": "1-770-736-8031 x56442",
    "website": "hildegard.org",
    "company": {
      "name": "Romaguera-Crona",
      "catchPhrase": "Multi-layered client-server neural-net",
      "bs": "harness real-time e-markets"
    }
  },
  ...
----

A secured service is now running behind Flex Gateway.