= Install and Run Flex Gateway
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

Flex Gateway can be deployed in the following environments:

* A Docker container image in a local development environment. See xref:microgateway-install-run.adoc#install-and-run-as-a-docker-container-image[Install and Run as a Docker Container Image].
* An Ubuntu instance in a VM cluster. See xref:microgateway-install-run.adoc#install-and-run-as-an-ubuntu-service[Install and Run as an Ubuntu Service].
* A Kubernetes application in a Kubernetes cluster. See xref:microgateway-install-run.adoc#install-and-run-as-a-kubernetes-application[Install and Run as a Kubernetes Application].
* A Kubernetes ingress controller in a Kubernetes cluster. See xref:microgateway-install-run.adoc#install-and-run-as-a-kubernetes-ingress-controller[See Install and Run as a Kubernetes Ingress Controller].

== Install and Run as a Docker Container Image

A Docker container image is a package of software that includes everything needed to run an application. You install and run Flex Gateway as a container image in your local environment during application development - enabling you to test and iterate quickly within Continuous-Integration and Continuous Delivery (CI/CD) workflows. 

The following procedure demonstrates how to install and run a "containerized" Flex Gateway in your local environment.

=== Procedure

. https://drive.google.com/file/d/1xR2kQqV5BUdIqk8LUbdW8LSdjlF2dP8P/view?usp=sharing[Download the Flex Gateway container image^].
. Copy the container image tar archive into a directory of your choice.
. Open a command line client and navigate to the directory containing the container image tar archive.
. Load ("install") the Flex Gateway container image by executing the following command:
+
----
docker load --input anypoint-flex-gateway.tar
----

. Verify the installation was successful by executing the following command: 
+
----
docker images
----
+
The Flex Gateway container image should appear in the resulting list: 
+
----
REPOSITORY                                TAG       IMAGE ID       CREATED        SIZE
mulesoft/anypoint-flex-gateway            latest    1c1fbdbf819b   9 days ago     279MB
----

. https://drive.google.com/file/d/1Uq1YA8UZCRCLhmg7-nMsUPjafNjFzAPQ/view?usp=sharing[Download the sample Flex Gateway configuration file^].
. Copy the sample configuration `.yaml` file into a directory of your choice (typically the same directory as the container image tar archive.)
. Run the Flex Gateway by executing the following command: 
+
----
docker run -it -p 8080:8080 -v /absolute/path/to/sample/config.yaml:/etc/peregrine/conf.d/custom/config.yaml mulesoft/anypoint-flex-gateway
----

. Verify that the container image is running successfully by executing the following command: 
+
----
docker ps
----
+
The Flex Gateway process should appear in the resulting list: 
+
----
CONTAINER ID   IMAGE                            COMMAND   CREATED      STATUS      PORTS                                       
c2a360f8c9ed   mulesoft/anypoint-flex-gateway   "/init"   8 days ago   Up 8 days   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp 
----

== Install and Run as an Ubuntu Service

In addition to "sandboxing" Flex Gateway as a Docker container image, you can install and run Flex Gateway as an Ubuntu service. The Ubuntu instance is typically run virtually as a node in a virtual machine cluster, thereby guaranteeing that each virtual machine (with its running Flex Gateway) is standalone and encapsulated. 

The following procedure demonstrates how to install and run Flex Gateway as a service in an Ubuntu instance.

=== Procedure

. Retrieve the public package keys and add them to the Advanced Package Tool (APT) key server by executing the following command:
+ 
----
wget -qO- https://peregrine-repos.s3.us-west-2.amazonaws.com/ubuntu/pubkey.gpg | sudo apt-key add -
----

. Add the Flex Gateway package repository by storing the type of distribution archive (Debian), as well as the repository URL and Ubuntu distribution code name. Execute the following command: 
+
----
echo "deb https://peregrine-repos.s3.us-west-2.amazonaws.com/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/mulesoft.list
----

. Update the package list by executing the following command: 
+
----
sudo apt update
----

. Install the Flex Gateway package from the updated repository by executing the following command:
+
----
sudo apt install anypoint-flex-gateway
----

. Run the Flex Gateway by executing the following command:
+
----
sudo service anypoint-flex-gateway start
----

. Verify that the Flex Gateway service is running successfully by executing the following command: 
+
----
service --status-all
----
+
A list of all services displays. Locate the `anypoint-flex-gateway` service, which will be successfully running if the value of its `status` is `+`, as in the following:   
+
----
[ + ]  anypoint-flex-gateway
----

== Install and Run as a Kubernetes Application

== Install and Run as a Kubernetes Ingress Controller

