= View and Manage Log Output
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

Anypoint Flex Gateway enables you to push metrics to https://docs.fluentbit.io/manual/v/1.7/[Fluentbit 1.7.9^] logging services. Supported outputs can be found in Fluentbit's https://docs.fluentbit.io/manual/v/1.7/pipeline/outputs[Outputs^] reference. Refer to the xref:microgateway-configuration-reference.adoc#logging[Declarative Configuration Reference Guide] for information on how to configure Flex Gateway for any of these supported outputs.

The following examples describe how to configure Flex Gateway for use with the File and HTTP outputs.

== File Configuration Example

Configure Flex Gateway to send formatted runtime and access logs to a file called `log.txt` (Fluentbit https://docs.fluentbit.io/manual/v/1.7/pipeline/outputs/file[File^] output), located within the container's `/var/log` directory. As an example, the following definition specifies a `spec.logging.outputs.type` value of `file`:

----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Configuration
metadata:
  name: metrics-config
spec:
  logging:
    outputs:
    - name: default
      type: file
      parameters:
        path: /var/log
        file: log.txt
        format: template
        template: |
          [{runtime}][{loglevel}][{kind}] {message}
    runtimeLogs:
      logLevel: info
      outputs:
      - default
    accessLogs:
      outputs:
      - default
----

== HTTP Configuration Example

In addition to configuring logging for Fluentbit File output, you can also configure for Fluentbit https://docs.fluentbit.io/manual/v/1.7/pipeline/outputs/http[HTTP^] output. As an example, the following definition specifies a `spec.logging.outputs.type` value of `http`:

----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Configuration
metadata:
  name: metrics-config
spec:
  logging:
    outputs:
    - name: default
      type: http
      parameters:
        host: collectors.au.sumologic.com
        port: 443
        URI: /receiver/v1/http/[PrivateKey]
        format: json_lines
        json_date_key: timestamp
        json_date_format: iso8601
    runtimeLogs:
      logLevel: info
      outputs:
      - default
    accessLogs:
      outputs:
      - default
----