= Configure Flex Gateway
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

Modify `.yaml` configuration files to deploy and secure services. You can do so directly within the Docker container filesystem. Or, for Kubernetes environments, you can apply configuration `.yaml` files via the Kubectl command line. With either method, the format of the Flex Gateway configuration files is the same.

This document describes how to configure Flex Gateway to run a secure service.

== Before You Begin

A Flex Gateway instance must be deployed. See xref:microgateway-install-run.adoc[Install and Run Flex Gateway].

== Procedure

. Configure the API instance. Create a `.yaml` configuration file with the following snippet:
+
----
---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: ApiInstance
metadata:
  name: hello-flex-gateway-instance
  namespace: e-commerce
spec:
  address: http://0.0.0.0:8080/
----
+
This snippet specifies an `ApiInstance` with metadata that describes the instance identifier. The `metadata.name` value is used as the target reference for other resources, such as policy bindings.

. Configure the Service. Append the following snippet to the `.yaml` configuration file:
+
----
---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Service
metadata:
  name: helloworld-v1
  namespace: e-commerce
spec:
  address: https://jsonplaceholder.typicode.com:443/
----
+
This snippet specifies a `Service` with metadata that describes the service identifier. The `metadata.namespace` value matches the namespace specified in the `ApiInstance` configuration. The `spec.address` is the address of the API implementation.

. Configure policy binding. Append the following snippet to the `.yaml` configuration file: 
+
----
---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: PolicyBinding
metadata:
  name: ingress-http-route
  namespace: e-commerce
spec:
  targetRef:
    kind: ApiInstance
    name: hello-flex-gateway-instance
    namespace: e-commerce
  policyRef:
    kind: Extension
    name: route
    namespace: gateway
  config:
    destinationRef:
      kind: Service
      name: helloworld-v1
      namespace: e-commerce
  rules:
  - path: /api/jsonplaceholder(/.*)
----
+
This snippet binds an `ingress-http-route` policy to the API instance, routing traffic specified in `rules.path` to the proxy address specified in the `Service` configuration snippet.

. Copy the `.yaml` configuration file into the Flex Gateway configuration directory, located within the Docker container filesystem (or VM filesystem): `/etc/peregrine/conf.d/custom/`. Flex Gateway automatically reloads this change and immediately begins running the service.
+
Alternatively, for Kubuernetes you can apply the configuration using `kubectl apply`).

. Test the service by executing the following command: 
+
----
curl http://127.0.0.1:8080/api/jsonplaceholder/users
----
+
The result should include the following: 
+
----
[
  {
    "id": 1,
    "name": "Leanne Graham",
    "username": "Bret",
    "email": "Sincere@april.biz",
    "address": {
      "street": "Kulas Light",
      "suite": "Apt. 556",
      "city": "Gwenborough",
      "zipcode": "92998-3874",
      "geo": {
        "lat": "-37.3159",
        "lng": "81.1496"
      }
    },
    "phone": "1-770-736-8031 x56442",
    "website": "hildegard.org",
    "company": {
      "name": "Romaguera-Crona",
      "catchPhrase": "Multi-layered client-server neural-net",
      "bs": "harness real-time e-markets"
    }
  },
  ...
----

. Now that the service is running behind Flex Gateway, you can secure the service with a simple authentication policy. Append the following snippet to the `.yaml` configuration file: 
+
----
---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: PolicyBinding
metadata:
 name: ingress-http-auth
 namespace: e-commerce
spec:
 targetRef:
   kind: ApiInstance
   name: ingress-http
   namespace: e-commerce
 policyRef:
   kind: Extension
   name: basic-auth
   namespace: gateway
 config:
   username: foo
   password: bar
----
+
This snippet binds an `ingress-http-auth` policy to the API instance, requiring requests to include the basic credentials defined in `.config`.
+
Executing the previous `curl` command now results in an authorization error:
+
----
curl http://127.0.0.1:8080/api/jsonplaceholder/users
----

. Test the service with the required credentials by executing the following command: 
+
----
curl -u foo:bar http://127.0.0.1:8080/api/jsonplaceholder/users
----
+
Output similar to before is returned.





