= Install and Run as an Ubuntu Service
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

You can install and run Anypoint Flex Gateway as an Ubuntu LTS (Focal Fossa) service. The Ubuntu instance is typically run virtually as a node in a virtual machine cluster, thereby guaranteeing that each virtual machine (with its running Flex Gateway) is standalone and encapsulated. 

The following procedure demonstrates how to install and run Flex Gateway as a service in an Ubuntu instance.

== Procedure 

. Retrieve the public package keys and add them to the Advanced Package Tool (APT) key server by executing the following command:
+ 
----
curl -XGET https://peregrine:48bcfd4617c9cce@d8wbbsqfcfi8u.cloudfront.net/ubuntu/pubkey.gpg | sudo apt-key add -
----

. Add the Flex Gateway package repository by storing the type of distribution archive (Debian), as well as the repository URL and Ubuntu distribution code name. Execute the following command: 
+
----
echo "deb https://peregrine:48bcfd4617c9cce@d8wbbsqfcfi8u.cloudfront.net/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/mulesoft.list
----

. Update the package list by executing the following command: 
+
----
sudo apt update
----

. Install the Flex Gateway package from the updated repository by executing the following command:
+
----
sudo apt install peregrine
----

. Run the Flex Gateway by executing the following command:
+
----
sudo service peregrine start
----

. Verify that the Flex Gateway service is running successfully by executing the following command: 
+
----
service --status-all
----
+
A list of all services displays. Locate the `peregrine` service, which will be successfully running if the value of its `status` is `+`, as in the following:   
+
----
[ + ]  peregrine
----

. Create a configuration file called `app.yaml` and save it in the Flex Gateway configuration directory, located within the Docker container filesystem (or Ubuntu filesystem): `/etc/peregrine/conf.d/custom/`.

. Copy the following into `app.yaml`, then save:
+
----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: ApiInstance
metadata:
  name: ingress-http
spec:
  address: http://0.0.0.0:8080
  services:
    jsonplaceholder:
      address: https://jsonplaceholder.typicode.com:443/
      routes:
        - rules:
            - path: /api(/users/.*)
            - path: /api(/comments/.*)
  policies:
    - policyRef:
        name: basic-authentication
      config:
        username: foo
        password: bar
----
+
The configuration creates a service called `jsonplaceholder`, specifies its implementation address, and then defines path rules.
+
Additionally, the configuration applies a policy called `basic-authentication`, and specifies credentials that incoming requests use when accessing the `jsonplaceholder` service.

. Test the service by executing the following command: 
+
----
curl -v -u foo:bar http://127.0.0.1:8080/api/users/1
----
+
The result should include the following: 
+
----
[
  {
    "id": 1,
    "name": "Leanne Graham",
    "username": "Bret",
    "email": "Sincere@april.biz",
    "address": {
      "street": "Kulas Light",
      "suite": "Apt. 556",
      "city": "Gwenborough",
      "zipcode": "92998-3874",
      "geo": {
        "lat": "-37.3159",
        "lng": "81.1496"
      }
    },
    "phone": "1-770-736-8031 x56442",
    "website": "hildegard.org",
    "company": {
      "name": "Romaguera-Crona",
      "catchPhrase": "Multi-layered client-server neural-net",
      "bs": "harness real-time e-markets"
    }
  },
  ...
----