= Install and Run as a Kubernetes Ingress Controller
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

You can install Anypoint Flex Gateway as an Ingress controller - a specialized Kubernetes application that routes external traffic to internal applications and services. The following procedures demonstrate how to install and run Flex Gateway as an Ingress controller.

== Dependencies

* https://kubernetes.io/docs/tasks/tools/#kubectl[kubectl,^] a tool used to interact with Kubernetes clusters.
* https://helm.sh/docs/intro/install/[Helm,^] a tool used to install Peregrine, monitoring tools and applications.

== Prepare the Environment

. Create a new Kubernetes cluster with a single server node: 
+
----
k3d cluster create flex-gateway-1 --k3s-arg "--disable=traefik@server:0" --port '443:443@server:0'
----
// ----
// k3d cluster create flex-gateway-1 --k3s-arg "--disable=traefik@server:0" --port '80:80@server:0'  --port '443:443@server:0'  --port '8080:8080@server:0'
// ----
+
The command should return the following: 
+
----
INFO[0042] Cluster 'flex-gateway-1' created successfully!
----

. https://drive.google.com/file/d/1lWC0aDvaVVD6RhkqeEt1u5ZVPlP9kyZT/view?usp=sharing[Download the Flex Gateway container^] and import the Docker container image: 
+
----
k3d image import -c flex-gateway-1 flex-gateway-1.0.0-alpha.1.tar
----
+
The command should return the following: 
+
----
INFO[0016] Successfully imported image(s)
INFO[0016] Successfully imported 1 image(s) into 1 cluster(s)
----

== Procedure 

. Execute the following `helm upgrade` command to install Flex Gateway: 
+
----
helm -n gateway upgrade -i --wait --create-namespace ingress peregrine/peregrine --set image.name=mulesoft/flex-gateway:1.0.0-alpha.1
----
+
The command should return something like the following: 
+
----
NAME: ingress
LAST DEPLOYED: Tue Oct 19 13:08:07 2021
NAMESPACE: gateway
STATUS: deployed
REVISION: 1
TEST SUITE: None
----

. Verify that the Flex Gateway Ingress Controller is running:
+
----
kubectl -n gateway get svc,apiinstances
---- 
+
The command returns output similar to the following: 
+
----
NAME              TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
service/ingress   LoadBalancer   10.43.64.139   172.19.0.3    80:30426/TCP,443:31828/TCP   118s

NAME                                             ADDRESS
apiinstance.gateway.mulesoft.com/ingress-https   http://0.0.0.0:443/
apiinstance.gateway.mulesoft.com/ingress-http    http://0.0.0.0:80/
----

. Create a namespace for a sample application: 
+
----
kubectl create namespace app
----

. Forward the local connection to port 80:  
+
----
kubectl --namespace gateway port-forward service/ingress 8080:80
----
+
The command returns the following: 
+
----
Forwarding from 127.0.0.1:8080 -> 80
Forwarding from [::1]:8080 -> 80
----
+
NOTE: `kubectl port-forward` does not return. Open a new terminal to continue. 

. Verify that the URL and port are accessible: 
+
----
curl -v http://127.0.0.1:8080/
----
+
The command returns a `404 Not Found` error because an application listening at that address hasn't yet been deployed.

. Apply the following configuration: 
+
----
cat <<EOF | kubectl apply -f -
---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: ApiInstance
metadata:
  name: ingress-http
  namespace: app
spec:
  address: http://0.0.0.0:8080/
---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Service
metadata:
  name: jsonplaceholder
  namespace: app
spec:
  address: https://jsonplaceholder.typicode.com:443/
---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: PolicyBinding
metadata:
  name: jsonplaceholder-route
  namespace: app
spec:
  targetRef:
    kind: ApiInstance
    name: ingress-http
    namespace: app
  policyRef:
    kind: Extension
    name: route
    namespace: gateway
  config:
    destinationRef:
      kind: Service
      name: jsonplaceholder
      namespace: app
  rules:
    - path: /api/jsonplaceholder(/.*)
---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: PolicyBinding
metadata:
  name: app-auth
  namespace: app
spec:
  targetRef:
    kind: ApiInstance
    name: ingress-http
    namespace: app
  policyRef:
    kind: Extension
    name: basic-authentication
    namespace: gateway
  config:
    username: foo
    password: bar
  rules:
    - methods: POST
---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: PolicyBinding
metadata:
  name: app-access-logs
  namespace: app
spec:
  targetRef:
    kind: ApiInstance
    name: ingress-http
    namespace: app
  policyRef:
    kind: Extension
    name: access-log
    namespace: gateway
  config: {}
EOF
----
+
The configuration creates a service called `jsonplaceholder`, specifies its implementation address, and then defines path rules.
+
Additionally, the configuration applies a policy called `basic-authentication`, and specifies credentials that incoming requests use when accessing the `jsonplaceholder` service.

. Test the service by executing the following command: 
+
----
curl -v -u foo:bar http://127.0.0.1:8080/api/users/1
----
+
The result should include the following: 
+
----
[
  {
    "id": 1,
    "name": "Leanne Graham",
    "username": "Bret",
    "email": "Sincere@april.biz",
    "address": {
      "street": "Kulas Light",
      "suite": "Apt. 556",
      "city": "Gwenborough",
      "zipcode": "92998-3874",
      "geo": {
        "lat": "-37.3159",
        "lng": "81.1496"
      }
    },
    "phone": "1-770-736-8031 x56442",
    "website": "hildegard.org",
    "company": {
      "name": "Romaguera-Crona",
      "catchPhrase": "Multi-layered client-server neural-net",
      "bs": "harness real-time e-markets"
    }
  },
  ...
----

A secured service is now running behind Flex Gateway.

== Next Steps

* xref:microgateway-view-manage-log-output.adoc[View and Manage Log Output].
* Refer to the xref:microgateway-configuration-reference.adoc[Configuration Reference].