= Transport Layer Security Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:keywords: tls, transport layer security, api gateway, flex gateway, gateway, policy

[%autowidth.spread,cols="a,a"]
|===
>s| Policy Name | Transport Layer Security (TLS)
>s|Summary      | Enables HTTPS
>s|Category | Security
>s| First Mule version available | TLS cannot be applied as a policy in Mule.
>s| First Flex version available | v1.0.0
.4+>.^s| Returned Status Codes | No return codes exist for this policy.
[%autowidth.spread,cols="a,a"]
| 
|===

== Summary

HTTPS uses encryption to protect the communication between the client and Flex Gateway. To use HTTPS as your schema, bind the Transport Layer Security policy to your API instance. 

== Configuring Policy Parameters

=== Flex Gateway

To use HTTPS as your schema
when creating an API Instance using Flex Gateway as your runtime, you must manually configure the TLS context
in a YAML configuration file. Refer to the following policy definition and table of parameters:

----
- policyRef:
    name: tls
  config:
    certificate: // REQUIRED
        key: <string> // REQUIRED
        crt: <string> // REQUIRED
    alpn: <array> // OPTIONAL
    minversion: <string> // OPTIONAL
    maxversion: <string> // OPTIONAL
    ciphers: <array> // OPTIONAL
----

[%header%autowidth.spread,cols="a,a,a,a"]
|===
|Parameter | Required or Optional | Default Value | Description

| `certificate` 
| Required
| N/A
| A TLS certificate key pair

| `certificate.key` 
| Required
| N/A
| The private key part of the certificate

| `certificate.crt` 
| Required
| N/A
| The public key part of the certificate

| `alpn` 
| Optional
| 
|A prioritized list of supported application level protocols; for example, h2, http/1.1, and so forth.

| `minversion` 
| Optional
| 
|The minimum TLS version allowed

| `maxversion` 
| Optional
| 
|The maximum TLS version allowed

| `ciphers` 
| Optional
| 
|A list of supported TLS ciphers (IANA format)

|===

==== Resource Configuration Example

// intro 
include::gateway::partial$task-tls-config.adoc[tags=intro2]
// sample config applied to all apis on gateway intro
include::gateway::partial$task-tls-config.adoc[tags=sample-config-all-intro]
//sample config applied to all apis on gateway
include::gateway::partial$task-tls-config.adoc[tags=sample-config-all]
//sample config applied a specific api intro
include::gateway::partial$task-tls-config.adoc[tags=sample-config-instance-intro]
//sample config applied to a specific api
include::gateway::partial$task-tls-config.adoc[tags=sample-config-instance]

After adding your private key and certificate information, verify that the policy was correctly applied. The following `curl` command tests an HTTPS endpoint with an example certificate that matches the certificate specified in the policy binding configuration resource.

----
curl https://localhost/api/httpbin/get -v --cacert ./tls-certs/test.crt
----

The command should return information on the TLS handshake, as well as an HTTP status of `200` for the endpoint:

----
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server did not agree to a protocol
...
> HTTP/1.1 200 OK
----

[NOTE]
====
The configuration `key` and `crt` values must be correctly indented, otherwise `curl` returns the following error when attempting to test the endpoint:
----
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
----
====