= Troubleshooting Request Connection
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

When configuring and running Flex Gateway, you might encounter connection issues. 

You can troubleshoot the request connection between the API upstream and Flex Gateway, as well as the connection between Flex Gateway and the client, by isolating the connections. Isolating Flex Gateway connections allows you to localize the issue.

== Isolate Connection Between the API Upstream and Flex Gateway
Isolating the connection between the API upstream and Flex Gateway allows you to test for a connection issues between the two.

To isolate the connection between the API upstream and Flex Gateway:

. Log into the Flex Gateway container or VM:

* Linux
+
[source,ssh]
----
ssh [-i sshkey.pem] <user>@<domain>
----


* Docker:
+
[source,ssh]
----
docker exec -it <container-id> bash
----


* Kubernetes:
+
[source,ssh]
----
kubectl -n <namespace> exec -it <pod-name> -- bash
----

. Make a request to the upstream:
+
[source,ssh]
----
curl -v <http://upstream.domain>
----

== Isolate Connection Between Flex Gateway and the API Upstream

Isolating the connection between the Flex Gateway and the client allows you to test if the connection issue is due to a load balancer or another system in between the gateway and the client.

To isolate the connection between Flex Gateway and the client:

. Log into the Flex Gateway container or VM:

* Linux
+
[source,ssh]
----
ssh [-i sshkey.pem] <user>@<domain>
----


* Docker:
+
[source,ssh]
----
docker exec -it <container-id> bash
----


* Kubernetes:
+
[source,ssh]
----
kubectl -n <namespace> exec -it <pod-name> -- bash
----


. Make a request to Flex Gateway
+
[source,ssh]
----
curl -v http://localhost:<api-instance-port>/<path>
--