= Deleting an Instance of Flex Gateway
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: runtime-manager::flex-gateway-delete.adoc
:imagesdir: ../assets/images

To delete a gateway and its replicas in Runtime Manager:

. From Anypoint Platform, select *Runtime Manager*.
. Select *Flex Gateway* in the navigation menu.
. Click the action menu button for the gateway that you want to delete.
. Click *Delete gateway*.

If there are APIs associated with the gateway you want to delete, Runtime Manager displays a message that prompts you to either:

* Move the associated APIs to another gateway.
* Delete all associated APIs.

Once you moved or deleted all the associated APIs, follow the steps previously described to delete a gateway and confirm the deletion.

== Flex Gateway Status

The following table describes the meaning of each gateway status:

[%header,cols="20a,50a"]
|===
|Status Name |Description
|Connected |Gateway is connected to the platform, and you can add APIs to it.
|Disconnected |Gateway is not connected to the platform.
|Deleting | Gateway is in the process of being deleted.
|Deleted | Gateway was deleted from the platform. It stops accepting API requests and configuration changes, and stops reporting metrics.
|===

Deleted gateways are shown with status `Deleted` for 30 days before the status is removed from the gateways list.

[NOTE]
If you delete a gateway, you lose its configuration history and cannot recover it.