= Configure Logging for Flex Gateway in Local Mode
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

include::partial$task-config-logs-third-party.adoc[tags=intro1]

include::partial$task-config-logs-third-party.adoc[tags=icon-table]

include::partial$task-config-logs-third-party.adoc[tags=byb]

include::partial$task-config-logs-third-party.adoc[tags=runtime-access-logs]

include::partial$task-config-logs-third-party.adoc[tags=file-example]

include::partial$task-config-logs-third-party.adoc[tags=linux;view-logs-local;configure-message-logging-step]

include::partial$task-config-logs-third-party.adoc[tags=docker;view-logs-local;configure-message-logging-step]

include::partial$task-config-logs-third-party.adoc[tags=k8s;view-logs-local;configure-message-logging-step]

include::partial$task-config-logs-third-party.adoc[tags=file-configuration-example]

include::partial$task-config-logs-third-party.adoc[tags=http-configuration-example]

include::partial$task-config-logs-third-party.adoc[tags=splunk-configuration-example]

[[access-logs]]
== Configure Access Logs

After specifying access log output (as described in the previous configuration examples), you must enable access logs via policy binding. 

For inline configurations, enable access logs by adding `message-logging-flex` to the `spec.policies` section of `ApiInstance`. The following is an inline configuration example:

----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: ApiInstance
metadata:
  name: jsonplaceholder-api
spec:
  address: http://0.0.0.0:8080
  services:
    jsonplaceholder:
      address: https://jsonplaceholder.typicode.com:443/
      routes:
        - rules:
            - path: /api(/users/.*)
  policies:
    - policyRef:
        name: message-logging-flex
      config:
        loggingConfiguration:
          - itemName: "Access Log Request"
            itemData:
              message: "#[attributes.version ++ ' ' ++ attributes.method ++ ' ' ++ attributes.requestUri]"
              level: "INFO"
              firstSection: true
          - itemName: "Access Log Response"
            itemData:
              message: "#[attributes.statusCode ++ ' ' ++ (attributes.headers['content-length'] default '')]"
              level: "INFO"
              secondSection: true
----

For resource-based configurations, enable access logs by adding `message-logging-flex` to the `spec.policyRef` section of `PolicyBinding`. The following is a resource-based configuration example:

----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: PolicyBinding
metadata:
  name: ingress-http-access-logs
spec:
  targetRef:
    kind: ApiInstance
    name: ingress-http
  policyRef:
    kind: Extension
    name: message-logging-flex
  config:
    loggingConfiguration:
      - itemName: "Access Log Request"
        itemData:
          message: "#[attributes.version ++ ' ' ++ attributes.method ++ ' ' ++ attributes.requestUri]"
          level: "INFO"
          firstSection: true
      - itemName: "Access Log Response"
        itemData:
          message: "#[attributes.statusCode ++ ' ' ++ (attributes.headers['content-length'] default '')]"
          level: "INFO"
          secondSection: true
----

For more information about message logging configuration, see xref:policies::policies-included-message-logging.adoc[].



== See Also

* xref:policies::policies-included-message-logging.adoc[]
* https://docs.fluentbit.io/manual/v/1.8/pipeline/outputs[Fluent Bit Outputs documentation ^]
* xref:flex-local-third-party-logs-config.adoc[]