= Add Flex Gateway Replicas to a Namespace
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

For high availability (HA) environments, horizontal scaling distributes load across multiple Flex Gateway instances. By default, the Helm chart for Flex Gateway is configured with one replica. To release more Flex Gateway replicas in a namespace, use `--set replicaCount` with `helm upgrade`. 

//how to view helm chart defaults:
include::partial$reference-k8-general.adoc[tags=flex-k8-helm-chart-info]

== Before You Begin

Ensure that the following prerequisites are in place:

* A Flex Gateway deployment or a registered Flex Gateway instance (gateway)
+
For gateway registration and deployment processes, see xref:flex-gateway-set-up.adoc[] or xref:flex-gateway-k8-getting-started.adoc[]. 

* A Kubernetes cluster for your Flex Gateway deployment

== Update the Replica Count

Configure and verify the number of replicas that you require. The update steps to follow depend on whether a Helm chart is installed. 

. If a Helm chart for your namespace is installed, run the following command:
+
.Syntax:
----
help -n <namespace> upgrade \
<release-name> <helm-repository-name>/<helm-chart-name> \
--reuse-values \
--set replicaCount=<number of replicas>
----
+
.Example:
[source,helm]
----
helm -n gateway upgrade \
ingress flex-gateway/flex-gateway \
--reuse-values \
--set replicaCount=2
----
+
When successful, the command returns output similar to this: 
+
----
Release "ingress" has been upgraded. Happy Helming!
NAME: ingress
LAST DEPLOYED: Mon Apr 17 15:00:09 2023
NAMESPACE: gateway
STATUS: deployed
REVISION: 27
TEST SUITE: None
----

. If the Helm chart is not installed, run the following command:
+
.Syntax:
----
helm -n <namespace> \
upgrade -i --create-namespace \
<release-name> <helm-repository-name>/<helm-chart-name> \
--set-file registration.content=<registration file> \
--set replicaCount=<number of replicas>
----
+
.Example:
[source,helm]
----
helm -n gateway \
upgrade -i --create-namespace \
ingress flex-gateway/flex-gateway \
--set-file registration.content=registration.yaml \
--set replicaCount=2
----
+
When successful, the command prints output similar to this example: 
+
----
Release "ingress" does not exist. Installing it now.
NAME: ingress2
LAST DEPLOYED: Mon Apr 17 15:32:50 2023
NAMESPACE: gateway
STATUS: deployed
REVISION: 1
TEST SUITE: None
----

. Verify creation of the replicas by running the following command:
+
.Syntax:
----
kubectl get rs -n <namespace>
----
+
.Example:
----
kubectl get rs -n gateway
----
+
When successful, the command prints output similar to this example: 
+
----
NAME                  DESIRED   CURRENT   READY   AGE
ingress-5b7474b8f6    2         2         2       70s
----
