= Configure Flex Gateway as an Ingress Controller in Local Mode

For Kubernetes deployments in Local Mode, Flex Gateway typically acts as an ingress controller that manages external access to your Kubernetes cluster.

As an ingress controller, Flex Gateway manages `Ingress` resources that are created manually or though a continuous integration/continuous development (CI/CD) pipeline.

Ingress controllers are defined by using `IngressClass` resources. By default, in the Helm chart, the following parameters enable Flex Gateway as an ingress controller:

[source,helm]
----
ingressClass.enabled: true
ingressClass.name: "{releaseName}-{namespace}"
ingressClass.setAsDefault: false
----

[cols="1,2,2"]
|===
| Parameter | Description | Possible values
| `ingressClass.enabled` | If this Flex Gateway is enabled as an `IngressClass` | `true` or `false`, `true` by default
| `ingressClass.name` | The name of the `IngressClass` | Any string, by default, the name is the release name and the Kubernetes namespace separated by a dash.
| `ingressClass.setAsDefault` | If this Flex Gateway is the default `IngressClass` | `true` or `false`, `false` by default
|===

To modify the default `IngressClass` parameters, you must update your Helm chart. You can modify these parameters at the initial installation of the Helm chart or after. For more information about how to modify a Helm chart, see xref:flex-gateway-k8-change-helm-settings.adoc[]

By setting `ingressClass.setAsDefault: true`, you define the Flex Gateway instance as the default `IngressClass` resource for the cluster. When you create `Ingress` resources, the default `IngressClass` resource, is set as the default ingress controller of new resources. If you create an `Ingress` resource and do not have a default `IngressClass` defined or do not want the default `IngressClass` resource as the `IngressClass` for that resource, you must manually define the `IngressClassName` for that resource.


== Before You Begin

Register and deploy Flex Gateway to a Kubernetes cluster. For guidance, see xref:flex-gateway-set-up.adoc[] or xref:flex-gateway-k8-getting-started.adoc[].
