= Deleting an Instance of Flex Gateway
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: runtime-manager::flex-gateway-delete.adoc
:imagesdir: ../assets/images

To delete a gateway and its replicas in Runtime Manager:

. From Anypoint Platform, select *Runtime Manager*.
. Select *Flex Gateway* in the left menu.
. Click the action menu button for the gateway you want to delete.
. Click Delete gateway.

If there are APIs associated to the gateway you want to delete, Runtime Manager displays a message prompting you to either:

* Move the associated APIs to another gateway; or
* Delete all associated APIs.

Once you have moved or deleted all the associated APIs, follow the steps previously described to delete a gateway and confirm the deletion.

== Flex Gateway Status

The following table describes the meaning of each status for a gateway:

[%header,cols="20a,50a"]
|===
|Status Name |Description
|Connected |Gateway is connected to the platform and you can add APIs to it.
|Disconnected |Gateway is not connected to the platform.
|Deleting | Gateway is in the process of being deleted.
|Deleted | Gateway is deleted from the platform, it stops accepting API requests and configuration changes, and stops reporting metrics.
|===

Deleted gateways are shown with status **Deleted** for 30 days before it is removed from the gateways list.

[NOTE]
If you delete a gateway, you lose all its configuration history and will not be able to recover it.