= Configuring TLS Context for Flex Gateway in Connected Mode
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:page-mode: conn

// Add TLS Context intro
include::anypoint-security::partial$task-flex-add-tls-context.adoc[tags=intro1;intro2]

include::partial$task-tls-config.adoc[tags=intro3]

== Before You Begin
Before configuring the TLS context for a Flex Gateway Connected Mode, complete the following tasks:

* xref:flex-install.adoc[Install Flex Gateway]
* xref:flex-{page-mode}-reg-run.adoc[Register and Run Flex Gateway]
* xref:anypoint-security::asm-secret-group-creation-task.adoc[Create a Secret Group]
* xref:anypoint-security::asm-secret-group-creation-task.adoc#adding-a-keystore[Add a PEM Type Keystore]


== Add a TLS Context for Flex Gateway in Secrets Manager
// Add TLS Context in Secrets Manager
include::anypoint-security::partial$task-flex-add-tls-context.adoc[tags=addContext]
// configure TLS context for Flex Gateway Connected Mode



== Apply a TLS Context to an API in API Manager

To apply a TLS context to an API Instance in Flex Gateway Connected mode, you must first xref:api-manager::create-instance-task.adoc[create a Flex Gateway API Instance]. After you have create an API Instance, you can then apply a TLS context to the API. You can also apply a TLS context during the xref:api-manager::configure-api-task.adoc#configure-an-api-instance-on-flex-gateway-options[endpoint configuration step] of creating an API Instance. However, this tutorial only explains how to apply a TLS context when editing the endpoint of an existing API Instance.

To apply a TLS context to an API Instance in Flex Gateway Connected mode:

. Go to *Anypoint Platform > API Manager*.

. In *API Administration* click the name of the API you want to add TLS context to.

. Click *Runtime & Endpoint Configuration*. 

. Select *HTTPS*.

. Specify the *Port*.

. Add TLS context for inbound traffic, outbound traffic, or both. 
+
To add TLS context for either direction:

.. Click *Add TLS Context*.

.. Select a *Secret Group*.

.. Select a *TLS Context*.

.. Click *Ok*.

+
If adding outbound TLS context, first click *Advanced options*.

. Click *Save & Apply*.

//redeploy

include::anypoint-security::partial$task-flex-add-tls-context.adoc[tags=redeploy]
//Redeploy

== TLS Context Port Sharing
Though a port must have an API Instance to have a TLS context applied, it is easiest to think of TLS context as being applied to the port rather than the API Instance. 

Applying a TLS context to an API Instance that shares its port with other instances applies the TLS context to all instances sharing the port.

When you apply or edit the TLS context of an API Instance sharing a port, API Manager shows a warning with a list of the instances sharing the port. You can then choose to override the TLS context of the listed API Instances. Overriding the TLS context of the API Instances that share the port applies the TLS context to the instances and then redeploys the instances.

Overriding the TLS context of deployed API Instances redeploys the instances. Redeploying causes a brief period of downtime in the API Instances.

If you edit the port of an API Instance that previously shared a port and TLS context with other instances, the TLS context remains applied to the instances on the previous port.

//Ciphers
include::anypoint-security::partial$flex-tls-cipher.adoc[tags=connectedSelect;cipherSupport;ciphers]

//Ciphers
== See Also

* xref:flex-local-tls-config.adoc[Configuring TLS Context for Flex Gateway in Local Mode]
* xref:policies::policies-included-tls.adoc[Transport Layer Security Policy]