= Viewing the Replica Status in Runtime Manager
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: runtime-manager::flex-gateway-replica-status.adoc
:imagesdir: ../assets/images

In Runtime Manager, you can view the status of groups of Flex Replicas and individual Flex Replicas.

== Groups of Flex Replicas

To view information about the status of groups of Flex Gateway replicas:

. From Anypoint Platform, select *Runtime Manager*.
. Select *Flex Gateway* in the navigation menu. +
By default, all Flex Gateways are shown. To filter by status, click the *Any Status* arrow and the status you want to filter.

The *Name* column lists the name and the number of connected replicas.

The *Status* column shows the connection status for the replicas associated with a particular gateway.

The following table describes the meaning of each status for a group of replicas:

[%header,cols="30a,70a"]
|===
|Status | Group of Replicas
|Connected | At least one replicas is to the platform and are serving traffic.
|Disconnected | There are no replicas connected to the platform and no information on whether they are serving traffic.
|===

== Individual Flex Replicas

To view information about the status of groups or individual replicas:

. From Anypoint Platform, select *Runtime Manager*.
. Select *Flex Gateway* in the navigation menu.
. Select the name of the Flex Gateway whose individual replica statuses you want to view. +
By default, disconnected replicas are not shown. To view disconnected replicas, select *Show disconnected Replicas*. 

The *Status* column in the list of replicas shows the connection status for that particular replica.

The following table describes the meaning of each status for a single replica:

[%header,cols="30a,70a"]
|===
|Status |Single Replica
|Connected | The replica is connected to the platform and is serving traffic.
|Disconnected |The replica is not connected to the platform. There is no information on whether it is serving traffic. Flex Gateway unregisters disconnected replicas after a period of inactivity.
|===