= Configuring a Health Check for Flex Gateway in Connected Mode

include::partial$health-check-partial.adoc[tags=intro1]
 
include::partial$health-check-partial.adoc[tags=tlsImportant]

== How Health Check Works

include::partial$health-check-partial.adoc[tags=intro2]

== Before You Begin

Before configuring message logging for a Flex Gateway, complete the following tasks:

* xref:flex-install.adoc[Install Flex Gateway]
* xref:flex-conn-reg-run.adoc[Register and Run Flex Gateway]
* xref:api-manager::create-instance-task.adoc[Add an API Instance]

== Configure a Health Check Policy

. Go to *Anypoint Platform > API Manager*.
. From API Administration, select the name of the API Instance.
. Click *Policies*.
. Click *+ Add policy*.
. Under the *Quality of service* category, click *Health Check*.
. Click *Next*.
. Configure the following parameters:
+
include::partial$health-check-partial.adoc[tlsImportant1]

. Click *Apply & continue to Create Alert*.

== Configure a Health Check Alert
You are required to create an alert for the Health Check policy. Applying the policy navigates you to the Create Alert page, where you must create an alert.

Creating an alert for a Health Check Policy is the same as the xref:gateway::flex-use-api-alerts.adoc[Using Flex Gateway API Alerts] task. However, when creating a Health Check alert after creating a Health Check policy, some fields are configured by default.

To create an alert:

. Specify values for the displayed alert options:
* *Name*:
+
Type an alert name, for example `trial-alert`. You can delete an alert anytime if not required.
* *Severity*:
+
Select a severity for the alert:

** *Info*
+
Assign to alerts that do not require immediate attention when triggered. This severity indicates that the metric should be passively monitored.
** *Warning*
+
Assign to alerts that require prompt attention when triggered. This severity indicates an alert should be closely monitored.
** *Critical*
+
Assign to alerts that require immediate attention when triggered. This severity indicates an alert should receive an immediate response.

. Configure the email notification:

* *Subject*
+
Subject of the alert email to send when the alert is triggered. The subject can include variables. See <<alert-variables>>.

* *Message*
+
Body text for the email to send when the alert is triggered. The message body can include variables. See <<alert-variables>>.

* *Recipients*
+
Recipients of the alert email. You can select up to 20 platform user IDs and enter up to 20 email addresses.

. Click *Create*.

Alerts appear as *Pending* when they are created. After the Health Check request is made, the alert changes to a state of *OK*. Depending on the value, the alert transitions to *OK* or *Alerting*.
