= Configuring TLS Context for Flex Gateway in Connected Mode
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:page-mode: conn

// Add TLS Context intro
include::anypoint-security::partial$task-flex-add-tls-context.adoc[tags=intro1;intro2]


== Before You Begin
Before configuring the TLS context for a Flex Gateway Connected Mode, you must complete the following tasks:

* xref:flex-install.adoc[Install Flex Gateway]
* xref:flex-{page-mode}-reg-run.adoc[Register and Run Flex Gateway]
* xref:anypoint-security::asm-secret-group-creation-task.adoc[Create a Secret Group]
* xref:anypoint-security::asm-secret-group-creation-task.adoc#adding-a-keystore[Add a Keystore]


== Add a TLS Context for Flex Gateway
// Add TLS Context in Secrets Manager
include::anypoint-security::partial$task-flex-add-tls-context.adoc[tags=addContext]
// configure TLS context for Flex Gateway Connected Mode

== Apply a TLS Context to an API
include::anypoint-security::partial$task-flex-add-tls-context.adoc[tags=intro3]

To apply TLS context to an API Instance in Flex Gateway Connected mode:

. Go to *Anypoint Platform > API Manager*.

. Create a new API Instance deployed with Flex Gateway or edit the endpoint of an existing Flex Gateway API Instance:

* To the create a new API using Flex Gateway as the runtime, complete the xref:api-manager::create-instance-task.adoc[Adding an API Instance] task up to the endpoint configuration page.

* To edit an the existing existing endpoint of an API Instance, in *API Administration* click the name of the API you want to add TLS context to, then click *Runtime & Endpoint Configuration*. 

. Configure the end point up to *Scheme* or begin editing the existing API Instance. For more information on configuration, see xref:api-manager::configure-api-task.adoc#configure-an-api-instance-on-flex-gateway-options[Configure an API Instance on Flex Gateway Options].

. Select *HTTPS*.

. Specify the *Port*.

. Add TLS context for inbound traffic, outbound traffic, or both. If adding outbound TLS context, first click *Advanced options*, then to add TLS context for either traffic direction:

.. Click *Add TLS Context*.

.. Select a *Secret Group*.

.. Select a *TLS Context*.

.. Click *Ok*.

. Click *Save & Apply*.


== TLS Context Port Sharing
Applying a TLS context to a port applies the TLS context to all API Instances that share that port.

If you apply a TLS context to an API Instance that shares a port with another instance, a warning with a list of the API Instances that share the port is provided. You can choose to override the TLS context of the API Instances that share port. Overriding the TLS context of the API Instances that share the port applies the TLS context to the instances.

Editing the port of an API Instance that has a TLS context applied does not remove the TLS context from the other API Instances that share that port.

Ports

== See Also

* xref:flex-local-tls-config.adoc[Configuring TLS Context for Flex Gateway in Local Mode]
* xref:policies::policies-included-tls.adoc[Transport Layer Security Policy]