= Configure Flex Gateway as an Ingress Controller in Local Mode
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

For Kubernetes deployments in Local Mode, Flex Gateway typically acts as an ingress controller that manages external access to your Kubernetes cluster.

As an ingress controller, Flex Gateway manages `Ingress` resources that are created manually or through a continuous integration/continuous development (CI/CD) pipeline.

Ingress controllers are defined by using `IngressClass` resources. By default, a Flex Gateways deployed on Kubernetes in Local Mode are defined as `IngressClass` resources.

== Ingress Class Parameters
By default, in the Helm chart, the following parameters configure Flex Gateway as an `IngressClass` resource:

[source,helm]
----
ingressClass.enabled: true
ingressClass.name: "{releaseName}-{namespace}"
ingressClass.setAsDefault: false
----

[cols="1,2,2"]
|===
| Parameter | Description | Possible values
| `ingressClass.enabled` | If this Flex Gateway is enabled as an `IngressClass` | `true` or `false`, `true` by default
| `ingressClass.name` | The name of the `IngressClass` | Any string, by default, the name is the release name and the Kubernetes namespace separated by a dash.
| `ingressClass.setAsDefault` | Set this Flex Gateway as the default `IngressClass` | `true` or `false`, `false` by default
|===

By setting `ingressClass.setAsDefault: true`, you define the Flex Gateway instance as the default `IngressClass` resource for the cluster. The default `IngressClass` is the default ingress controller for all `Ingress` resources created in the cluster. 

If you do not have a default `IngressClass` defined or do not want the default `IngressClass` resource as the `IngressClass` for a resource, you must manually define the `IngressClassName` for that resource.

To modify the default `IngressClass` parameters, you must update your Helm chart. You can modify these parameters at the initial installation of the Helm chart or after. For more information about how to modify a Helm chart, see xref:flex-gateway-k8-change-helm-settings.adoc[]

== Creating Ingress Resources

After you xref:flex-local-reg-run-up#install-helm-chart-into-the-namespace[install a Helm chart into a namespace], you can confirm your new `IngressClass` resource is present by running the following command:

[source,helm]
----
kubectl get ingressclasses
----

If your `IngressClass` resource is present, the name you defined for `ingressClass.name` is present.



== See Also
