= Securing and Governing Flex Gateway APIs
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

Policies enforce rules when processing requests, thereby enabling you to secure and govern your Flex Gateway APIs.

MuleSoft provides several policies that you can apply to your APIs via Anypoint Platform (Connected Mode), or via declarative configuration files (Local Mode). Provided policies include rate limiting, caching, authentication, authorization, threat protection, monitoring, and logging.

For more information about MuleSoft-provided policies, see the xref:policies-included-directory.adoc[].

You can create custom policies based on your specific business requirements and apply them to APIs to extend existing functionality or define new functionality. For information about creating custom policies, see xref:policies-custom-overview.adoc[].

Automated policies enable your API instance to comply with common security and logging requirements by automatically applying the same set of policies to all APIs running in Flex Gateway. See xref:policies-automated-overview.adoc[] for more information.

== See Also

* xref:index.adoc[]
* xref:flex-gateway-getting-started.adoc[]