= Configuring Timeouts in Connected Mode
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:page-mode: conn

include::partial$timeout-configuration.adoc[tags=timeout-types]

You can configure these timeouts in Connected Mode via:

* Runtime Manager runtime configurations: Applies to all API instances in the gateway.
* Environment variables: Applies to all API instances and is the most permanent configuration option.
* Configuration YAML resource: Applies to all API instances and is easy to adjust.
* Policy: Applies to one API instance or upstream and provides granular control.

== Configure Timeouts in Runtime Manager

To configure timeout defaults for a Connected Mode gateway in Runtime Manager:

. In Anypoint Platform, select *Runtime Manager*.
. Select *Flex Gateways*.
. Select your Connected Mode Flex Gateway.
. Open *Runtime Configurations*.
. Open *Timeouts*.
. Set values for *Stream Idle Timeout*, *Upstream Connection Idle Timeout*, and *Upstream Response Timeout*.
. Apply the changes.

include::partial$timeout-configuration.adoc[tags=timeout-configuration-env-var]

include::partial$timeout-configuration.adoc[tags=timeout-configuration-yaml]

include::partial$timeout-configuration.adoc[tags=timeout-configuration-policies]
