= Configure Timeouts for Managed Flex Gateway
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

include::partial$timeout-configuration.adoc[tags=timeout-types]

You can configure these timeouts for Managed Flex Gateway via:

* Managed Flex Gateway deployment: Set initial timeout values when you create the gateway.
* Runtime Manager runtime configurations: Applies to all API instances in the gateway after the gateway is deployed.
* Environment variables: Applies to all API instances and is the most permanent configuration option.
* Configuration YAML resource: Applies to all API instances and is easy to adjust.
* Policy: Applies to one API instance or upstream and provides granular control.

== Configure Timeouts During Managed Gateway Deployment

Set timeout values in the deployment flow when you create a Managed Flex Gateway.
For the UI steps and parameter descriptions, see xref:flex-gateway-managed-set-up.adoc[].

:flex-gateway-timeout-label: Managed
include::partial$timeout-runtime-manager.adoc[tags=timeout-runtime-manager]

include::partial$timeout-configuration.adoc[tags=timeout-configuration-env-var]

include::partial$timeout-configuration.adoc[tags=timeout-configuration-yaml]

include::partial$timeout-configuration.adoc[tags=timeout-configuration-policies]
