= Configuring TLS for Outgoing Policy Requests
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: policy, custom

Some Flex Gateway policies make outgoing requests to HTTP and gRPC upstream service. For example, the xref:policies-included-oauth-token-introspection.adoc[] sends token validation requests to an OAuth 2.0 service, and the xref:policies-included-external-authorization.adoc[] forwards incoming client requests to an authorization service. 

By default, Managed and Self-Managed Flex Gateways protect these connections with a default TLS Context. The default TLS context is not mTLS and uses the default ciphers listed in <<local-support>>.

To overide the default TLS context, configure a custom default TLS context for all outgoing requests from policies. You can't configure a custom default TLS context for Managed Flex Gateway.

== Configure a TLS Context for Self-Managed Gateways

For both local and connected mode, use a YAML configuration file to configure TLS between a policy and an upstream service:

----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Configuration
metadata:
 name: default-tls
spec:
 defaultTLS:
   outboundPolicies:
       skipValidation: <boolean> // OPTIONAL
       trustedCA: <string> # OPTIONAL, defaults to the CA of operating systems
       certificate: // OPTIONAL
           key: <string> // OPTIONAL
           crt: <string> // OPTIONAL
       alpn: <array> // OPTIONAL
       minversion: <string> // OPTIONAL
       maxversion: <string> // OPTIONAL
       ciphers: <array> // OPTIONAL
       
----

Not including optional parameters in your configuration file applies the parameters default values to your TLS context.

When configuring the `ciphers` parameter, ensure that your API upstream supports the listed ciphers. For the supported ciphers, see <<local-support, TLS Cipher Support on Flex Gateway>>.

[%header%autowidth.spread,cols="a,a,a,a"]
|===
|Parameter | Required or Optional | Default Value | Description

| `skipValidation`
| Required
| false
| Skipping validation disables outbound mTLS.

| `trustedCA`
| Optional
| N/A
| The key used to validate the upstream server certificate. If no trusted CA is provided, the policys uses the default OS CA.

| `certificate`
| Optional
| N/A
| The client certificate to present for mTLS. To comply with security standards, all certificates must be 2048 bits or longer.

| `certificate.key`
| Optional
| N/A
| The private key part of the certificate.

| `certificate.crt`
| Optional
| N/A
| The public key part of the certificate.

| `alpn`
| Optional
| `h2` and `http/1.1`
| A prioritized list of supported application level protocols; for example, h2, http/1.1, and so forth.

| `minversion`
| Optional
| `1.2`
| The minimum TLS version allowed.

| `maxversion`
| Optional
| `1.3`
| The maximum TLS version allowed.

| `ciphers`
| Optional
| For the default and other supported ciphers, see <<local-support, TLS Cipher Support on Flex Gateway>>.
| A list of supported TLS ciphers (IANA format).

|===


include::partial$flex-tls-cipher.adoc[tags=cipherSupportLocal;outboundImportantLocal;local-ciphers]
