= MCP Schema Validation Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:keywords: api gateway, flex gateway, gateway, policy

[width="100%", cols="5,15"]
|===
>s| Policy Name | MCP Schema Validation
>s|Summary      | Validates MCP requests to ensure they conform to the MCP specification
>s|Category | MCP
>s|First Flex Gateway version available | v1.9.3
>s| Returned Status Codes |
|===

include::partial$mcp-version-support.adoc[]

== Summary

The MCP Schema Validation policy validates that every incoming request complies with JsonRPC MCP protocol (MCP 2024_11_05 standard). If validation fails it reports a Policy Violation.

When *Validate Tool Schema* is enabled, the policy also:
* Validates that the incoming request complies with the JSON schema of the MCP Server.
* Validates tool invocation request parameters against the JSON schema of the tool and returns the tools/list MCP request without having to send the request to the upstream MCP Server.

include::partial$policy-title-headers.adoc[tag=configFileTitleOnly]

The MCP Schema Validation policy isn't supported in Local Mode.

include::partial$policy-title-headers.adoc[tag=ui]

[%header%autowidth.spread,cols="a,a"]
|===
| Parameter| Description
| Validate Tool Schema | When enabled, the policy:

* Validates that the incoming request complies with the JSON schema of the MCP Server.
* Validates tool invocation request parameters against the JSON schema of the tool and returns the tools/list MCP request without having to send the request to the upstream MCP Server.
|===