
Applying a Message Logging policy to your API instance in API Manager allows you to view basic logs, such as inbound and outbound calls and headers, for APIs managed by Omni Gateway within API Manager. Logging for an API instance only happens if you configure and apply a Message Logging policy.

To view metrics in API Manager, such as total requests, total policy violations, total errors, and average response time, see xref:{page-mode}-view-api-metrics.adoc[].


NOTE: To use multiple log levels for different configurations, add multiple configurations within a single Message Logging policy. To learn more, see <<multiple-log-levels>>.

== Message Logging Limits and Features

include::reuse::partial$billing/pricing.adoc[tag=apimLogging] 

Basic logs report this information for each API instance configured through a policy:

* Inbound and outbound API calls, as well as the packet contents
* Headers and any other information in the request

To view message logs in API Manager, you need one of the following permissions:

* API Manager Environment Administrator
* API Manager Deploy API Proxies
* General Organization Administration

Refer to xref:access-management::permissions-by-product.adoc[].

[[configure-message-logging]]
== Configure Message Logging

. From *API Instances* in API Manager, select the name of the API Instance.
. Click *Policies*.
. Click *+ Add policy*.
. Click *Message Logging* in the *Troubleshooting* category.
. Click *Next*.
. Click *+ Add*.
. Enter a *Configuration Name*, for example, 'Info messages before calling API'.
. Enter a DataWeave expression that selects what information you want to see.
+
For example, `#[attributes.headers['id']]` extracts the ids from the headers of
the messages. For more information, see xref:policies-dataweave-support.adoc[].

. If you want to filter log messages, enter a DataWeave expression.
+
For example, `#[attributes.headers['id']==1]` shows log messages that have
an id of 1 in the header.

. If you want to affix a prefix to your logs, enter a *Category*.
. Enter the severity level.
+
You can only enter one level. See <<severity-levels, Message Logging Severity Levels>>
for a description of each severity level and the hierarchy for the levels.

. If you want messages after the API is called, select *After Calling API*.
. If you want to add additional configurations, click *+ Add*. For more information about configuring multiples levels, see <<multiple-log-levels>>.
. Click *Save*.
+
Afterward, you should see a *Message Log* option for the API instance.
+
Use the search field to search for specific logs based on the time and log severity (INFO, ERROR, WARN, DEBUG). You can download these logs for further analysis.

[[multiple-log-levels]]
=== Configuring Multiple Log Levels

To log messages at multiple levels or with different conditions within a single Message Logging policy:

. Apply one Message Logging policy to your API instance following the steps at <<configure-message-logging>>.
. Configure the first logging entry with your desired settings (for example, *Level*: INFO).
. Click *+ Add* to add another configuration.
. Configure the second logging entry with different settings (for example, *Level*: ERROR).
. Repeat steps 3-4 to add additional configurations as needed.
. Click *Save*.

For example, if you configure the parameter:

* *First configuration*:
** *Message*: `#[payload]`
** *Level*: INFO
** *Before Calling API*: Selected
* *Second configuration*:
** *Message*: `#[attributes.headers]`
** *Level*: ERROR
** *After Calling API*: Selected

This configuration logs the request payload at INFO level before calling the API and logs response headers at ERROR level after calling the API.

include::partial$logging-severity-level.adoc[]
