= Troubleshooting SOAP APIs
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

Flex Gateway does not natively support SOAP APIs and does not provide any schema validation for XML. However, you can publish an HTTP API instance to a secure SOAP upstream service.

To create an HTTP API instance to a secure SOAP API upstream service, refer to the following:

* xref:flex-gateway-publish-apis-conn.adoc[]
* xref:flex-gateway-publish-apis-local.adoc[]

== Publish a Soap API

Refer to the following video for additional information about how to publish a SOAP API as an HTTP API instance:

++++
include::_partials/soap-api-video.html[]
++++

== SOAP API Policy Limitations

Flex Gateway policies return JSON error messages when the policy blocks a request. Most SOAP clients cannot read the JSON messages.

SOAP APIs do not support the following policies:

* xref:policies-included-schema-validation.adoc[] 
* xref:policies-included-json-threat-protection.adoc[]
