= Traffic Management for Single Upstream Service
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:keywords: route, traffic management, single upstream service

[%autowidth.spread,cols="a,a"]
|===
>s| Policy Name | Traffic Management for Single Upstream Service
>s|Summary      | Manages API instance traffic to a single upstream service from a single consumer endpoint
>s| First Flex Gateway version available | v1.0.0
.4+>.^s| Returned Status Codes | No return codes exist for this policy.
[%autowidth.spread,cols="a,a"]
|
|===

[NOTE]
====
The following information applies only to Flex Gateway running in Local Mode. To configure an upstream service for Flex Gateway running in Connected Mode, refer to xref:api-manager::create-instance-task-flex.adoc[Adding a Flex Gateway API Instance in Connected Mode].
====

== Summary

Flex Gateway running in Local Mode supports API instances that expose single upstream services through a single consumer endpoint. For information about exposing multiple upstream services, refer to xref:policies-included-traffic-management.adoc[].

To allow routing requests to a Service when an `ApiInstance` does not include `spec.services`, you must define a `PolicyBinding` configuration with the Traffic Management for Single Upstream Service (`route`) policy. You do not need to configure a Traffic Management for Single Upstream Service (`route`) policy if a custom policy is managing requests.

== Configuring Policy Parameters

Refer to the following policy definition and table of parameters:

----
policyRef:
  name: route
config:
  destinationPath: <string> // OPTIONAL, default: "/"
  destinationRef:
      name: <string> // REQUIRED
      kind: <string> // OPTIONAL, default: "Service"
      namespace: <string> // OPTIONAL, default: ""
rules:
  - path: <URL-regex> // OPTIONAL, Example: (.*)
    methods: <regex-string> // OPTIONAL, Example: GET|POST
    headers:
      <header-name>: <regex-string> // OPTIONAL
    host: <regex-string> // OPTIONAL
----

[%header%autowidth.spread,cols="a,a,a,a"]
|===
| Parameter | Required or Optional | Default Value | Description

| `destinationPath`
| Optional
| "/"
| Path of the upstream service

| `destinationRef.name`
| Required
| N/A
| Name of the upstream service as defined in the `Service` configuration resource

| `destinationRef.kind`
| Optional
| "Service"
|

| `destinationRef.namespace`
| Optional
| ""
|

| `rules`
| Optional
| Empty
| Array of rulesets for this route. +
Each route can support multiple rulesets.

| `rules.path`
| Optional
| Empty
| Request path that the route can service. +
You can define only one “URI Template Regex" path for each ruleset. Only requests with the defined path are sent to this route.

| `rules.methods`
| Optional
| Empty
| Array that defines the types of request methods that the route can service. +
You can select multiple methods for each ruleset. Only requests that are one of the defined methods are sent to this route. Supported values are `GET`, `POST`, `PUT`, `PATCH`, `DELETE`, `OPTIONS`, `HEAD`, `TRACE`, and `CONNECT`.

| `rules.headers`
| Optional
| Empty
| Array that defines what headers and regular expression value must be present for this route to service the request. +
Only requests that meet all of the specified header requirements are sent to this route. Additional headers present in the request that are not specifically defined in the rules are ignored.

| `rules.host`
| Optional
| Empty
| Request host URL that the route can service. +
You can define only one host URL for each ruleset. Only requests made from the defined host are sent to this route.

|===

=== Resource Configuration Example

// The following example defines a rate limit of three requests every six seconds:

[source,yaml]
----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: ApiInstance
metadata:
  name: ingress-http
spec:
  address: http://0.0.0.0:8080/api # [1] ApiInstance.address.path
----

[source,yaml]
----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: PolicyBinding
metadata:
  name: ingress-httpbin-route
spec:
  targetRef:
    name: ingress-http
  policyRef:
    name: route
  config:
    destinationPath: /orders # [2] PolicyBinding(route).config.destinationPath
    destinationRef:
      name: orders-svc
  rules:
  - path: /foo(/.*) # [3] PolicyBinding(route).rules.path
----

[source,yaml]
----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Service
metadata:
  name: orders-svc
spec:
  address: https://orders.svc.local:443/
----

== See Also

* xref:policies-included-traffic-management.adoc[]
* xref:flex-local-publish-api-multiple-services.adoc[]