= External Processing Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:keywords: external processing, processing, flex gateway, gateway, policy


[width="100%", cols="5,15"]
|===
>s| Policy Name | External Processing
>s|Summary | 
>s|Category | Transformation
>s|First Flex Gateway version available | v1.6.0
.1+>.^s| Returned Status Codes
| 403 - IP is rejected
|===

== Summary


== Configuring Policy Parameters

=== Flex Gateway Local Mode

In Local Mode, you apply the External Processing policy to your API via declarative configuration files. Refer to the following policy definition and table of parameters:

----
- policyRef:
    name: native-external-proc
  config: 
    uri: <string> // REQUIRED
    messageTimeout: <integer> // OPTIONAL
    requestHeaderMode: <string> // OPTIONAL, default: "send"
    responseHeaderMode: <string> // OPTIONAL, default: "send"
    requestBodyMode: <string> // OPTIONAL
    responseBodyMode: <string> // OPTIONAL 
    requestTrailerMode: <string> // OPTIONAL, default: "send"
    responseTrailerMode: <string> // OPTIONAL, default: "send"
----

[%header%autowidth.spread,cols="a,a,a,a"]
|===

|Parameter | Required or Optional | Default Value | Description

| `uri`
| Required
| `http://ext.proc.com`
| 

| `messageTimeout`
| Optional
| `1000`
| Message timeout to processing server expressed in milliseconds

| `requestHeaderMode`
| Optional
| `send`
| Supported values are `send` and `skip`.

| `responseHeaderMode`
| Optional
| `send`
| Supported values are `send` and `skip`.

| `requestBodyMode`
| Optional
| `none`
| Supported values are `none`, `streamed`, `buffered`, and `bufferedPartial`.

| `responseBodyMode`
| Optional
| `none`
| Supported values are `none`, `streamed`, `buffered`, and `bufferedPartial`.

| `requestTrailerMode`
| Optional
| `send`
| Supported values are `send` and `skip`.

| `responseTrailerMode`
| Optional
| `send`
| Supported values are `send` and `skip`.

|===

==== Resource Configuration Example

----
- policyRef:
    name: ip-allowlist-flex
  config:
    ips:
      - "192.168.1.1"
      - "192.168.3.1/30"
      - "192.168.2"
      - "192.160"
----

=== Flex Gateway Connected Mode

When you apply the IP Allowlist policy to your API from the UI, configure the following parameters:

[%header%autowidth.spread,cols="a,a"]
|===
| Parameter | Description
|IP expression  |The DataWeave 2.0 used for extracting the IP address from this API request.
|Allowlist |The list of IP addresses allowed access to the API. You can define one IP or IP range at a time, as many times as required.  For more information, see <<specifying_ip_address,Specifying IP Addresses to Allowlist in Your Policy>>.
|Method & Resource conditions |The option to add configurations either to a select few or to all methods and resources of the API.
|===

[[specifying_ip_address]]
== Specifying IP Addresses to Allowlist in Your Policy 

Specify IP addresses to allow access to your policy based on:

* The IP address of the request
* The origin IP address that is determined by resolving a specific DataWeave expression, such as the https://en.wikipedia.org/wiki/X-Forwarded-For[x-Forwarded-For^] header
* Any other origin.

=== Allowlisting Access Based on the IP address of the Request

Allowlist access based on the IP address of the request in any of the following ways:

* Define a specific IP address by enumerating it in the Allowlist field, for example, `192.168.1.1`.
* Define a subset of addresses by identifying a subnet mask, for example, `192.168.3.1/30`, which includes the consolidated range `192.168.3.01` through `192.168.3.3`.
* Define a whole range of IP addresses by stating the relevant octets of the IP address you want to permit, for example, setting `192.168`, which includes IP addresses from `192.168.0.0` through `192.168.255.255`.


=== Allowlisting Access Based on the Origin IP Address of the x-Forwarded-For Header

If the client connects to your API through an HTTP proxy or a load balancer, you can allowlist the client's specific IP address (the IP address originating the request) instead of the address that appears in the request.

For example, if you want to allowlist `192.168.2.3`(private IP) and the address of a client connecting through an HTTP proxy is `92.40.1.255` (public IP), the client requests appear with the public address using the proxy.

Typically, applications use the `X-Forwarded-For` header to identify the origin IP addresses of a request that was redirected to your endpoint.

You can use a DataWeave 2.0 expression in the policy to instruct the service to look for the IP address in the `x-Forwarded-For` header.

When you insert the IP address in the IP expression field of the policy parameters, Anypoint Platform is instructed to look for the starting IP address in the concatenated values of the `x-Forwarded-For` header of the request.