= External Processing Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:keywords: external processing, processing, flex gateway, gateway, policy


[width="100%", cols="5,15"]
|===
>s| Policy Name | External Processing
>s|Summary | Sends requests to an external gRPC service for additional processing
>s|Category | Transformation
>s|First Flex Gateway version available | v1.6.0
.1+>.^s| Returned Status Codes
| 403 - IP is rejected
|===

== Summary

The External Processing policy is an extension of the External Processing filter native to Envoy. To learn more about the External Processing filter, see https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_proc/v3/ext_proc.proto[External Processing Filter^].

== Configuring Policy Parameters

=== Flex Gateway Local Mode

In Local Mode, you apply the External Processing policy to your API via declarative configuration files. Refer to the following policy definition and table of parameters:

[source,yaml]
----
- policyRef:
    name: native-external-proc
  config: 
    uri: <string> // REQUIRED
    messageTimeout: <integer> // OPTIONAL
    requestHeaderMode: <string> // REQUIRED, default: "send"
    responseHeaderMode: <string> // REQUIRED, default: "send"
    requestBodyMode: <string> // REQUIRED, default: "none"
    responseBodyMode: <string> // REQUIRED, default: "none"
    requestTrailerMode: <string> // OPTIONAL, default: "send"
    responseTrailerMode: <string> // OPTIONAL, default: "send"
----

[%header%autowidth.spread,cols="a,a,a,a"]
|===

|Parameter | Required or Optional | Default Value | Description

| `uri`
| Required
| NA
| External processing server URI. For gRPC type servers, define the URI as `\h2://<ext.authz.com>:<port>`.

| `messageTimeout`
| Required
| `1000`
| Message timeout to processing server expressed in milliseconds.

| `requestHeaderMode`
| Required
| `send`
| Whether the requests headers are sent to the processing service or not. Supported values are `send` and `skip`.

| `responseHeaderMode`
| Required
| `send`
| Whether the response headers are sent to the processing service or not. Supported values are `send` and `skip`.

| `requestBodyMode`
| Required
| `none`
| Mode the request body is sent in. Supported values are `none`, `streamed`, `buffered`, and `bufferedPartial`. Selecting `none` does not send the request body.

| `responseBodyMode`
| Required
| `none`
| Mode the response body is sent in. Supported values are `none`, `streamed`, `buffered`, and `bufferedPartial`. Selecting `none` does not send the request body.

| `requestTrailerMode`
| Required
| `send`
| Whether the requests trailer headers are sent to the processing service or not. Supported values are `send` and `skip`.

| `responseTrailerMode`
| Required
| `send`
| Whether the response trailer headers are sent to the processing service or not. Supported values are `send` and `skip`.

|===

NOTE: Leaving a required value blank configures the parameter as the default value. No value is set for optional values left blank.

==== Resource Configuration Example

This configuration sends both the request headers, trailers, and the request body in a streamed manner to the external proccessing server. This configuration does not send any part of the response to to the external proccessing server.

[source,yaml]
----
- policyRef:
    name: native-external-proc
  config: 
    uri: h2://<ext.authz.com>:<port>
    messageTimeout: <integer> // OPTIONAL
    responseHeaderMode: skip
    requestBodyMode: streamed
    responseTrailerMode: skip
----

=== Flex Gateway Connected Mode

When you apply the External Processing policy to your API from the UI, configure the following parameters:

[%header%autowidth.spread,cols="a,a"]
|===
| Parameter | Description
|External processing server URI | External processing server URI. For gRPC type servers, define the URI as `\h2://<ext.authz.com>:<port>`.
|Message timeout | Message timeout to processing server expressed in milliseconds.
|Request header processing mode | Whether the requests headers are sent to the processing service or not.
|Response header processing mode  | Whether the response headers are sent to the processing service or not.
|Request body processing mode | Mode the request body is sent in.
|Response body processing mode | Mode the response body is sent in.
|Request trailer processing mode | Whether the requests trailers are sent to the processing service or not.
|Response trailer processing mode | Whether the response trailers are sent to the processing service or not.
|===
