= External Authorization Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:keywords: external authorization, authorization, flex gateway, gateway, policy

[width="100%", cols="5,15"]
|===
>s|Policy name | External Authorization
>s|Summary | Authenticates requests with an external gRPC or HTTP authorization service
>s|Category | Security
>s| First Flex Gateway version available | v1.6.0
>s| Returned Status Codes | 403 - Forbidden, invalid client application credentials
|===

== Summary

The External Authorization policy is an extension of the External Authorization filter native to Envoy. To learn more about the External Authorization filter, see https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_authz_filter[External Authorization Filter^].

The External Authorization policy sends incoming HTTP requests to an external gRPC of HTTP authorization service to determine if the request is authorized to make calls to the Flex Replica. Flex Gateway returns a `403` forbidden request error for unauthorized access. Flex Gateway does not return a status code for valid requests.

If it is necessary to include request headers when sending the request to the authorization service, you can configure what headers are sent by using the *Allowed Headers* parameter

== Configuring Policy Parameters

=== Flex Gateway Local Mode

In Local Mode, you apply the External Authorization policy to your API via YAML configuration files. Refer to the following policy definition and table of parameters:

[source,yaml]
----
- policyRef:
    name: native-external-authz
  config:
    uri: <string> // REQUIRED
    serverType: <string> // REQUIRED, default: "grpc"
    serverVersion: <string> // REQUIRED, default: `v3`
    includePeerCertificate: <boolean> // REQUIRED, default: `false`
    allowedHeaders: <array> // OPTIONAL, default: []
----

[%header%autowidth.spread,cols="a,a,a,a"]
|===

|Parameter | Required or Optional | Default Value | Description

| `uri`
| Required
| NA
| External authorization service Uri. With gRPC type server, define the uri as `\h2://<ext.authz.com>:<port>`.

| `serverType`
| Required
| `grpc`
| Type of external server. Supported values are `grpc` and `http`.

| `serverVersion`
| Optional
| `v3`
| Transport protocol API version. Supported values are `v3` and `v2`.

| `includePeerCertificate`
| Optional
| `false`
| Includes peer certificates in the authorization server request. Supported values are `true` and `false`.

| `allowedHeaders`
| Optional
| NA
| By default, requests sent to gRPC servers include all client headers, and requests sent to HTTP servers do not include any client headers. If you list allowed headers for either server type, requests include only the listed headers.

|===

NOTE: Leaving a required value blank sets the value as the default value. No value is set for optional values left empty.

=== Resource Configuration Example

In the following example, all the headers matching the configured `#[attributes.requestPath]` expression are injected into the message.

[source,yaml]
----
- policyRef:
    name: native-external-authz
  config:
    uri: h2://ext-authz-grpc-service:9001
    serverType: "grpc"
    includePeerCertificate: "true"
    allowedHeaders: <array> // OPTIONAL, default: []
----

=== Flex Gateway Connected Mode

When you apply the policy to your API from the UI, the following parameters are displayed:

[%header%autowidth.spread,cols="a,a"]
|===
| *Parameter* | *Description*
|External authorization service URI  | External authorization service Uri. With gRPC type server, define the uri as `\h2://<ext.authz.com>:<port>`.
|External authorization server type  | Type of external server.
|Transport protocol API version  | Transport protocol API version.
|Include peer certificates in the authorization server request | Includes peer certificates in the authorization server request.
|Allowed headers | By default, requests sent to gRPC servers include all client headers, and requests sent to HTTP servers do not include any client headers. If you list allowed headers for either server type, requests include only the listed headers.
|===
