= Configuring Outbound TLS for Managed Omni Gateway
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:page-mode: conn

Outbound Transport Layer Security (TLS) encrypts communication between Omni Gateway and upstream services.

include::partial$task-tls-config.adoc[tag=share-contexts]

After you xref:anypoint-security::asm-secret-group-creation-task.adoc[create a secret group], you can add a TLS context or a mutual authentication TLS (mTLS) context and apply the TLS context to upstreams in API Manager to encrypt outbound traffic.


include::partial$task-tls-config.adoc[tags=defaultOutboundTLS]

include::partial$task-tls-config.adoc[tag=aia-support]

== Before You Begin
Before configuring the outbound TLS context for a Managed Omni Gateway, complete the following tasks:

* xref:anypoint-security::asm-secret-group-creation-task.adoc[Create a Secret Group]
+
When adding a secret group, refer to the <<tls-configuration-options, TLS Configuration Options>>. 
+
Depending on your desired configuration, either:
+
** xref:anypoint-security::asm-secret-group-creation-task.adoc#adding-a-keystore[Add a Keystore]
** xref:anypoint-security::asm-secret-group-creation-task.adoc#adding-a-truststore[Add a Trustore]
+
NOTE: Privacy Enhanced Mail (PEM) type is required for your Keystore or Truststore.

// TLS Configuration Options

[[tls-configuration-options]]
== Outbound TLS Configuration Options
You can configure your outbound TLS context to support regular TLS or mTLS.

Refer to the following cross reference table for the required TLS context configuration settings in the <<add-a-tls-context, Add a TLS Context>> step:

[%header%autowidth.spread,cols="a,a,a"]
|===
| Parameter | Outbound TLS | Outbound mTLS
| *Keystore* | Not Used | Required
| *Truststore* | Required, unless skip server cert validation is selected | Required to validate upstream certificate
| *Validate Client certificate* | Not Used | Not Used
| *Skip server certificate validation* | Either | Not Selected 
|===

A parameter that is "Not Used" for a configuration implies its status does not affect configuration.

To simplify your configurations, create different TLS contexts for the different traffic directions of your API instance. You can also use the same TLS context to support different traffic directions, but you can't support TLS and mTLS for the same direction by using the same context. Include the required parameters for both directions if you use the same TLS context for different directions.

// Add TLS Context in Secrets Manager
[[add-a-tls-context]]
== Add a TLS Context for Omni Gateway

Adding a TLS context to your secret group requires supplying a name, target, version, and keystore or truststore. You can also add context expiration date and ALPN Protocols and configure the outbound settings. 

[WARNING]
====
If you edit a secret group, including a TLS context, that is currently applied to an API instance, you must redeploy each API instance to apply the changes. To redeploy API instances, see <<redeploy-api-instance, Redeploy an API Instance>>.
====

To add a TLS context:

. Go to *Anypoint Platform > Secrets Manager*.
. To apply your TLS context to API instances, make your secret group downloadable.
+
To make your secret group downloadable:

.. Click the pencil icon next to the name of your secret group.
.. If *Secret Group Downloadable* is selected, click *Cancel*.
.. If *Secret Group Downloadable* is not selected, select it and click *Save*.
. In the *Secret Groups* list view, click the *Edit* button of the secret group to add a TLS context. 
. Select *TLS Context* in the menu on the left, and then click *Add TLS Context*. 
. In the Create TLS context screen, add the required information:
+
* *Name* +
Enter a name for your TLS context. 
* *Target* +
Select *Omni Gateway* to use the TLS context as the SSL validation for Omni Gateway APIs. 
* *Min TLS Version* and *Max TLS Version* +
Support a range of TLS versions or a single version by selecting the same version for the minimum and maximum.  
* *Keystore* +
If necessary for your configuration, select the PEM type keystore to store in the TLS context. The keystore contains the certificate presented by Omni Gateway to the remote party for outbound TLS.
+
[NOTE]
====
To comply with security standards, all certificates must be 2048 bits or longer.
====
* *Truststore* +
If necessary for your configuration, select a PEM type truststore to store certificates trusted by the client. The truststore contains the CA path that Omni uses to validate the remote party certificate for outbound TLS. 
+
[NOTE]
====
Upstream certificates must include the Subject Alternative Name (SAN) extension. The Common Name (CN) field is deprecated.

Omni Gateway supports the SAN extension of type `dNSName`.
====
* *Expiration Date* +
Optionally, enter an expiration date for the TLS context.
* *ALPN Protocols* +
By default, *H2 - HTTP/1.1* are the selected ALPN protocols. Change this value to support different protocols. 
* *Outbound Settings* +
If you don't want to support mTLS for outbound traffic, select *Skip server certificate validation*.

. If you want to customize cipher support for your TLS context, <<select-ciphers, Select Ciphers>>. 
+
Cipher selection is not available if only supporting TLS version 1.3.
. Click *Save*.

//redeploy

== Apply a TLS Context to an API

You can apply a TLS context to an upstream service when configuring the upstream configuration of a new API instance or by editing an existing instance's upstream configuration.

For information about either option, see the relevant tutorial:

* xref:api-manager::create-instance-task-flex.adoc[]
* xref:api-manager::edit-api-endpoint-task.adoc[]

To apply a TLS context to an upstream service:

. Go to *Anypoint Platform > API Manager*.
. Navigate to either the:
* Downstream configuration page, if adding a new API instance.
* *Settings* page, if editing an existing API instance.
. Configure the upstream service, if adding a new API instance.
. Click *Add TLS Context*.
.. Select a *Secret Group*.
.. Select a *TLS Context*.
.. Click *Ok*.
. Finish creating the API instance or save the configuration edits.



include::partial$task-flex-add-tls-context.adoc[tags=redeploy]
//Redeploy

//Ciphers
include::partial$flex-tls-cipher.adoc[tags=connectedSelect;cipherSupport;ciphers]

//Ciphers
== See Also

* xref:flex-local-tls-config.adoc[]
* xref:policies-included-tls.adoc[]