= Upgrade or Delete Managed Omni Gateway
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

You can upgrade or delete a Managed Omni Gateway using Anypoint Runtime Manager.

Managed Omni Gateways are regularly auto-upgraded, depending on your Gateway release channel (LTS or Edge). 
See xref:flex-gateway-version-lifecycle.adoc[] for more information.

You can upgrade a Managed Omni Gateway earlier than the regularly scheduled upgrade or patching process, between the new release date and the auto-upgrade date.
You can choose the time that better suits the needs of your organization.

== Early Upgrade Managed Omni Gateway (Optional)

. From Anypoint Platform, select *Runtime Manager*.
. Select *Omni Gateways* in the navigation menu.
. Select the *Managed Omni Gateway* tab.
. Click the name of the gateway to upgrade.
. Click *Settings* in the navigation menu.
. If a newer version is available, the *Version* field shows an *Update available* tag.
. Click the padlock symbol next to the version and *Update available* tag.
. Click the *Apply Changes* button. +
A status message (*Your gateway is being updated*) appears while the upgrade is being applied. A success message (*Your gateway has been successfully updated*) appears when the upgrade is complete.
. Click *Dashboard* in the navigation menu to view your gateway status.

== Delete Managed Omni Gateway

You can delete a Managed Omni Gateway using Anypoint Runtime Manager.

=== Before You Begin

If there are any APIs associated with the gateway you want to delete, you must either move the APIs to another gateway or delete the APIs. After any associated APIs are moved or deleted, follow these steps to delete a gateway and confirm the deletion.

=== Delete Gateway

. From Anypoint Platform, select *Runtime Manager*.
. Select *Omni Gateways* in the navigation menu.
. Select the *Managed Omni Gateway* tab.
. Click the name of the gateway to delete.
. Ensure the action menu button says *Delete Gateway*. If it says *Stop Gateway*, click the down arrow part of this button, and select *Delete Gateway* to change the action.
. Click the action menu button *Delete Gateway*.
. Verify that you delete the correct gateway in the confirmation dialog.
. Click *Yes, Delete*. +
A status message (*Your gateway is being deleted*) appears while the action is applied. A success message (*Your gateway has been successfully deleted*) appears when the action is complete.

[NOTE]
If you delete a gateway, you lose its configuration history.