= Applying Policies for Managed Omni Gateways and Connected Mode
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:page-aliases: policies-included-apply.adoc, api-manager::using-policies.adoc, policies::policies-included-apply.adoc

For Managed Omni Gateway and Omni Gateway running in Connected Mode, you apply inbound and outbound policies using *API Manager*. To find the policies provided by Omni Gateway, see xref:policies-included-directory.adoc[] and xref:policies-outbound-directory.adoc[].

[[apply-inbound-policy]]
== Apply Inbound Policies

. Go to *Anypoint Platform > API Manager*.
. From *API Instances* or *Agent and Tool Instances*, click the name of the instance to which you want to apply a policy.
. From the side navigation panel, click *Policies*.
. Click *+ Add policy*.
. Select the policy to apply.
. Configure the required parameters.
+
For policy configuration parameters, see xref:policies-included-directory.adoc[].
. Click *Advanced options* to configure these optional parameters:
** Policy label: A label to identify the policy, specifically for use cases with multiples of the same policy.
** Policy definition version: The version of the policy definition to use.
** Application conditions: Apply the policy to all incoming requests or requests that match specified conditions:
*** Methods: The HTTP methods to apply the policy to.
*** URI template regex: A URI template regex of which request paths to apply the policy to.
*** Host: The host to apply the policy to.
*** Headers: A map of headers names and regex values to apply the policy to.
+ 
NOTE: If necessary, use multiples of the same policy to meet all required conditions.
. Click *Apply*.

You can apply a policy to the entire instance by default, or to specific methods and resources within the API.

[[apply-outbound-policy]]
== Apply Outbound Policies

. Go to *Anypoint Platform > API Manager*.
. From *API Instances* or *Agent and Tool Instances*, click the name of the instance to which you want to apply a policy.
. From the side navigation panel, click *Policies*.
. Click the *Outbound policies* tab.
. Click *+ Add outbound policy*.
. Select the *Upstream* to which you want to apply a policy.
. If you want to apply the policy to an additional upstream, click *Add upstream* and select the additional upstream. Repeat this step for all upstreams to which you want to apply the policy.
. Click *Next*.
. Select the policy to apply.
. Configure the required parameters.
+
For policy configuration parameters, see xref:policies-outbound-directory.adoc[].
. Click *Advanced options* to configure these optional parameters:
** Policy label: A label to identify the policy, specifically for use cases with multiples of the same policy.
** Policy definition version: The version of the policy definition to use.
** Application conditions: Apply the policy to all incoming requests or requests that match specified conditions:
*** Methods: The HTTP methods to apply the policy to.
*** Headers: A map of headers names and regex values to apply the policy to.
+ 
NOTE: If necessary, use multiples of the same policy to meet all required conditions.
. Click *Apply*.

You can apply a policy to the entire upstream by default, or to specific methods and resources of the upstream.

== See Also

* xref:index.adoc[]
* xref:flex-gateway-getting-started.adoc[]
