= Viewing the Replica Status in Runtime Manager
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: runtime-manager::flex-gateway-replica-status.adoc
:imagesdir: ../assets/images

In Runtime Manager, you can view the status of groups of Omni Replicas and individual Omni Replicas.

== Groups of Omni Replicas

To view information about the status of groups of Omni Replicas:

. From Anypoint Platform, select *Runtime Manager*.
. Select *Omni Gateways* in the navigation menu. +
By default, all Omni Gateways regardless of their status are shown. To filter by status, click the *Any Status* arrow and the status you want to filter.

The *Name* column lists the name and the number of connected replicas.

The *Status* column shows the connection status for the replicas associated with a particular gateway.

The following table describes the meaning of each status for a group of replicas:

[%header,cols="30a,70a"]
|===
|Status | Group of Replicas
|Running | At least one replica is connected to the platform and can serve traffic.
|Not Running | There are no replicas connected to the platform and no information on whether they are serving traffic.
|===

== Individual Omni Replicas

To view information about the status of individual replicas:

. From Anypoint Platform, select *Runtime Manager*.
. Select *Omni Gateways* in the navigation menu.
. Select the name of the Omni Gateway whose individual replica statuses you want to view.

The *Status* column in the list of replicas shows the connection status for that particular replica.

The following table describes the meaning of each status for a single replica:

[%header,cols="30a,70a"]
|===
|Status |Single Replica
|Running | The replica is connected to the platform and can serve traffic.
|Not Running |The replica is not connected to the platform. There is no information on whether it is serving traffic. Disconnected replicas are deleted after seven days.
|===

== See Also

* xref:flex-conn-view-api-status.adoc[View the API Status in Runtime Manager]