= Securing Omni Gateway Instances with Policies
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:page-aliases: flex-gateway-secure-apis.adoc

Policies enforce rules when Omni Gateway processes requests, enabling you to secure and govern your Omni Gateway API, agent, and tool instances.

MuleSoft provides policies that you can apply to your instances via Anypoint Platform or declarative configuration files. The provided policies include rate limiting, caching, authentication, authorization, threat protection, monitoring, logging. For more information about MuleSoft-provided policies, see the xref:policies-included-directory.adoc[] and xref:policies-outbound-directory.adoc[].

To extend existing functionality or define new functionality, create custom policies based on your specific business requirements. For information about creating custom policies, see xref:pdk::policies-pdk-overview.adoc[].

Automated policies enable your instances to comply with common security and logging requirements by automatically applying the same set of policies to all instances running in Omni Gateway. See xref:policies-automated-overview.adoc[] for more information.

To apply a policy for Managed Omni Gateway or Connected Mode, see xref:gateway-secure-conn.adoc[].

To apply a policy in Local Mode, see xref:gateway-secure-local.adoc[].

For information about policy reordering, see xref:policies-reorder.adoc[].

For information about DataWeave support, see xref:policies-dataweave-support.adoc[].

== See Also

* xref:index.adoc[]
* xref:gateway-getting-started-overview.adoc[]
