= MCP Schema Validation Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:keywords: api gateway, flex gateway, gateway, policy

[width="100%", cols="5,15"]
|===
>s| Policy Name | MCP Schema Validation
>s|Summary      | Validates MCP requests to ensure they conform to the MCP specification
>s|Category | MCP
>s|First Omni Gateway version available | v1.9.3
>s| Returned Status Codes |
|===

include::partial$mcp-version-support.adoc[]

== Summary

The MCP Schema Validation policy validates that every incoming request complies with JsonRPC MCP protocol.

When *Validate Tool Schema* is enabled, the policy also:

* Validates tool invocation request parameters against the JSON schema of the tool.
* Returns the tools/list MCP request without having to send the request to the upstream MCP Server.

When the policy can't validate the request, it returns an https://modelcontextprotocol.io/specification/2025-11-25/basic#error-responses[MCP Error Response].

include::partial$policy-title-headers.adoc[tag=configFileTitleOnly]

The MCP Schema Validation policy isn't supported in Local Mode.

include::partial$policy-title-headers.adoc[tag=ui]

[%header%autowidth.spread,cols="a,a"]
|===
| Parameter| Description
| Validate Tool Schema | When enabled, the policy:

* Validates tool invocation request parameters against the JSON schema of the tool.
* Returns the tools/list MCP request without having to send the request to the upstream MCP Server.
|===