= Credential Injection Basic Authentication Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:keywords: basic authentication, api gateway, flex gateway, gateway, policy

[width="100%", cols="5,15"]
|===
>s| Policy Name | Credential Injection Basic Authentication
>s|Summary      | Injects a basic authorization header into outgoing requests
>s|Category | Security
>s|First Omni Gateway version available | v1.9.0
>s| Returned Status Codes | No return codes exist for this policy. Error codes are returned from the upstream service.
|===

== Summary

The Credential Injection Basic Authentication policy injects an `Authorization` header containing a username and password into outbound requests. The policy ensures that requests sent from Omni Gateway to an upstream service include the correct authentication headers. The Authorization header format is `Authorization: Basic <username:password>`.

The policy follows https://tools.ietf.org/html/rfc7617[Basic HTTP authentication standards].

When an error occurs, the policy returns a `WWW-Authenticate` HTTP header field.

== Configuring Policy Parameters

include::partial$policy-title-headers.adoc[tag=configFile]

----
- policyRef:
    name: credential-injection-basic-auth-flex
  config:
    username: <string> // OPTIONAL
    password: <string> // OPTIONAL
    overwrite: <boolean> // OPTIONAL
    customHeader: <string> // OPTIONAL
----

[%header%autowidth.spread,cols="a,a,a,a"]
|===
|Parameter | Required or Optional | Default Value | Description

| `username`
| Optional
| N/A
| The username for the basic authentication credentials.

| `password`
| Optional
| N/A
| The password for the basic authentication credentials.

| `overwrite`
| Optional
| true
| When enabled, if the `Authorization` header is present, the policy overwrites it with the configured credentials.

| `customHeader`
| Optional
| N/A
| When configured, a custom header is injected instead of the `Authorization` header. If *Overwrite header* is enabled, the policy overwrites the custom header if present instead of the `Authorization` header.

|===

==== Resource Configuration Example

----
- policyRef:
    name: http-basic-authentication-flex
  config:
    username: chris
    password: admin
----

include::partial$policy-title-headers.adoc[tag=ui]

[%header%autowidth.spread]
|===
|Parameter |Description | Required?
|Username |The username for the basic authentication credentials. |Optional
|Password |The password for the basic authentication credentials. |Optional
|Overwrite header |When enabled, if the `Authorization` header is present, the policy overwrites it with the configured credentials.|Optional
|Custom Header |When configured, a custom header is injected instead of the `Authorization` header. If *Overwrite header* is enabled, the policy overwrites the custom header if present instead of the `Authorization` header.|Optional
|===

