= Circuit Breaker Policy

[%autowidth.spread,cols="a,a"]
|===
>s| Policy name | Circuit Breaker
>s| Summary | Prevents an upstream from receiving too many requests or connections
>s| Category | Quality of Service
>s| First Omni Gateway version available | v1.9.0
>s|Release Notes| xref:release-notes::flex-gateway/policies/outbound-circuit-breaker-release-notes.adoc[]
.4+>.^s| Returned Status Codes
|503 - Service Unavailable
|===

== Summary

The Circuit Breaker policy prevents upstream services from receiving too many requests or connections at a time. If the defined maximums are reached, Omni Gateway returns a `503 - Service Unavailable` error.

For Managed Omni Gateways or Connected Mode, each API instance has its own independent limit when requesting the same upstream, allowing each to use the full maximum. In Local Mode, the limits are shared among different API instances, so they must all adhere to the same upstream maximum. For all modes, maximums are not distributed across replicas; each Gateway can use the full maximum.

The Circuit Breaker policy is an extension of the Envoy upstream clusters circuit breaking feature. To learn more about the Envoy's circuit breaking, see https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/circuit_breaking.html[Circuit Breaking] in the Envoy documentation.

== Configuring Policy Parameters

include::partial$policy-title-headers.adoc[tag=configFile]

----
apiVersion: gateway.mulesoft.com/v1alpha1  
kind: PolicyBinding  
metadata:  
  name: upstream-policy  
spec:  
  targetRef:  
    Kind: Service  
    name: upstream  
  policyRef:  
    name: circuit-breaker-flex  
  config:  
    thresholds:  
      maxConnections: <number> // OPTIONAL 
      maxPendingRequests: <number> // OPTIONAL  
      maxRequests: <number> // OPTIONAL
      maxRetries: <number> // OPTIONAL  
      maxConnectionPools: <number> // OPTIONAL
----

NOTE: For Local Mode, the limits are not independent, so different API instances share the maximums for an upstream.

[%header%autowidth.spread,cols="a,a,a"]
|===
|Parameter | Required or Optional | Description


| `maximumConnections`
| Optional
| Maximum number of connections per API to an upstream.

| `maximumPendingRequests`
| Optional
| Maximum number of queued requests while waiting for a connection.

| `maximumRequests`
| Optional
| Maximum number of outstanding requests to an upstream.

| `maximumRetries`
| Optional
| Maximum number of outstanding retries.

| `maximumConnectionPools`
| Optional
| Maximum number of connection pools concurrently initiated to an upstream.

|===

==== Resource Configuration Example

This example defines a policy that supports a maximum of one request at a time:

----
apiVersion: gateway.mulesoft.com/v1beta1  
kind: Configuration  
metadata:  
  name: circuit-breaker  
  namespace: test-ns  
spec:  
  circuitBreaker:  
    thresholds:  
      maxConnections: 1  
      maxPendingRequests: 1  
      maxRequests: 1  
      maxRetries: 1  
      maxConnectionPools: 1  
----


include::partial$policy-title-headers.adoc[tag=ui]


[%header%autowidth.spread,cols="a,a,a"]
|===
|Parameter | Required or Optional | Description

| Maximum connections
| Optional
| Maximum number of connections per API to an upstream.

| Maximum pending requests
| Optional
| Maximum number of queued requests while waiting for a connection.

| Maximum requests
| Optional
| Maximum number of outstanding requests to an upstream.

| Maximum retries
| Optional
| Maximum number of outstanding retries.

| Maximum connection pools
| Optional
| Maximum number of connection pools concurrently initiated to an upstream.

|===

NOTE: For Managed Omni Gateways or Connected Mode, each API instance has its own independent limit when requesting the same upstream, allowing each to use the full maximum.
