= Health Check Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:keywords: health check, api gateway, flex gateway, gateway, policy
:page-aliases: policies::policies-included-health-check.adoc

[width="100%", cols="5,15"]
|===
>s|Policy name | Health Check
>s|Summary | Monitors API upstream health at specific intervals
>s|Category | Quality of Service
>s| First Omni Gateway version available | v1.4.0
>s|Release Notes| xref:release-notes::gateway/policies/health-check-release-notes.adoc[]
.1+>.^s| Returned Status Codes | No return codes exist for this policy.
|===

== Summary

The Health Check policy enables you to monitor an API instance's connection to an upstream service and sends you an email alert if the connection status changes. The Health Check policy monitors the health of the upstream service and not the health of the API instance or Omni Gateway.

The Health Check policy monitors your API by making GET requests to the specified upstream's base path. You must specify a base path with a GET request. Requests are made at a fixed schedule every minute with the first request. The first request occurs a minute after the policy is applied. Requests made by the Health Check policy do not count as Omni Gateway API calls for pricing purposes.

When you configure Health Check, specify a response code for the GET request that indicates a healthy connection. For example, the status code of an active API should return 200, indicating the API can receive connections. The platform sends an email alert when the status code is not 200. Health Check only validates the response code, so what is returned to the endpoint is unimportant.

No logging event appears for healthy responses. Omni Gateway logs only unhealthy responses.

You can use any 1xx, 2xx, 3xx, 4xx, or 5xx response codes. However, if you expect successful connections to your endpoints, 2xx response codes are ideal. Only a number response code is accepted.

You are required to create an alert for the Health Check policy. Applying the policy navigates you to the Create Alert page, where you must create an alert. For information about how to configure your alert, visit xref:use-api-alerts.adoc[Using Omni Gateway API Alerts].

IMPORTANT: Applying the Health Check policy to API Instances with an outbound TLS context also applied causes the Health Check policy to return an unhealthy connection.

== Configuring Policy Parameters

include::partial$policy-title-headers.adoc[tag=configFileTitleOnly]

The Health Check policy isn't supported in Local Mode.

include::partial$policy-title-headers.adoc[tag=ui]

[%header%autowidth.spread,cols="a,a,a"]
|===
| Element | Description | Required?
|Upstream URL  | The full URL of the API upstream you are monitoring | Yes
|Base path  | The HTTP path of the GET method that is requested during health checks | Yes
|Response code  | The expected status code of the GET request specified in the base path. Only a number response code is accepted. | Yes
|===
