= Registering and Running Flex Gateway in Connected Mode
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

When using Anypoint Flex Gateway in Connected Mode, you can view your gateways
in Runtime Manager and your API instances and policy configurations in API Manager.

Connected Mode enables you to manage all of your non-Mule APIs from a single unified
control plane, and grants you all the other benefits of Anypoint Platform, such as
monitoring through API Analytics and reusability through Exchange.

Before you can use your Flex Gateway to manage API instances, you must register and start it.

There are three ways to register Flex Gateway in Connected Mode including the following:

* xref:flex-conn-reg-run-up.adoc[Register and Run using a Username and Password]: If you have
a username and password for Anypoint Platform, you can use these credentials to register
your Flex Gateway.
* xref:flex-conn-reg-run-app.adoc[Register and Run using a Connected App]: If you do not have
a username or password for Anypoint Platform, you can use connected app credentials to register
your Flex Gateway.
* xref:flex-conn-reg-run-token.adoc[Register and Run using a Token]: If you do not have a username
or password for Anypoint Platform, you can use a registration token generated by the Runtime Manager UI.