= Creating an LLM Proxy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images


LLM Proxy provides a unified access layer for multiple Large Language Model (LLM) providers. LLM Proxy are deployed to Flex Gateway to enable governance, intelligent routing, and cost management for AI applications.

By creating a proxy, the user defines a singular LLM service that can receive requests for multiple providers, such as Open AI or Gemini. This simplifies the developer experience. You can add new models to the service seamlessly without changing the endpoint.

Depending on configuration, the proxy then sends the request to the model defined by the user or dynamically sends the request to the provider that best matches the request. 

== Before You Begin

== Define a Semantic Service

== Create an LLM Proxy


== Model-Based Routing

Model-based routing is static routing. In the request, the user specificies what model the LLM Proxy should send the request to. To ensure users 

By specifying a target model, LLM Proxy can override the model version provided by the user.


----
curl --location --request POST 'https://llm-proxy-gateway-iiexmc.vmizg1.usa-e1.qax.cloudhub.io/chat/completions' \
--header 'Content-Type: application/json' \
--header 'client_id: 30813d6014e84838b1b01b5144400021' \
--header 'client_secret: C1F2dCE8aA234581B121d736d7E1c41e' \
--data-raw '{
    "model": "openai/gpt-5-nano",
    "input": "What is Artificial Intelligence"
}'
----

[[configure-model-based-routing]]
=== Configure Model-Based Routing

. Configure multiple routes. Click Add LLM Route to create new routes.
. Select Model-based for Routing strategy.
. Choose to enable a Fallback route. If enabling a fallback route:
.. Select a Route to fallback to.
.. Select a target model for the fallback route to use.
. If no fall back route is configured and a route fails, a error response is returned.

== Semantic Routing

Semantic routing is dynamic routing where the LLM Proxy chooses which model to send the request to. For Sematic Routing, the user creates prompt topics for each route. When a request is sent to the LLM Proxy, a semantic service compares the request to the define topic utterances and sends the request to the route that best matches it.


=== Configure Semantic-Based Routing
. Configure multiple routes. Click Add LLM Route to create new routes.
. Select Model-based for Routing strategy.
. Select a Target Model for each route.
. Define a prompt topics for the routes:
.. Click the Select prompt topics.
.. Click + Create prompt topic.
.. Define a Prompt topic name.
.. Define a Prompt utterances or click Upload utterances to upload a `.txt` containing your prompt utterances.
.. Click Create.
.. Create multiple prompt topics for each route.
. Configure a Fallback route:
.. Specify an accuracy threshold. When the accuracy of the semantic match is less than this threshold, traffic is sent to the fallback route.
.. Select a Route to fallback to.
.. Select a target model for the fallback route to use.
. Create a Semantic prompt guard to block users from asking the server about specific topics:
.. Click + Create deny list.
.. Define a Prompt topic name.
.. Define a Prompt utterances or click Upload utterances to upload a `.txt` containing your prompt utterances.
.. Click Create.
.. Create multiple deny list topics to better protect your LLM Proxy.
