= LLM Proxy Requests
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

LLM Proxy supports both Open AI Responses and Chat Completions requests. To learn more about the these API types, see:

* https://developers.openai.com/api/reference/resources/responses[Responses]
* https://developers.openai.com/api/reference/resources/chat[Chat]

When sending a request to an LLM Proxy with either routing strategy, you can specify a model in the request. You don't have to modify the request for different routing strategies. Each routing strategy handles the model selection differently:

* *Model-Based Routing*: The user specifies a model in the request. If no model is specified, the LLM Proxy sends the request to the fallback route.
* *Semantic Routing*: No model is specified in the request. The LLM Proxy chooses which model to use based on the request content by matching it to prompt topics you define for each route. If a model is specified in the request, like in <<model-based-routing-example-request>>, it is ignored.

[[model-based-routing-example-request]]
== Model-Based Routing Example Request

This is an example request to the LLM Proxy using model-based routing. The request is sent to the Open AI GPT-5 nano model:

[tabs]
====
Responses::
+
[source,cli]
----
curl --location --request POST 'https://llm-proxy-gateway-iiexmc.vmizg1.usa-e1.qax.cloudhub.io/chat/completions' \
--header 'Content-Type: application/json' \
--header 'client_id: 30813d6014e84838b1b01b5144400021' \
--header 'client_secret: C1F2dCE8aA234581B121d736d7E1c41e' \
--data-raw '{
    "model": "openai/gpt-5-nano",
    "input": "What is Artificial Intelligence"
}'
----

Chat Completions::
+
[source,cli]
----

----
====

To find the configurable parameters in this request, see <<retrieve-the-request-configuration-parameters>>.

[[semantic-routing-example-request]]
== Semantic Routing Example Request

This is an example request to the LLM Proxy using semantic routing. No model is specified in the request. If a model is specified, it is ignored.

[tabs]
====
Responses::
+
[source,cli]
----
curl --location '<public-endpoint>/<base-path>' \
--header 'Content-Type: application/json' \
--header 'client_id: <client-id>' \
--header 'client_secret: <client-secret>' \
--data '{
    "input": "Calculate simple interest"
}'
----

Chat Completions::
+
[source,cli]
----
curl --location '<public-endpoint>/<base-path>' \
--header 'Content-Type: application/json' \
--header 'client_id: <client-id>' \
--header 'client_secret: <client-secret>' \
--data '{
  "messages": [
    {
      "role": "user",
      "content": "Provide a step-by-step guide for authenticating an API request."
    }
  ]
}'
----
====

To find the configurable parameters in this request, see <<retrieve-the-request-configuration-parameters>>.

[[retrieve-the-request-configuration-parameters]]
== Retrieve the Request Configuration Parameters

To find your LLM Proxy endpoint and client application credentials:

. Find your public endpoint:
.. Navigate to *Runtime Manager* > *Flex Gateways* 
.. Click the name of the Flex Gateway where your LLM Proxy is deployed.
.. Copy the *Public Endpoint*.
. Find your base path:
.. From *API Manager* > *LLM Proxies*, click the name of the LLM Proxy whose base path you want to find.
.. Click *Configuration*.
.. Copy the *Base path*.
. Retrieve your client ID and client secret:
.. From the *LLM Summary* page of your LLM Proxy, click *Actions* > *View LLM proxy in Exchange*.
.. Click *Request access*.
.. Select the *API Instance* you want to request access to.
.. Select the *Application* you want to request access to.
.. Select the *SLA tier*.
.. Click *Request access*.
.. Copy the *Client ID* and *Client Secret*.




