= LLM Proxy Requests
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

NOTE: If a model is specified in the request, like in <<model-based-routing-example-request>>, it is ignored. You don't have to modify the request for different routing strategies.

[[model-based-routing-example-request]]
== Model-Based Routing Example Request

This is an example request to the LLM Proxy using model-based routing. The request is sent to the Open AI GPT-5 nano model:

----
curl --location --request POST 'https://llm-proxy-gateway-iiexmc.vmizg1.usa-e1.qax.cloudhub.io/chat/completions' \
--header 'Content-Type: application/json' \
--header 'client_id: 30813d6014e84838b1b01b5144400021' \
--header 'client_secret: C1F2dCE8aA234581B121d736d7E1c41e' \
--data-raw '{
    "model": "openai/gpt-5-nano",
    "input": "What is Artificial Intelligence"
}'
----

To find the configurable parameters in this request, see <<find-the-necessary-information-to-make-a-requests>>.


[[semantic-routing-example-request]]
== Semantic Routing Example Request

This is an example request to the LLM Proxy using semantic routing. No model is specified in the request. If a model is specified, it is ignored.

----
curl --location '<public-endpoint>/<base-path>' \
--header 'Content-Type: application/json' \
--header 'client_id: <client-id>' \
--header 'client_secret: <client-secret>' \
--data '{
  "messages": [
    {
      "role": "user",
      "content": "Provide a step-by-step guide for authenticating an API request."
    }
  ]
}'
----

To find the configurable parameters in this request, see <<find-the-necessary-information-to-make-a-requests>>.

[[find-the-necessary-information-to-make-a-requests]]
== Find the Necessary Information to Make a Requests

To find the necessary information to use the example requests:

. Find your public endpoint:
.. Navigate to *Runtime Manager* > *Flex Gateways* 
.. Click the name of the Flex Gateway where your LLM Proxy is deployed.
.. Copy the *Public Endpoint*.
. Find your base path:
.. From *API Manager* > *LLM Proxies*, click the name of the LLM Proxy whose base path you want to find.
.. Click *Configuration*.
.. Copy the *Base path*.
. Retrieve your client ID and client secret:
.. From the *LLM Summary* page of your LLM Proxy, click *Actions* > *View LLM proxy in Exchange*.
.. Click *Request access*.
.. Select the *API Instance* you want to request access to.
.. Select the *Application* you want to request access to.
.. Select the *SLA tier*.
.. Click *Request access*.
.. Copy the *Client ID* and *Client Secret*.