[[severity-levels]]
== Message Logging Severity Levels

When you configure a Message Logging policy for your API instance, you can assign a severity level. Each severity level includes a specific set of information in the log report.

Log reports include the severity level you select and the following levels on the hierarchy.
For example, if you select DEBUG, the log reports include the DEBUG severity level as well as the INFO, WARN, and ERROR severity levels. However, if you select ERROR, the log reports include only error messages. The following table describes the type of information included in the logs for each severity level:

[%header,cols='1a,5a'] 
|===
|Log Severity Level
|Description

|DEBUG
|Tracing information used by application developers.

|INFO
|Informational messages that highlight the progress of the application.

|WARN
|Potentially harmful situations that indicate potential problems.

|ERROR
|Events that prevent normal program execution but might allow the application to continue running.
|===