//tag::intro1[]

Flex Gateway includes the following CLI command to test gateway health. You can run this command manually on any Flex Gateway:

[source,ssh]
----
flexctl probe --check=liveness
----

This command returns either an exit code of `0` for a healthy Flex Gateway or `1` for an unhealthy Flex Gateway.

//end::intro1[]

//tag::intro2[]
You can also configure this command to run automatically. By default, Flex Gateways deployed on Kubernetes have a liveness probe configured. The liveness probe periodically runs the liveness check command and automatically restarts the Flex Gateway pod after a specified number of failed liveness checks. 

Flex Gateways deployed on Docker or Linux, Flex Gateway does not offer a default liveness probe. However, you can still use the the liveness check command. For both deployments, you can use liveness check in scripts that check liveness and restart containers. 

An example of how you can use this command with Docker is by configuring `HEALTHCHECK` in your `docker run` command. For more information about `HEALTHCHECK`, see https://docs.docker.com/engine/reference/run/#healthcheck[Docker run HEALTHCHECK].

//tag::intro2[]

//tag::k8s-liveness-probe[]
== Configure a Kubernetes Liveness Probe
By default, Flex Gateways running on Kubernetes have a liveness probe configured in the Helm chart. The liveness probe automatically runs the liveness check command at a specified interval and restarts unhealthy pods after a specified number of unhealthy tests. 

The liveness probe is configured by default with the following values:

[source,helm]
----
livenessProbe:
 exec:
   command:
   - flexctl
   - probe
   - --check=liveness
 initialDelaySeconds: 10
 periodSeconds: 10
 failureThreshold: 5
 timeoutSeconds: 1
----

[cols="1,2"]
|===
| Parameter | Description

| `exec.command` | The liveness check command
| `initialDelaySeconds` | The time in seconds to wait after startup before executing the first liveness test
| `periodSeconds` | The period in seconds between each liveness check
| `failureThreshold` | The number of failed liveness tests before the Kubernetes pod is restarted
| `timeoutSeconds` | The time in seconds before the test times out
|===

To modify the default liveness probe parameters, you must update your Helm chart. For more information about how to modify a Helm chart, see xref:flex-gateway-k8-change-helm-settings.adoc[]

//end::k8s-liveness-probe[]


//tag::see-also[]
== See Also

* https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/[Configure Liveness, Readiness and Startup Probes^].
* xref:policies-included-health-check.adoc[]

//end::see-also[]