// partial for registering in connected/local modes with a username and password, connected app, or a token, in a Docker container or as a Linux service

// tag::prerequisites-heading[]

== Before You Begin

Before registering Flex Gateway, you must complete the following tasks:
// end::prerequisites-heading[]
// tag::app-prerequisites[] 

* xref:access-management::connected-apps-developers.adoc#create-a-connected-app[Configure a Connected App]
** Include the following scopes:
*** Read Servers
*** Manage Servers
*** View Organization
** Save the *Id* and *Secret* of the Connected app you configure.

// end::app-prerequisites[]
// tag::prerequisites[]

* xref:flex-install.adoc[Install a Flex Gateway]
* Request _Manage Servers_ and _Read Servers_ permissions in Runtime Manager from your Anypoint Platform admin
* Collect the following information from your Anypoint Platform instance: 
** The *Organization ID* for the organization where you want to run Flex Gateway
+
See xref:access-management::organization.adoc#find-your-organization-id[Find your Organization ID] for more information on how to find your Organization ID.

// end::prerequisites[]
// tag::environment-prerequisites[]

** The *Environment ID* for the environment where you want to run Flex Gateway
+
See xref:api-manager::latest-overview-concept.adoc#what-api-manager-looks-like[What API Manager Looks Like]
for more information on how to find your Environment ID.

// end::environment-prerequisites[]
// tag::token-prerequisites[]

** The registration *token* for the environment in Anypoint Platform where you want to run Flex Gateway
+
Navigate to Runtime Manager, select *Flex Gateway* in the left navigation, and click *Add Gateway*
to generate set of instructions that includes a command block with the registration token.

// end::token-prerequisites[]
// tag::user-prerequisites[]

** The *Username* and *Password* of a user with _Read Servers_ and _Manage Servers_ permissions for Runtime Manager

// end::user-prerequisites[]
// tag::app-docker-heading[]
== Register and Run with a Connected App in a Docker Container
// end::app-docker-heading[]
// tag::user-docker-heading[]
== Register and Run with a Username and Password in a Docker Container
// end::user-docker-heading[]
// tag::token-docker-heading[]
== Register and Run with a Token in a Docker Container
// end::token-docker-heading[]
// tag::app-linux-heading[]
== Register and Run with a Connected App as a Linux Service
// end::app-linux-heading[]
// tag::user-linux-heading[]
== Register and Run with a Username and Password as a Linux Service
// end::user-linux-heading[]
// tag::token-linux-heading[]
== Register and Run with a Token as a Linux Service
// end::token-linux-heading[]
// tag::app-k8s-heading[]
== Register and Run with a Connected App on a Kubernetes Cluster
// end::app-k8s-heading[]
// tag::user-k8s-heading[]
== Register and Run with a Username and Password on a Kubernetes Cluster
// end::user-k8s-heading[]
// tag::token-k8s-heading[]
== Register and Run with a Token on a Kubernetes Cluster
// end::token-k8s-heading[]
// tag::reg-command-intro[]
To register a Flex Gateway with Anypoint Platform, you must enter the registration command and then the start command. Each command includes information specific to your Anypoint Platform instance and *must be updated before* executing. See <<Before You Begin>> for more information on how to find the information you will need.
//end::reg-command-intro[]
//
// tag::k8s-connected-intro[]

In Connected Mode, Flex Gateway typically serves as an ingress or a standalone gateway that is managed mostly through Anypoint Platform, where you can: 

* Deploy APIs to your cluster.
* Apply policies and other configurations.
* Create resources (_with the exception_ of Configuration and Service resources). 

In Connected Mode, resource creation through `kubectl apply` is possible but restricted to the following resource types:
Configuration, Service, Extension, and PolicyBinding of types `tls`, `tls-inbound`, and `tls-outbound`. For more info about resources, see xref:flex-local-configuration-reference-guide.adoc[].

// end::k8s-connected-intro[]
//
// tag::k8s-local-intro[]

In Local Mode, Flex Gateway typically acts as an ingress controller that manages external access to your Kubernetes cluster. Flex Gateway can also act as a standalone gateway for internal traffic. 

When using this mode, you must know what resources to create and apply, and use `kubectl apply` to deploy Kubernetes targets and resources such as APIs, policies, or Flex Gateway-related resources to your gateway. 

Local Mode also supports the Ingress resources from Kubernetes, which are configured through a YAML file with properties, such as `apiVersion`, `kind`, `metadata`, `spec` for configuring a load balancer or proxy server, and `rules` for directing HTTP and HTTPS traffic (see https://kubernetes.io/docs/concepts/services-networking/ingress/[Kubernetes documentation^] on Ingress resources).

// end::k8s-local-intro[]

// tag::k8s-reg-command-intro[]
To register a Flex Gateway instance with Anypoint Platform, run the  registration command with required options. After registering, install the Helm chart for the registered gateway. The installation step requires an existing cluster. See <<Before You Begin>> for more prerequisites to these procedures.
// end::k8s-reg-command-intro[] 

// tag::k8s-mode-overview[]
For information about this mode, see xref:k8-overview.adoc[].
// tag::k8s-mode-overview[]

//tag::sub-coll-info[]

=== Substitute Collected Information

Before executing the registration command, replace the following sample information with the information you collected:

//end::sub-coll-info[] 
// tag::user-replace-content[]

* `--username` = the username for an Anypoint Platform user with _Read Servers_ and _Manage Servers_ permissions for Runtime Manager
* `--password` = the password for an Anypoint Platform user with _Read Servers_ and _Manage Servers_ permissions for Runtime Manager
// end::user-replace-content[]
// tag::token-replace-content[]
* `--token` = the registration token for your environment in Anypoint Platform
// end::token-replace-content[]
// tag::app-replace-content[]

* `--client-id` = the Id for the Connected App you configured in Access Management
* `--client-secret` = the Secret for the Connected App you configured in Access Management

// end::app-replace-content[]
// tag::environment-replace-content[]

* `--environment` = the Environment Id for the environment in Anypoint Platform where you want the Flex Gateway to run

// end::environment-replace-content[]
// tag::replace-content[]

* `--organization` = your Organization ID in Anypoint Platform

* `--split` (optional) = the flag that determines whether registration information should split into multiple files. The default value is `false`.
+
If `split` is set to `true`, registration information is split into two files: `registration.yaml` and `certificate.yaml`. If `false`, all registration information is contained in one file: `registration.yaml`.
* `--output-directory` (optional) = the directory in which registration information is output

* `my-gateway` = the name you want to assign the gateway cluster

// end::replace-content[]
// tag::reg-command-heading[]

=== Registration Command

After replacing the sample content, register your Flex Gateway by executing the following command: 

// end::reg-command-heading[]
// tag::reg-command-1[]

[source,ssh,subs=attributes+]
----
# end::reg-command-1[]
# tag::docker-reg-command[]
docker run --entrypoint flexctl \
-v "$(pwd)":/registration -u $UID mulesoft/flex-gateway \
register \
# end::docker-reg-command[]
# tag::linux-reg-command[]
flexctl register \
# end::linux-reg-command[]
# tag::user-reg-command[]
--username=<your-username> \
--password=<your-password> \
# end::user-reg-command[]
# tag::app-reg-command[]
--client-id=<your-connected-app-client-id> \
--client-secret=<your-connected-app-client-secret> \
# end::app-reg-command[]
# tag::environment-reg-command[]
--environment=<your-environment-id> \
# end::environment-reg-command[]
# tag::token-reg-command[]
--token=<your-registration-token> \
# end::token-reg-command[]
# tag::connected-reg-command[]
--connected=true \
# end::connected-reg-command[]
# tag::organization-reg-command[]
--organization=<your-org-id> \
# end::organization-reg-command[]
# tag::output-reg-command-linux[]
--output-directory=/usr/local/share/mulesoft/flex-gateway/conf.d \
# end::output-reg-command-linux[]
# tag::output-reg-command-docker[]
--output-directory=/registration \
# end::output-reg-command-docker[]
# tag::reg-command-2[]
my-gateway
----

NOTE: Use `sudo` if you encounter file permission issues when running this command.

NOTE: If you are in Europe you will need to add the `--anypoint-url=https://eu1.anypoint.mulesoft.com` flag
to your command.

// end::reg-command-2[]
// tag::after-reg[]
In the output directory, you should see the following new registration file(s):

* `registration.yaml`
* `certificate.yaml` (generated only if the `split` registration parameter is set to `true`, otherwise certificate information will be contained in `registration.yaml`)

IMPORTANT: These generated files are credentials for you to connect your Flex Gateway. If you lose them you
can no longer connect your Flex Gateway.
// end::after-reg[]
//tag::after-reg-2[]

//end::after-reg-2[]
//tag::linux-after-reg[]

//end::linux-after-reg[]
//tag::k8s-after-reg[]

//end::k8s-after-reg[]
// tag::connected-after-reg[]

You should also see your new Flex Gateway in Runtime Manager after clicking *Flex Gateway* in the left navigation. 
The gateway's status is disconnected for now. You need to start the gateway to connect it.
// end::connected-after-reg[]
// tag::start-command[]

=== Start Command

Before executing the start command below, update the absolute path to the directory where your Flex Gateway registration files reside.

[source,ssh,subs=attributes+]
----
docker run --rm \
-p 8080:8080 \
-v <absolute-path-to-directory-with-gateway-registration-files>/:/usr/local/share/mulesoft/flex-gateway/conf.d \
mulesoft/flex-gateway
----
NOTE: Specify an optional name you want to assign to your Flex Replica by including the following: `-e FLEX_NAME=<name-for-flex-replica> \`.
// end::start-command[]
// tag::start-command-local-intro[]

=== Start Command

Before executing the start command below, update the absolute path to the directory where your Flex Gateway configuration and registration files reside.

//end::start-command-local-intro[]
//tag::start-command-local[]

[source,ssh,subs=attributes+]
----
docker run --rm \
-v <absolute-path-to-directory-with-gateway-files>/:/usr/local/share/mulesoft/flex-gateway/conf.d \
-p 8080:8080 \
mulesoft/flex-gateway
----
NOTE: Specify an optional name you want to assign to your Flex Replica by including the following: `-e FLEX_NAME=<name-for-flex-replica> \`.

//end::start-command-local[]
//tag::start-command-local-valid[]
The Docker logs should include this line:

[source,ssh]
----
[flex-gateway-envoy][info] all dependencies initialized. starting workers
----
// end::start-command-local-valid[]
// tag::create-config-folder-file[]

// end::create-config-folder-file[]
// tag::config-content[]

// end::config-content[]
// tag::linux-start-commands[]

=== Start Commands

Start Flex Gateway with the following command: 

[source,ssh]
----
sudo systemctl start flex-gateway
----

Verify that the Flex Gateway service is running successfully:

[source,ssh]
----
systemctl list-units flex-gateway*
----

You should see a list of services. Flex Gateway is successfully running if each service has a status of `active`.

[source,text]
----
  UNIT                              LOAD   ACTIVE SUB     DESCRIPTION
  flex-gateway-fluent-reloader.path loaded active waiting flex-gateway-fluent-reloader.path
  flex-gateway-agent.service        loaded active running flex-gateway-agent.service
  flex-gateway-envoy.service        loaded active running flex-gateway-envoy.service
  flex-gateway-fluent.service       loaded active running flex-gateway-fluent.service
  flex-gateway.service              loaded active exited  Application
----

// end::linux-start-commands[]
//tag::k8s-install-helm-chart[]

=== Install Helm Chart into the Namespace

Before installing, ensure that you have:

* https://helm.sh/docs/intro/install/[Helm^], a tool used to install Flex Gateway, monitoring tools, and applications. A minimum Helm version of 3.0.0 is required. 
+
Refer to the <<helm-chart-options,Helm Chart Configuration Options>> for information about customizing the chart.

. Add the Flex Gateway Helm repository:
+
[source,kubernetes]
----
helm repo add flex-gateway https://flex-packages.anypoint.mulesoft.com/helm
----

. Update the Helm repository using the following command:
+
[source,kubernetes]
----
helm repo up
----

. Using Ingress, install the *flex-gateway* Helm chart into the *gateway* namespace.
+
[source,kubernetes]
----
helm -n gateway upgrade -i --create-namespace --wait ingress flex-gateway/flex-gateway \
--set-file registration.content=registration.yaml
----
+
The command returns something similar to the following: 
+
[source,text]
----
NAME: ingress
LAST DEPLOYED: Tue Oct 19 13:08:07 2021
NAMESPACE: gateway
STATUS: deployed
REVISION: 1
TEST SUITE: None
----

//end::k8s-install-helm-chart[]
//tag::gateway-connected[]

Now if you check in Runtime Manager after clicking *Flex Gateway* in the left navigation, your gateway's status is connected. You may need to refresh the page.

If a Flex Replica
in Connected Mode is stopped it will be removed from the UI in Runtime Manager after 30 days. Otherwise,
it will appear in the Runtime Manager UI even if it is no longer running.

//end::gateway-connected[]
//tag::helm-chart-options[]

[[helm-chart-options]]
=== Helm Chart Configuration Options

The following command describes the configurable options of the Helm chart for Flex Gateway:

[source,kubernetes]
----
helm show values flex-gateway/flex-gateway
----

To view the Helm chart `README`, execute the following:

[source,kubernetes]
----
helm show readme flex-gateway/flex-gateway
----

//end::helm-chart-options[]
