//tag::add-flex-intro[]
== Flex Replicas

A Flex Replica is an instance of Flex Gateway. Setting up your gateway layer with multiple Flex Gateway replicas will enable the APIs deployed on Flex Gateway to serve more traffic.

When using Flex Gateway to manage APIs in production, you should at least have more than one Flex Replica to avoid a single point of failure. Running multiple Flex Replicas also increases performance if your API service receives a significant amount of traffic.
//end::add-flex-intro[]

//tag::add-flex-rep-byb[]
== Before You Begin

Before getting started, ensure you have completed the following tasks:

* xref:flex-install.adoc[Install a Flex Gateway]
//end::add-flex-rep-byb[]
//tag::add-flex-rep-byb-conn[]
* xref:flex-conn-reg-run.adoc[Register and Run in Connected Mode]
//end::add-flex-rep-byb-conn[]
//tag::add-flex-rep-byb-local[]
* xref:flex-local-reg-run.adoc[Register and Run in Local Mode]
//end::add-flex-rep-byb-local[]
//tag::add-flex-rep1[]

== Add a Flex Replica as a Linux Service

Adding a Flex Replica as a Linux Service includes the following tasks:

* Copy and paste the registration file created during registration to your Linux machine or VM.
* Run the Flex Gateway start command.

=== Copy the Registration File

Copy the `registration.yaml` file to the following location on your Linux machine or VM:

* `/usr/local/share/mulesoft/flex-gateway/conf.d`

//end::add-flex-rep1[]
//tag::add-flex-rep2[]

Now if you check in Runtime Manager after clicking *Flex Gateway* in the left navigation, your Flex Gateway will have an additional replica listed. You may need to refresh the page.

//end::add-flex-rep2[]