//tag::intro1[]
For use cases where Flex Gateway is deployed behind a load balancer or other external service, Flex Gateway supports Proxy Protocol to perserve client IP address across multiple layers of NAT or TCP proxies.

In Proxy Protocol, the load balancer or other proxy service sends the Proxy Protocol header containing the client address information to Flex Gateway. To learn more about Proxy Protocol, see the https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt[HAProxy specification].

Your load balancer must support Proxy Protocol to transmit the Proxy Protocol header.

When Proxy Protocol is enabled, the Proxy Protocol header is mandatory for incoming requests. If the header is not present Envoy closes the connection.

//end::intro1[]

//tag::proxy-config[]
== Enable Proxy Protocol
To enable your Flex Gateway to receive the Proxy Protocol header, add the following configuration file to your configuration directory:

[source,yaml]
----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Configuration
metadata:
  name: config
spec:
  proxyProtocol:
    enabled: true
----

//end::proxy-config[]

//tag::see-also[]

== See Also

* https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt[HAProxy specification^]


//end::see-also[]