= Configuring Replica Configuration Caching in Connected Mode
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

Enable replica configuration caching to have a Flex Gateway replica cache its gateway configuration in Redis shared storage. When configured, new replicas use the cached gateway configuration Instead of each replica directly downloading the configuration from Anypoint Platform. Caching a replica's configuration reduces scale-up time and increases resiliency.

Replica caching works by:

. When the first Flex Replica is created, it sees that there is no configuration in the Redis shared storage.
. The first replica creates the group ID and downloads its configuration from Anypoint Platform. The replica then stores the configuration in Redis.
. When a new Flex Replica is created, it uses the stored configuration.
. When the configuration is updated on Anypoint Platform, a single replica downloads the necessary configuration from Anypoint Platform and stores the configuration in Redis for the other replicas to use.


== Enable Replica Caching

. Ensure the Redis shared storage is configured.
+
To learn more, see xref:flex-conn-shared-storage-config.adoc[].

. Enable the `FLEX_DATASOURCE_CONTROL_NODE_ENABLED=true` environment variable.

