= Troubleshooting Managed Gateway Maintenance
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

When viewing or maintaining Anypoint Managed Flex Gateway instances, you might encounter issues. Check these topics for possible causes and solutions.

* xref:#gateway-metrics-not-showing[Missing Gateway Metrics]
* xref:#cant-change-gateway-properties[Gateway Properties Not Editable]
* xref:#timeout-while-waiting-for-update[Timeout While Waiting for Update]
* xref:#gateway-missing-disabled[Gateway is Missing or Disabled]
* xref:#same-path-error[API Path Conflict]

[[gateway-metrics-not-showing]]
== Missing Gateway Metrics

In Runtime Manager, if you can't see metrics for your gateway from the Managed Flex Gateway dashboard, verify that you have the _Usage Viewer_ permission. 

Verify your permissions::

Check your assigned roles and permissions for Runtime Manager in Access Management to verify that you have the required _Usage Viewer_ permission.

Your Anypoint Platform Admin can add these permissions in Access Management.
See xref:access-management::configure-teams.adoc#manage-team-permissions[Manage Team Permissions] for more information. 

[[cant-change-gateway-properties]]
== Can't Change Gateway Properties

Some Managed Flex Gateway properties, such as such as *Gateway Name*, *Deployment Target*, and *Flow plans*, can't be edited after the gateway instance is created. If you need to change one of these properties, you must delete and recreate your Managed Flex Gateway with the desired values.

[[timeout-while-waiting-for-update]]
== Timeout While Waiting for Update

If your Managed Flex Gateway update or deletion is stalled, refresh the status and check again in a few minutes. Delays can happen when the Anypoint Platform is handling a lot of traffic.

[[gateway-missing-disabled]]
== Gateway is Missing or Disabled in API Manager

In API Manager, when adding an API instance to a gateway, if you do not find your Managed Flex Gateway in the API Manager *Select a gateway* list, or the Managed Flex Gateway is disabled, verify the gateway status in Runtime Manager. If the gateway status isn't *Running*, you can the probelm from Runtime Manager. If the gateway status is *Running*, but still unavailable in API Manager, there might be a cluster issue, and you should contact MuleSoft Support for assistance.

[[same-path-error]]
== API Path Conflict

If you see the *This path conflicts with another API* error in API Manager when an API to a Managed Flex Gateway, you must choose a different base path. Each API instance in a Flex Gateway must be unique (within the gateway). To fix this problem, change the API path to a unique value or edit the path of the conflicting API. Click *API* in the error message to view or edit the API instance with the conflicting path.