= Configuring Flex Gateway Caching in Connected Mode
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

Enable Flex Gateway configuration caching to have a Flex Gateway cache its gateway configuration in Redis shared storage. Flex replicas then use the cached gateway configuration instead of each replica directly downloading the configuration from Anypoint Platform. Caching configuration reduces scale-up time and increases resiliency.

Flex Gateway configuration caching works by:

. After the first Flex replica starts, the replica downloads the configuration from Anypoint Platform, encrypts the configuration, and stores it in Redis.
. After subsequent replicas start, they use the locally cached configuration rather than downloading from Anypoint Platform.
. If the Flex Gateway configuration changes on Anypoint Platform, the replicas download the necessary configuration from Anypoint Platform and store it in Redis for immediate use by the other replicas.

If caching is configured and Redis errors occur, each replica downloads configurations directly from Anypoint Platform. If Flex Gateway disconnects from Anypoint Platform, Flex gateway uses the cached configuration until connections are restored.

== Enable Flex Gateway Configuration Caching

. Ensure the Redis shared storage is configured.
+
To learn more, see xref:flex-conn-shared-storage-config.adoc[].

. Enable the `FLEX_DATASOURCE_CONTROL_NODE_ENABLED=true` environment variable.

