= Troubleshoot APIs with Managed Gateway 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

When you add an API to an Anypoint Managed Flex Gateway instance, you might encounter issues. Check these topics for possible causes and solutions.

== Gateway is Missing or Disabled

When adding an API instance to a Managed Flex Gateway, you can't select the desired Managed Gateway as a target.

Cause::

* The gateway status or readiness. The Managed Gateway instance must successfully start and have at least one replica running in the cluster to receive traffic.

Troubleshooting Steps::

* Verify Gateway Status
+
--
    * Confirm the Managed Gateway status in Runtime Manager.
    * Ensure the gateway status is *Running*.
--
* Verify Cluster Health:
+
--
    * If the gateway is *Running* but is still unavailable, a cluster issue might be the cause.
--

Possible Solution::

* Contact Support
+
--
    * If the gateway is *Running* but still not selectable, contact MuleSoft Support for assistance.
--

== Same Path Error Creating API

An error occurs when trying to specify an API path, indicating that the path is already in use.

Cause::

* The API path must be unique. API paths must be unique within the gateway, and can't be shared with other APIs associated with the same gateway.

Possible Solutions::
* Change or Edit API Path
+
--
    * Change the API path to a unique value.
    * Edit the path of the conflicting API to resolve the conflict.
--
