= Flex Gateway Version Lifecycle
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

== Edge and LTS Release Channels

Flex Gateway releases are available in two release channels, Edge and Long-term Support (LTS). 

[%header,cols="4*a"]
|===

| Channel Type | Release Cadence | Differentiators | Support Coverage

| Edge 
| Three times per year 
| Includes new features on a frequent release cadence with shorter maintenance coverage.
a| 
* 4 months of Standard Support
* 4 months of Extended Support

| LTS
| Annual
| Includes new features introduced in prior Edge releases, along with new features introduced in the current year Edge release. This release is maintained for an extended period.
a|
* 12 months of Standard Support
* 12 months of Extended Support

|===

The following table shows the length of support for Flex Gateway releases:

[%header%autowidth.spread]
|===
| Release Channel | Gateway Version |Release Date | End of Standard Support | End of Extended Support
| Edge | 1.9 | March 2025 | July 2025 | November 2025
| Edge | 1.10 | July 2025 | November 2025 | March 2026
| Edge | 1.11 | November 2025 | March 2026 | July 2026
| Edge | 1.12 | March 2026 | July 2026 | November 2026
| LTS | 1.9 | March 2025 | March 2026 | March 2027
| LTS | 1.12 | March 2026 | March 2027 | March 2028
|===


Consider the following factors to determine which release channel is the best choice for your requirements.

* Edge release channel
+ 
Mulesoft releases Flex Gateway Edge versions three times per year. Use the Edge channel if you want to stay on top of the latest features and feel comfortable with a more frequent release cycle and auto-upgrade cycle. The Edge channel includes the latest features and innovations available on the MuleSoft platform.

* LTS release channel
+ 
MuleSoft releases Flex Gateway Long-Term Support (LTS) versions once a year. Use the LTS channel if you want to avoid upgrading to a new version frequently. The LTS channel adopts new capabilities after they have been introduced via Edge releases.

== Flex Gateway Version Lifecycle Management

Flex Gateway lifecycle management varies depending on the release channel and the type of gateway. Managed gateways are auto-upgraded regularly, and any available patches are applied once per month. Self-managed gateways are never never patched or upgraded automatically.

For information on how to patch, upgrade, or roll back your gateway version, see xref:flex-gateway-upgrade.adoc[].