= Securing Agent Interactions with Flex Gateway
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

Flex Gateway supports both the Model Context Protocol (MCP) and the Agent2Agent (A2A) Protocol, enabling you to protect your agents and systems. Flex Gateway provides centralized oversight, agent visibility, logging, and valuable insights, ensuring effective governance and security for your agent-based architecture. Flex Gateway secures agent interactions by enforcing policies across agent connections and monitoring agent activities for enhanced visibility.

== Flex Gateway A2A and MCP Support

Flex Gateway enables you to secure and manage MCP and A2A agent interactions.

A2A::
  An open standard that defines how agents interact with each other, enabling interoperability for agents built by different teams, using different technologies, and hosted by different organizations.

MCP::
  An open protocol that defines how agents interact with tools or external context, enabling agents to connect with the data and tools they need.

== Securing Agent Interactions with Policies

Flex Gateway includes A2A and MCP specific policies that provide enhanced security and control over agent interactions. Flex Gateway A2A policies enable you to protect agent endpoints by rewriting Agent Cards URLs, logging or blocking sensitive information in messages, modifying prompt behavior, and  logging Server-Sent Events (SSE) content for compliance audits.  Flex Gateway MCP policies enable you to use attribute-based access control to manage access to MCP servers.

Flex Gateway MCP and A2A server instances also support Flex Gateway's other policies. For example, use policies such as xref:policies-included-rate-limiting.adoc[] or xref:policies-included-spike-control.adoc[] to manage the number of requests to MCP and A2A servers or the policies-included-message-logging.adoc[] to monitor agent interactions.

See xref:flex-agent-policies.adoc[] to learn about included A2A and MCP policies.

== See Also

* https://blogs.mulesoft.com/news/mulesoft-governance-for-agent-interactions/[Introducing Governance for Agent Interactions With Support for A2A & MCP]
* https://google.github.io/A2A/topics/what-is-a2a/[A2A Protocol spec]
* https://modelcontextprotocol.io/introduction[MCP Protocol spec]
* https://google.github.io/A2A/topics/streaming-and-async/[Streaming & Asynchronous Operations in A2A]
