= Troubleshoot Managed Gateway Maintenance
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

When viewing or maintaining Anypoint Managed Flex Gateway instances, you might encounter issues. Check these topics for possible causes and solutions.

== Viewing and Updating Settings

=== Gateway Metrics Not Showing

Metrics are missing from the Managed Flex Gateway dashboard.

Causes::

* Insufficient user permissions. You must have the *Usage Viewer* permission to view gateway metrics.

Troubleshooting Steps::

* Verify User Permissions
+
--
    . Navigate to Access Management and check your assigned roles and permissions for Runtime Manager.
    . Check whether you  have the *Usage Viewer* permission.
--

Possible Solution::

* Grant Necessary Permissions
+
--
    * Your Anypoint Platform Admin must grant you the *Usage Viewer* permission in Access Management. See xref:access-management::configure-teams.adoc#manage-team-permissions[Manage Team Permissions] for more information. 
--

=== Can't Change Gateway Properties

You can't edit some of the Managed Flex Gateway properties in the .

Cause::

* Fields such as *Gateway Name*, *Deployment Target*, and *Flow plans* can't be changed.

Possible Solutions::

* Create a New Gateway
+
--
    * Create a new Managed Flex Gateway with the desired values for the read-only fields.
--

=== Timeout While Waiting for Update

The status poller times out while waiting for the gateway to return to `STARTED` status after an update.

Cause::

* Anypoint Platform service overload, due to high traffic and demand on services.

Possible Solutions::

* Refresh and Retry
+
--
    * Refresh the status after some time to check the gateway's current state.
--

== Deleting Gateway

=== Delay Deleting Gateway

Gateway shown as *Deleting* for an extended period and continues to consume quota.

Causes::

* Anypoint Platform service overload, due to high traffic and demand on services. The quota is not released until the gateway is fully deleted.

Possible Solutions::

* Refresh and Retry
+
--
    * Refresh the status after some time to check if the gateway has been successfully deleted.
--