= Flex Gateway Version Lifecycle
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

== Edge and LTS Release Channels

Flex Gateway releases are available in two release channels, Edge and Long-term Support (LTS). 

[%header,cols="4*a"]
|===

| Channel Type | Release Cadence | Differentiators | Support Coverage

| *Edge* 

a| Three times per year

    * March
    * July
    * November

| Includes new features more often and has a shorter support period for each release.

a| For versions 1.9 and later:

    * 4 months of Standard Support
    * 4 months of Extended Support

| *LTS*

| Once per year
    
    * March

| Bundles new features in an annual release and has a longer support period for each release.

a| For versions 1.9 and later:

    * 12 months of Standard Support
    * 12 months of Extended Support

|===

In March, both Edge and LTS channels release with the same underlying version.

For more information about the support policy that aligns with the release periods and types of releases, see the https://www.salesforce.com/content/dam/web/en_us/www/documents/legal/Agreements/versioning-back-support-policy.pdf[MuleSoft Support Policy]. 

[[edge_channel]]
=== Edge Channel

Starting with Flex Gateway 1.9, MuleSoft releases Edge versions three times per year, in March, July, and November.
Use the Edge channel if you want to stay on top of the latest features and feel comfortable with a more frequent release and upgrade cycle. 
The Edge channel includes the latest features and innovations available on Flex Gateway.

=== LTS Channel

Starting with Flex Gateway 1.9, MuleSoft releases Long-Term Support (LTS) versions once a year, in March. Use the LTS channel if you want to upgrade less frequently. The LTS channel adopts new capabilities after they've been introduced via Edge releases.

== Switch from an Edge Version to an LTS Version

You can switch from an Edge version to an LTS version and vice versa. However, when moving from Edge to LTS, you must choose a later LTS version. For example, if you choose Flex Gateway 1.9 LTS and you want to take advantage of new feature released on Flex Gatway 1.10 Edge, you can opt into that Edge release, and then return to the LTS release channel after the next annual Flex Gateway LTS release (which is Flex Gateway 1.12 LTS, for this example).

== Flex Gateway Version Lifecycle Management

Flex Gateway lifecycle management varies depending on the release channel and the type of gateway. Managed gateways are auto-upgraded regularly, and any available patches are applied once per month. Self-managed gateways are never never patched or upgraded automatically.

For information on how to patch, upgrade, or roll back your gateway version, see xref:flex-gateway-upgrade.adoc[].