= Applying Policies for Managed Flex Gateways and Connected Mode
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:page-aliases: api-manager::using-policies.adoc, policies::policies-included-apply.adoc, policies-included-apply.adoc

For Managed Flex Gateway and Flex Gateway running in Connected Mode, you apply inbound and outbound policies using *API Manager*. To find the policies provided by Flex Gateway, see xref:policies-included-directory.adoc[] and xref:policies-outbound-directory.adoc[].

== Apply an Inbound Policy

. Go to *Anypoint Platform > API Manager*.
. In *API Administration*, click the name of the API to which you want to apply a policy.
. From the side navigation panel, click *Policies*.
. Click *+ Add policy*.
. Select the policy to apply.
. Configure the required parameters.
+
For policy configuration parameters, see xref:policies-included-directory.adoc[].
. If necessary, configure *Advanced options*.
. Click *Apply*.

You can apply a policy to the entire API by default, or to specific methods and resources within the API.

== Apply an Outbound Policy

. Go to *Anypoint Platform > API Manager*.
. In *API Administration*, click the name of the API to which you want to apply a policy.
. From the side navigation panel, click *Policies*.
. Click the *Outbound policies* tab.
. Click *+ Add outbound policy*.
. Select the *Upstream* to which you want to apply a policy.
. If you want to apply the policy to an additional upstream, click *Add upstream* and select the additional upstream. Repeat this step for all upstreams to which you want to apply the policy.
. Click *Next*.
. Select the policy to apply.
. Configure the required parameters.
+
For policy configuration parameters, see xref:policies-outbound-directory.adoc[].
. If necessary, configure *Advanced options*.
. Click *Apply*.

You can apply a policy to the entire upstream by default, or to specific methods and resources of the upstream.

== See Also

* xref:index.adoc[]
* xref:flex-gateway-getting-started.adoc[]
