= Securing Agent Communication with Flex Gateway
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

Anypoint Flex Gateway supports the Model Context Protocol (MCP) and Agent2Agent (A2A) protocols, enabling you to secure, manage, and govern agent-to-tool and agent-to-agent interactions. Use Flex Gateway with MCP and A2A to protect both your agents and systems.

== Flex A2A Support
A2A is an open standard that defines how agents interact with each other. Enable interoperability among agents built by different teams, using different technologies, and hosted by different organizations with A2A.

Use Flex Gateway with A2A to:

Protect agent interactions::
  Require that agents are invoked with appropriate authentication and authorization.

Enhance agent requests::
  Modify incoming prompts with additional context to improve server agent execution.

Provide centralized oversight::
  Enable frictionless agent visibility, logging, and insights for debugging and optimization.

== Flex MCP Support
MCP is an open protocol that defines how agents interact with tools or external context. Connect agents with the data and tools they need with MCP.

Use Flex Gateway with MCP to:

Secure connections::
  Restrict MCP endpoint access to authorized agents only.

Enforce rate limits::
  Help your organization meet performance requirements by controlling the number of requests.

Simplify governance::
  Provide centralized visibility and control over all interactions.

For more information, see the link:MCP Protocol spec[https://modelcontextprotocol.io/introduction].

== Use MCP and A2A with Flex Gateway

These Flex Gateway policies provide support for the MCP and A2A protocols:

A2A Specific Policies:

* Schema Validation: Verify requests conform to the A2A schema. +
See xref:policies-included-a2a-schema.adoc[].
* Agent Card Policy: Proxy the agent through Flex Gateway by rewriting the agent card. +
See xref:policies-included-agent-card.adoc[].
* PII Detector: Detect sensitive information in messages sent to and from agents. +
See xref:policies-included-pii-detector.adoc[].
* Prompt Decorator: Modify prompt behavior by injecting custom prompts into requests. +
See xref:policies-included-prompt-decorator.adoc[].
* Server-Sent Events (SSE) Content Logging: Log content sent by agents for audit and compliance needs. +
See xref:policies-included-sse-logging.adoc[].

MCP Specific Policies:

* Schema Validation: Verify requests conform to the MCP schema. +
See xref:policies-included-mcp-schema.adoc[].
* Protocol Support: Enable MCP support and enable Server-Sent Events (SSE). +
See xref:policies-included-enable-mcp.adoc[].
* Attribute-based access control: Enable access to MCP servers based on Anypoint access tiers. +
See xref:policies-included-attrib-access-control.adoc[].


== See also
* Introducing Governance for Agent Interactions With Support for A2A & MCPhttps://blogs.mulesoft.com/news/mulesoft-governance-for-agent-interactions/
* A2A Protocol spec[https://google.github.io/A2A/topics/what-is-a2a/]
* MCP Protocol spec[https://modelcontextprotocol.io/introduction]
* Streaming & Asynchronous Operations in A2A[https://google.github.io/A2A/topics/streaming-and-async/]
