= Flex Gateway Version Lifecycle
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

== Edge and LTS Release Channels

Flex Gateway releases are available in two release channels, Edge and Long-term Support (LTS). 

[%header,cols="4*a"]
|===

| Channel Type | Release Cadence | Differentiators | Support Coverage

| *Edge* 

a| Three times per year

    * March
    * July
    * November

| Includes new features more often and has a shorter support period for each release.

a| Flex Gateway 1.9 and later

    * 4 months of Standard Support
    * 4 months of Extended Support

| *LTS*

| Once per year
    
    * March

| Bundles new features in an annual release and has a longer support period for each release.

a| Flex Gateway 1.9 and later

    * 12 months of Standard Support
    * 12 months of Extended Support

|===

For detailed information and support timeframes for Flex Gateway 1.8 and earlier, see the https://www.salesforce.com/content/dam/web/en_us/www/documents/legal/Agreements/versioning-back-support-policy.pdf[MuleSoft Support Policy]. 

[[edge_channel]]
=== Edge Channel

Starting with Flex Gateway 1.9, MuleSoft releases Edge versions three times per year, in March, July, and November.
Use the Edge channel if you want to stay on top of the latest features and feel comfortable with a more frequent release and upgrade cycle. 
The Edge channel includes the latest features and innovations available on Flex Gateway.

=== LTS Channel

Starting with Flex Gateway 1.9, MuleSoft releases Long-Term Support (LTS) versions once a year, in March. Use the LTS channel if you want to upgrade less frequently. The LTS channel adopts new capabilities after they've been introduced via Edge releases.

== Flex Gateway Version Lifecycle Management

Flex Gateway lifecycle management varies depending on the release channel and the type of gateway. Managed gateways are auto-upgraded regularly, and any available patches are applied once per month. Self-managed gateways are never never patched or upgraded automatically.

For information on how to patch, upgrade, or roll back your gateway version, see xref:flex-gateway-upgrade.adoc[].