= Securing Flex Gateway APIs with Policies
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

Policies enforce rules when Flex Gateway processes requests, enabling you to secure and govern your Flex Gateway APIs.

MuleSoft provides policies that you can apply to your APIs via Anypoint Platform or declarative configuration files. The provided policies include rate limiting, caching, authentication, authorization, threat protection, monitoring, and logging. For more information about MuleSoft-provided policies, see the xref:policies-included-directory.adoc[] and xref:policies-outbound-directory.adoc[].

To extend existing functionality or define new functionality, create custom policies based on your specific business requirements and apply them to APIs. For information about creating custom policies, see xref:pdk::policies-pdk-overview.adoc[].

Automated policies enable your API instance to comply with common security and logging requirements by automatically applying the same set of policies to all APIs running in Flex Gateway. See xref:policies-automated-overview.adoc[] for more information.

To apply a policy for Managed Flex Gateway or Connected Mode, see xref:flex-gateway-secure-conn.adoc[].

To apply a policy in Local Mode, see xref:flex-gateway-secure-local.adoc[].

For information about policy reordering, see xref:policies-reorder.adoc[].

For information about DataWeave support, see xref:policies-flex-dataweave-support.adoc[].

== See Also

* xref:index.adoc[]
* xref:flex-gateway-getting-started-overview.adoc[]