= Applying Policies for Managed Flex Gateways and Connected Mode
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

:page-aliases: policies-included-apply.adoc, api-manager::using-policies.adoc, policies::policies-included-apply.adoc

For Managed Flex Gateway and Flex Gateway running in Connected Mode, you apply API policies using *API Manager*. To find the policies provided by Flex Gateway, see xref:policies-included-directory.adoc[Included Policies Directory].

== Apply a Policy

. Go to *Anypoint Platform > API Manager*.
. In *API Administration* click the name of the API to which to apply a policy.
. From the left navigation menu, click *Policies*.
. Click *+ Add policy*.
. Select the policy to apply.
. Configure the required configuration parameters.
+
For policy configuration parameters, see xref:policies-included-directory.adoc[Included Policies Directory].
. Click *Apply*

You can apply a policy either to the entire API (default) or to specific methods and resources of an API.

== See Also

* xref:index.adoc[]
* xref:flex-gateway-getting-started.adoc[]
