= MCP Attribute-Based Access Control Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:keywords: api gateway, flex gateway, gateway, policy

[width="100%", cols="5,15"]
|===
>s| Policy Name | MCP Attribute-Based Access Control
>s|Summary      | Controls access to tools, resources, and prompts based on user information such as Tiers, IP, Headers, or Claims
>s|Category | MCP
>s|First Flex Gateway version available | v1.9.3
>s| Returned Status Codes |
|===

== Summary



== Configuring Policy Parameters

include::partial$policy-title-headers.adoc[tag=ui]

[%header%autowidth.spread,cols="a,a"]

|===
| Element | Description
| Rules | 

Cedar Expression | Cedar (https://docs.cedarpolicy.com/) rules for granting access to tools, resources and prompts. e.g "permit(principal,action == Action::"tools/call", resource == Tool::"calculator");"

| Authentication Type | Select ClientId if ClientId enforcement is used. Select Other for different authentication types such as JWT. If using other, you must apply another policy from the Authentication
      Note that the Authentication policy must be inserted before this one.
|===
