= Response Idle Timeout
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:keywords: basic authentication, api gateway, flex gateway, gateway, policy

[width="100%", cols="5,15"]
|===
>s| Policy Name | Response Idle Timeout
>s|Summary      | 
>s|Category | 
>s|First Flex Gateway version available | v1.9.0
^s| Returned Status Codes | 504 - Upstream request timeout
|===

== Summary

The Stream Idle Timeout policy enables you to set a maximum amount of a time Flex Gateway waits for a response from an upstream service.
The timeout time starts at the last request sent by Flex Gateway. 

By default, all Flex Gateway API instances have a response timeout of 15 seconds. Apply the policy overrides this default.

== Configuring Policy Parameters

=== Flex Gateway Local Mode

In Flex Gateway Local Mode, you apply the policy to your API via declarative configuration files. Refer to the following policy definition and table of parameters:

----
- policyRef:
    name: response-timeout
  config:
    timeout: number // REQUIRED
----

[%header%autowidth.spread,cols="a,a,a,a"]
|===
|Parameter | Required or Optional | Default Value | Description

| `timeout`
| Required
| 15
| Time in seconds Flex Gateway waits for the response.

|===

==== Resource Configuration Example

----
- policyRef:
    name: stream-idle-timeout
  config:
    timeout: 3
----

=== Flex Gateway Connected Mode

When you apply the policy to your API from the UI, the following parameters are displayed:

[%header%autowidth.spread,cols="a,a,a"]
|===
| Element | Description | Required
| Response timeout | Time in seconds Flex Gateway waits for the response. | Yes
|===

