= Upstream Idle Timeout Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:keywords: basic authentication, api gateway, flex gateway, gateway, policy

[width="100%", cols="5,15"]
|===
>s| Policy Name | Stream Idle Timeout
>s|Summary | Sets a maximum amount of a time a stream between Flex Gateway and a upstream service can remain idle
>s|Category | Quality of Service
>s|First Flex Gateway version available | v1.9.0
^s| Returned Status Codes | 504 - Upstream request timeout
|===

== Summary

The Upstream Idle Timeout policy enables you to set a maximum amount of a time a stream between Flex Gateway and the upstream service can remain idle without receiving any additional requests. This policy prevents idle connections from consuming resources while allowing persistent connections to remain open. The timeout time starts at the last request. 

By default, all Flex Gateway API instances have an upstream idle timeout of 60 seconds. Apply the policy overrides this default.

== Configuring Policy Parameters

=== Flex Gateway Local Mode

In Flex Gateway Local Mode, you apply the policy to your API via declarative configuration files. Refer to the following policy definition and table of parameters:

----
- policyRef:
    name: upstream-idle-timeout
  config:
    timeout: number // REQUIRED
----

[%header%autowidth.spread,cols="a,a,a,a"]
|===
|Parameter | Required or Optional | Default Value | Description

| `timeout`
| Required
| 60
| Time in seconds before Flex Gateway closes the connection.

|===

==== Resource Configuration Example

----
- policyRef:
    name: upstream-timeout-flex
  config:
    timeout: 3
----

=== Flex Gateway Connected Mode

When you apply the policy to your API from the UI, the following parameters are displayed:

[%header%autowidth.spread,cols="a,a,a"]
|===
| Element | Description | Required
| Upstream idle timeout | Time in seconds before Flex Gateway closes the connection. | Yes
|===
