= Credential Injection OAuth 2.0 Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:keywords: basic authentication, api gateway, flex gateway, gateway, policy

[width="100%", cols="5,15"]
|===
>s| Policy Name | Credential Injection OAuth 2.0
>s|Summary      | Allows access based on the basic authorization mechanism, with a single user-password
>s|Category | Security
>s|First Flex Gateway version available | v1.0.0
.1+>.^s| Returned Status Codes
| 401 - Unauthorized or invalid client application credentials in HTTP or RAML APIs
| | 403 - Forbidden: Authentication succeeded, but access is denied.
| | 500 - Unauthorized or invalid client application credentials in WSDL API using SOAP 1.1
|===

== Summary

The Credential Injection OAuth 2.0 policy injects an `Authorization` token from an OAuth 2.0 service into a request as a header. You can use any third-party OAuth 2.0 Identify Provider (IdP), such as Okta, AWS, Azure or Google Cloud Platform.
The policy allows for tokens based on the OAuth 2.0 Authorization Framework to be injected into requests without having to register an external IdP server in the Anypoint Platform.

== Configuring Policy Parameters

=== Flex Gateway Local Mode

In Flex Gateway Local Mode, you apply the Basic Authentication: Simple policy to your API via declarative configuration files. Refer to the following policy definition and table of parameters:

----
- policyRef:
    name: http-basic-authentication-flex
  config:
    oauthService: <string> // REQUIRED
    clientId: <string> // REQUIRED
    clientSecret: <string> // REQUIRED
    scope:
      - <string> // OPTIONAL
    overwrite: <boolean> // REQUIRED
    tokenFetchTimeout: <number> // REQUIRED
    allowRequestWithoutCredential: <boolean> // REQUIRED
----

[%header%autowidth.spread,cols="a,a,a,a"]
|===
|Parameter | Required or Optional | Default Value | Description

| `oauthService`
| Required
| `<https://oauth-server/tokens>`
| URL of the OAuth 2.0 service.

| `clientId`
| Required
| N/A
| Client ID.

| `clientSecret`
| Required
| N/A
| Client Secret.

| `scope`
| Optional
| N/A
| Scopes to include in the token.

| `overwrite`
| Required
| `true`
| When enabled, if the `Authorization` header is present, the policy overwrites it with the new authorization token.

| `tokenFetchTimeout`
| Required
| 10
| Time in seconds to wait for the service to return the token.

| `allowRequestWithoutCredential`
| Required
| `false`
| When enabled, if the policy can't retrieve the token, Flex Gateway still sends the request.
|===

==== Resource Configuration Example

----
- policyRef:
    name: http-basic-authentication-flex
  config:
    oauthService: <https://oauth-server/tokens>
    clientId: id
    clientSecret: secret
    scope:
      - user
    tokenFetchTimeout: 20
    allowRequestWithoutCredential: ture
----

=== Flex Gateway Connected Mode

When you use the UI to apply the Message Logging policy to your API, you can configure the following parameters:

[%header%autowidth.spread]
|===
|Parameter |Description | Required?
|OAuth 2.0 service URL |URL of the OAuth 2.0 service. |Required
|Client ID |Client ID. |Required
|Client secret |Client Secret. |Required
|Scope |Scopes to include in the token. |Optional
|Overwrite header |When enabled, if the `Authorization` header is present, the policy overwrites it with the new authorization token. | Required
|Token fetch timeout |Time in seconds to wait for the service to return the token. | Required
|Allow request without credential |When enabled, if the policy can't retrieve the token, Flex Gateway still sends the request. | Required
|===

