= Credential Injection OAuth 2.0 Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:keywords: basic authentication, api gateway, flex gateway, gateway, policy

[width="100%", cols="5,15"]
|===
>s| Policy Name | Credential Injection OAuth 2.0
>s|Summary      | Allows access based on the basic authorization mechanism, with a single user-password
>s|Category | Security
>s|First Flex Gateway version available | v1.0.0
.1+>.^s| Returned Status Codes
| 401 - Unauthorized or invalid client application credentials in HTTP or RAML APIs
| | 403 - Forbidden: Authentication succeeded, but access is denied.
| | 500 - Unauthorized or invalid client application credentials in WSDL API using SOAP 1.1
|===

== Summary


The Credential Injection OAuth 2.0 policy injects an authorization token from an OAuth 2.0 service as a header. You can use any third-party OAuth 2.0 Identify Provider (IdP), such as Okta, AWS, Azure or Google Cloud Platform.
The policy allows for tokens based on the OAuth 2.0 Authorization Framework to be injected into requests without having to register an external IdP server in the Anypoint Platform.

== Configuring Policy Parameters

=== Flex Gateway Local Mode

In Flex Gateway Local Mode, you apply the Basic Authentication: Simple policy to your API via declarative configuration files. Refer to the following policy definition and table of parameters:

----
- policyRef:
    name: http-basic-authentication-flex
  config:
    oauthService: <string> // REQUIRED
    clientId: <string> // REQUIRED
    clientSecret: <string> // REQUIRED
    scope:
      - <string> // OPTIONAL
    overwrite: <boolean> // REQUIRED
    tokenFetchTimeout: <number> // REQUIRED
    allowRequestWithoutCredential: <boolean> // REQUIRED
----

[%header%autowidth.spread,cols="a,a,a,a"]
|===
|Parameter | Required or Optional | Default Value | Description

| `oauthService`
| Required
| `<https://oauth-server/tokens>`
| 

| `clientId`
| Required
| N/A
| 

| `clientSecret`
| Required
| N/A
| 

| `scope`
| Optional
| N/A
| 

| `overwrite`
| Required
| `true`
| 

| `tokenFetchTimeout`
| Required
| 10
| 

| `allowRequestWithoutCredential`
| Required
| `false`
| 
|===

==== Resource Configuration Example

----
- policyRef:
    name: http-basic-authentication-flex
  config:
    username: chris
    password: admin
----

=== Flex Gateway Connected Mode

When you use the UI to apply the Message Logging policy to your API, you can configure the following parameters:

[%header%autowidth.spread]
|===
|Parameter |Description | Required?
|Username |The username for the basic authentication credentials
|Optional
|Password |The password for the basic authentication credentials |Optional
|Category |A prefix in the log message that indicates the package and class where the log is executed. |Optional
|Overwrite header |Whether you want to overwrite the authorization header present in the request.|Optional
|Custom Header |A custom header instead of an authorization header +
Example: `Authorization: Basic <username:password>`
|Optional
|===

