= Circuit Breaker Policy

[%autowidth.spread,cols="a,a"]
|===
>s| Policy name | Circuit Breaker
>s| Summary | Prevents an upstream from receiving too many requests or connection
>s| Category | Quality of Service
>s| First Flex Gateway version available | v1.9.0
.4+>.^s| Returned Status Codes
|503 - Service Unavailable
|===

== Summary

The Circuit Breaker policy helps prevent an upstream service from receiving too many requests or connections at a time. If any defined maximums are reached, Flex Gateway rejects the request or connection with a `503 - Service Unavailable` error code.

For Managed Flex Gateways or Connected Mode, if different API instances request the same upstream, the limits are independent, so each API instance can use a full maximum. For Local Mode, the limits are not independent, so different API instances share the maximums for an upstream. For all modes, maximums are not distributed across replicas, so each Gateway can use can use a full maximum.

The Circuit Breaker policy is an extension of the Envoy upstream clusters circuit breaking feature. To learn more about the Envoy's circuit breaking, see https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/circuit_breaking.html[Circuit Breaking].

== Configuring Policy Parameters

=== Flex Gateway Local Mode

In Local Mode, you apply the Circuit Breaker policy to your API via declarative configuration files. Refer to the following policy definition and table of parameters:

----
apiVersion: gateway.mulesoft.com/v1alpha1  
kind: PolicyBinding  
metadata:  
  name: upstream-policy  
spec:  
  targetRef:  
    Kind: Service  
    name: upstream  
  policyRef:  
    name: circuit-breaker-flex  
  config:  
    thresholds:  
      maxConnections: <number> // OPTIONAL 
      maxPendingRequests: <number> // OPTIONAL  
      maxRequests: <number> // OPTIONAL
      maxRetries: <number> // OPTIONAL  
      maxConnectionPools: <number> // OPTIONAL
----

NOTE: For Local Mode, the limits are not independent, so different API instances share the maximums for an upstream.

[%header%autowidth.spread,cols="a,a,a"]
|===
|Parameter | Required or Optional | Description


| `maximumConnections`
| Optional
| Maximum number of connections per API to an upstream.

| `maximumPendingRequests`
| Optional
| Maximum number of queued requests while waiting for a connection.

| `maximumRequests`
| Optional
| Maximum number of outstanding requests to an upstream.

| `maximumRetries`
| Optional
| Maximum number of outstanding retries.

| `maximumConnectionPools`
| Optional
| Maximum number of connection pools concurrently initiated to an upstream.

|===

==== Resource Configuration Example

The following example defines a  of three requests every six seconds:

----
apiVersion: gateway.mulesoft.com/v1beta1  
kind: Configuration  
metadata:  
  name: circuit-breaker  
  namespace: test-ns  
spec:  
  circuitBreaker:  
    thresholds:  
      maxConnections: 1  
      maxPendingRequests: 1  
      maxRequests: 1  
      maxRetries: 1  
      maxConnectionPools: 1  
----


=== Flex Gateway Connected Mode

When you apply the Rate Limiting policy to your API from the UI, you can configure the following parameters:


[%header%autowidth.spread,cols="a,a,a"]
|===
|Parameter | Required or Optional | Description

| Maximum connections
| Optional
| Maximum number of connections per API to an upstream.

| Maximum pending requests
| Optional
| Maximum number of queued requests while waiting for a connection.

| Maximum requests
| Optional
| Maximum number of outstanding requests to an upstream.

| Maximum retries
| Optional
| Maximum number of outstanding retries.

| Maximum connection pools
| Optional
| Maximum number of connection pools concurrently initiated to an upstream.

|===

NOTE: For Managed Flex Gateways or Connected Mode, if different API instances request the same upstream, the limits are independent, so each API instance can use a full maximum.
