= Configuring Readiness and Liveness Probes

Flex Gateway supports two methods for ensuring reliability and efficiency.

* Readiness probes test whether a gateway instance is configured correctly and ready for incoming traffic. This ensures that end-users are not affected by unstable or partially started services. For information, refer to <<configure-a-readiness-probe>>.

* Liveness probes test whether a gateway instance is operational. This minimizes downtime due to crashes or other failures. For information, refer to <<configure-a-liveness-probe>>.

[[configure-a-readiness-probe]]
== Configure a Readiness Probe

To test whether a Flex Gateway instance is ready for incoming traffic, you can use the following CLI command:

[source,ssh]
----
flexctl probe --check=readiness
----

If the Flex Gateway instance is ready to handle incoming traffic, the command returns an exit code of `0`. Otherwise the command returns an exit code of `1`.

When Flex Gateway is started, its readiness state is `false`. The state changes to `true` after the following conditions are met:

* API instances are deployed (at least one API must be configured)
* Policies are initialized

The readiness state is not impacted when you apply configuration changes to a running gateway instance. This enables error-free scaling.

Refer to the following for information about configuring readiness probes for specific environments:

[tabs]
====
Kubernetes and OpenShift::
+
By default, Flex Gateway running on Kubernetes includes a readiness probe configured in the Helm chart. The readiness probe automatically runs `flexctl probe --check=readiness` at an interval of 10 seconds.
+
The readiness probe is configured by default with the following values:
+
[source,helm]
----
readinessProbe:
 exec:
   command:
   - flexctl
   - probe
   - --check=readiness
   - --allow-api-errors
   - --allow-envoy-errors
   - --allow-policy-errors
 initialDelaySeconds: 10
 periodSeconds: 10
 failureThreshold: 2
 timeoutSeconds: 5
----
+
[cols="1,2"]
|===
| Parameter | Description
| `exec.command` | The readiness probe command
| `--allow-api-errors`| The flag to allow errors in API instances
| `--allow-envoy-errors`| The flag to allow Envoy configuration errors
| `--allow-policy-errors`| The flag to allow policy configuration errors
| `initialDelaySeconds` | The time in seconds to wait after startup before executing the first readiness probe
| `periodSeconds` | The period in seconds between each readiness probe
| `failureThreshold` | The number of failed readiness probes before the Kubernetes pod is restarted
| `timeoutSeconds` | The time in seconds before the readiness probe times out
|===
+
[discrete]
==== Configure Error Tolerance
+
The default readiness probe is configured to be error-tolerant. If a configuration error occurs (for example, if you misconfigure a policy), the readiness state still changes to `true` once the API instances and policies are deployed. This enables Flex Gateway to scale even though there might be configuration errors.
+
You can also configure the readiness probe to be error-intolerant, meaning that misconfigured gateway instances never reach a readiness state of `true`.
+
To configure the Helm chart for error intolerance, remove the following flags from the chart: `allow-api-errors`, `allow-envoy-errors`, and `allow-policy-errors`. In deployments that query the readiness state through HTTP requests, use query parameters: `allowEnvoyErrors=false`, `allowAPIErrors=false`, and `allowPolicyErrors=false`.
+
[discrete]
==== Configure External Components
+
You configure your external components to query the readiness state. For example, in AWS virtual machines that run behind a load balancer, configure the readiness query as a “health check”. To expose the readiness API to external components, apply the following configuration to the Flex Gateway instance:
+
[source,yaml]
----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Configuration
metadata:
 name: probe
spec:
 probe:
   enabled: true
   port: 3000
----
// TODO: NOTE: Omit the `--wait` flag in the Helm chart used to deploy your gateway.
NOTE: In the Helm chart used to deploy Flex Gateway, omit the `--wait` flag when using a readiness probe. Not doing so will result in a readiness failure because Helm waits for the readiness state to be `true`.

Docker, Podman, and Linux::
+
For Docker and Linux deployments, Flex Gateway does not include a pre-configured default readiness probe. However, you can still run the the readiness probe command manually, or configure it for automated use with third-party services. Besides the Kubernetes readiness probe, MuleSoft does not provide support for third-party readiness probes.
+
To expose the readiness API to external components, apply the following configuration to the Flex Gateway instance:
+
[source,yaml]
----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Configuration
metadata:
 name: probe
spec:
 probe:
   enabled: true
   port: 3000
----
====

[[configure-a-liveness-probe]]
== Configure a Liveness Probe

To test whether a Flex Gateway instance is operational, you can use the following CLI command:

[source,ssh]
----
flexctl probe --check=liveness
----

If the Flex Gateway instance is operational, the command returns an exit code of `0`. Otherwise the command returns an exit code of `1`.

You can either run the liveness probe command manually, or configure the command to run automatically. By default, Flex Gateway Kubernetes deployments have an automatic liveness probe configured. The default probe periodically runs the liveness probe command and automatically restarts the Flex Gateway pod after a specified number of failures.

Refer to the following for information about configuring liveness probes for specific environments:

[tabs]
====
Kubernetes and OpenShift::
+
By default, Flex Gateway running on Kubernetes includes a liveness probe configured in the Helm chart. The liveness probe automatically runs `flexctl probe --check=liveness` at an interval of 10 seconds and restarts non-operational pods after 5 failed tests.
+
The liveness probe is configured by default with the following values:
+
[source,helm]
----
livenessProbe:
 exec:
   command:
   - flexctl
   - probe
   - --check=liveness
 initialDelaySeconds: 10
 periodSeconds: 10
 failureThreshold: 5
 timeoutSeconds: 1
----
+
[cols="1,2"]
|===
| Parameter | Description
| `exec.command` | The liveness probe command
| `initialDelaySeconds` | The time in seconds to wait after startup before running the first liveness probe
| `periodSeconds` | The period in seconds between each liveness probe
| `failureThreshold` | The number of failed liveness probes before the Kubernetes pod is restarted
| `timeoutSeconds` | The time in seconds before the liveness probe times out
|===
+
To modify the default parameters, you must update your Helm chart. You can modify these parameters during or after the initial installation of the Helm chart. For more information about how to update a Helm chart, see xref:flex-gateway-k8-change-helm-settings.adoc[].

Docker, Podman, and Linux::
+
For Docker and Linux deployments, Flex Gateway does not include a pre-configured default liveness probe. However, you can still run the the liveness probe command manually, or configure it for automated use with third-party services. Besides the Kubernetes liveness probe, MuleSoft does not provide support for third-party liveness probes.
+
One method of running the liveness probe command with Docker is to configure `HEALTHCHECK` in your `docker run` command. For more information, see https://docs.docker.com/engine/reference/run/#healthcheck[Docker run HEALTHCHECK^].
====

== See Also

* https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/[Configure Liveness, Readiness, and Startup Probes^].
* xref:policies-included-health-check.adoc[]