= Viewing Logs in Runtime Manager
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: runtime-manager::flex-gateway-monitoring.adoc, flex-view-logs-in-monitoring.adoc
:imagesdir: ../assets/images

Use Runtime Manager to view the runtime logs of your Flex Gateway. Runtime Manager enables you to search for keywords within the logs and to filter by *Replica*, *Time Range*, and *Log Level*. 

Access logs are not visible in Runtime Manager. To learn more about access logs, see xref:flex-conn-message-log.adoc[].

Runtime Manager stores up to 100 MB of logs per Flex Replica for 30 days. Runtime Manager automatically purges logs that go beyond 100 MB per Flex Replica. If you need more storage, you can either use a third-party service or sign up for the Anypoint Integration Advanced package or a Titanium subscription to Anypoint Platform. 

To access Flex Gateway runtime logs in Runtime Manager:

. From Anypoint Platform, select *Runtime Manager*.
. Select *Flex Gateway* in the navigation menu.
. Click the name of the Flex Gateway whose logs you want to view.
. Click *Logs*.

== See Also

* xref:flex-conn-message-log.adoc[]
* xref:flex-troubleshoot-debug-logs.adoc[]


