= Basic Authentication: Simple Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:keywords: basic authentication, api gateway, flex gateway, gateway, policy

[width="100%", cols="5,15"]
|===
>s| Policy Name | Basic Authentication: Simple
>s|Summary      | Allows access based on the basic authorization mechanism, with a single user-password
>s|Category | Security
>s|First Flex Gateway version available | v1.0.0
.1+>.^s| Returned Status Codes
| 401 - Unauthorized or invalid client application credentials in HTTP or RAML APIs
| | 403 - Forbidden: Authentication succeeded, but access is denied.

| | 500 - Unauthorized or invalid client application credentials in WSDL API using SOAP 1.1
|===

== Summary

The Basic Authentication: Simple policy protects the API by enabling automatic injection of Basic Authentication credentials into outbound requests. This policy ensures that requests sent from Flex Gateway to an upstream service include the correct authentication headers.

The policy follows https://tools.ietf.org/html/rfc7617[basic HTTP authentication standards^].

When an error is encountered, the policy returns an "WWW-Authenticate" HTTP header field.

== Configuring Policy Parameters

=== Flex Gateway Local Mode

In Flex Gateway Local Mode, you apply the Basic Authentication: Simple policy to your API via declarative configuration files. Refer to the following policy definition and table of parameters:

----
- policyRef:
    name: http-basic-authentication-flex
  config:
    username: <string> // REQUIRED
    password: <string> // REQUIRED
----

[%header%autowidth.spread,cols="a,a,a,a"]
|===
|Parameter | Required or Optional | Default Value | Description

| `username`
| Required
| N/A
| A base-64 encoded string

| `password`
| Required
| N/A
| A base-64 encoded string

|===

==== Resource Configuration Example

----
- policyRef:
    name: http-basic-authentication-flex
  config:
    username: chris
    password: admin
----

=== Flex Gateway Connected Mode

When you apply the Basic Authentication: Simple policy to an API, a request to that API must contain the following header:

----
Authorization: Basic <username:password>
----

The `username:password` value must be a base64-encoded string. For example on a Mac OS X or Linux system, the username and password requirement is implemented as:

`echo -n '<Client Id>:<Client Secret>' | base64`
