= Shared Responsibility
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

The successful operation of Anypoint Flex Gateway is a responsibility shared between you and MuleSoft. 

== MuleSoft Responsibility

MuleSoft is responsible for:

* Flex Gateway (including the agent, the Envoy package, and the Fluentbit package.)
* Providing and supporting a base Helm chart for the installation of Flex Gateway on a Kubernetes cluster.
* Providing and supporting an online Docker image registry.
* Providing and supporting an online package repository for installation on Ubuntu and Debian.

== Your Responsibility

When running on any target, you are responsible for:

* Maintaining connectivity to the Anypoint Control Plane.
* Not running third-party software that interferes with normal Flex Gateway operation. For example: antivirus, DPI, or application security systems. 
+
For security tool requirements, vendors and security experts that support Kubernetes are recommended.

When running in Kubernetes, you are responsible for:

* Adapting the base Helm chart to particular needs.
* Managing the Kubernetes cluster, including: 
** Ingress controller and external load balancing
** Customizations to Ingress resources
** Log forwarding
** Monitoring
** Network ports, NAT gateways, and proxies
** Container runtime and networking
** Provisioning and management of the Kubernetes environment, which requires:
*** Your IT team to provision and manage the infrastructure
*** Your network team to configure allowed ports and proxy settings
*** Your security team to verify compliance and obtain security certificates

You can view usage reports for Flex Gateway to get insight into your monthly usage. See xref:general::usage-reports.adoc[Viewing Usage Reports] for more. 
