// partial for registering in connected/local modes with a username and password, connected app, or a token, in a Docker container or as a Linux service

// tag::prerequisites-heading[]

== Before You Begin

Before registering Flex Gateway, you must complete the following tasks:
// end::prerequisites-heading[]
// tag::app-prerequisites[] 

* xref:service-mesh::obtain-connected-apps-credentials.adoc[Configure a Connected App]
** Include the following scopes:
*** Read Servers
*** Manage Servers
*** View Organization
** Save the *Id* and *Secret* of the Connected app you configure.

// end::app-prerequisites[]
// tag::prerequisites[]

* xref:flex-install.adoc[Install a Flex Gateway]
* Request _Manage Servers_ and _Read Servers_ permissions in Runtime Manager from your Anypoint Platform admin
* Collect the following information from your Anypoint Platform instance: 
** The *Organization ID* for the organization where you want to run Flex Gateway
+
See xref:access-management::organization.adoc#find-your-organization-id[Find your Organization ID] for more information on how to find your Organization ID.

// end::prerequisites[]
// tag::environment-prerequisites[]

** The *Environment ID* for the environment where you want to run Flex Gateway
+
See xref:api-manager::latest-overview-concept#what-api-manager-looks-like[What API Manager Looks Like]
for more information on how to find your Environment ID.

// end::environment-prerequisites[]
// tag::token-prerequisites[]

** The registration *token* for the environment in Anypoint Platform where you want to run Flex Gateway
+
Navigate to Runtime Manager, select *Flex Gateway* in the left navigation, and click *Add Gateway*
to generate set of instructions that includes a command block with the registration token.

// end::token-prerequisites[]
// tag::user-prerequisites[]

** The *Username* and *Password* of a user with _Read Servers_ and _Manage Servers_ permissions for Runtime Manager

// end::user-prerequisites[]
// tag::app-docker-heading[]
== Register and Run with a Connected App in a Docker Container
// end::app-docker-heading[]
// tag::user-docker-heading[]
== Register and Run with a Username and Password in a Docker Container
// end::user-docker-heading[]
// tag::token-docker-heading[]
== Register and Run with a Token in a Docker Container
// end::token-docker-heading[]
// tag::app-linux-heading[]
== Register and Run with a Connected App as a Linux Service
// end::app-linux-heading[]
// tag::user-linux-heading[]
== Register and Run with a Username and Password as a Linux Service
// end::user-linux-heading[]
// tag::token-linux-heading[]
== Register and Run with a Token as a Linux Service
// end::token-linux-heading[]
// tag::app-k8s-heading[]
== Register and Run with a Connected App as a Kubernetes Ingress Controller
// end::app-k8s-heading[]
// tag::user-k8s-heading[]
== Register and Run with a Username and Password as a Kubernetes Ingress Controller
// end::user-k8s-heading[]
// tag::token-k8s-heading[]
== Register and Run with a Token as a Kubernetes Ingress Controller
// end::token-k8s-heading[]
// tag::reg-command-intro[]
To register a Flex Gateway with Anypoint Platform you must enter the registration command and then the start command. Each command includes information specific to your Anypoint Platform instance and *must be updated before* executing. See <<Before You Begin>> for more information on how to find the information you will need.
//end::reg-command-intro[]
// tag::k8s-reg-command-intro[]
To register a Flex Gateway with Anypoint Platform as a Kubernetes ingress controller you must enter the registration command and then install the flex-gateway Helm chart into the gateway namespace. Each command includes information specific to your Anypoint Platform instance and *must be updated before* executing. See <<Before You Begin>> for more information on how to find the information you will need.
// end::k8s-reg-command-intro[] 
//tag::sub-coll-info[]

=== Substitute Collected Information

Before executing the registration command, replace the following sample information with the information you collected:

//end::sub-coll-info[] 
// tag::user-replace-content[]

* `--username` = the username for an Anypoint Platform user with _Read Servers_ and _Manage Servers_ permissions for Runtime Manager
* `--password` = the password for an Anypoint Platform user with _Read Servers_ and _Manage Servers_ permissions for Runtime Manager
// end::user-replace-content[]
// tag::token-replace-content[]
* `--token` = the registration token for your environment in Anypoint Platform
// end::token-replace-content[]
// tag::app-replace-content[]

* `--client-id` = the Id for the Connected App you configured in Access Management
* `--client-secret` = the Secret for the Connected App you configured in Access Management

// end::app-replace-content[]
// tag::environment-replace-content[]

* `--environment` = the Environment Id for the environment in Anypoint Platform where you want the Flex Gateway to run

// end::environment-replace-content[]
// tag::replace-content[]

* `--organization` = your Organization ID in Anypoint Platform
* `my-gateway` = the name you want to assign to this Flex Gateway instance or replica

// end::replace-content[]
// tag::reg-command-heading[]

=== Registration Command

After replacing the sample content, register your Flex Gateway by executing the following command: 

// end::reg-command-heading[]
// tag::reg-command-1[]

[source,ssh,subs=attributes+]
----
# end::reg-command-1[]
# tag::docker-reg-command[]
docker run --entrypoint flexctl -w /registration -v $(pwd):/registration mulesoft/flex-gateway \
register \
# end::docker-reg-command[]
# tag::linux-reg-command[]
flexctl register \
# end::linux-reg-command[]
# tag::user-reg-command[]
--username=<your-username> \
--password=<your-password> \
# end::user-reg-command[]
# tag::app-reg-command[]
--client-id=<your-connected-app-client-id> \
--client-secret=<your-connected-app-client-secret> \
# end::app-reg-command[]
# tag::environment-reg-command[]
--environment=<your-environment-id> \
# end::environment-reg-command[]
# tag::token-reg-command[]
--token=<your-registration-token> \
# end::token-reg-command[]
# tag::connected-reg-command[]
--connected=true \
# end::connected-reg-command[]
# tag::reg-command-2[]
--organization=<your-org-id> \
my-gateway
----

NOTE: If you are in Europe you will need to add the `--anypoint-url=https://eu1.anypoint.mulesoft.com` flag
to your command.

// end::reg-command-2[]
// tag::after-reg[]

You should also see three new files where you executed the command, similar to the following: 

* `6eb79785-c2f0-4e06-b574-8a030a321d74.conf`
* `6eb79785-c2f0-4e06-b574-8a030a321d74.key`
* `6eb79785-c2f0-4e06-b574-8a030a321d74.pem`

IMPORTANT: These generated files are credentials for you to connect your Flex Gateway. If you lose them you
can no longer connect your Flex Gateway.

// end::after-reg[]
//tag::after-reg-2[]
Determine the path where these files live by using the command, `pwd`, then save the path and the UUID,
or name, of the `.conf` file for later use. For example, `/Users/jane/flex-gateway/6eb79785-c2f0-4e06-b574-8a030a321d74.conf`.
//end::after-reg-2[]
//tag::linux-after-reg[]
Determine the path for these files, then save the path and the UUID, or name, of the files. For example, `/Users/jane/flex-gateway/6eb79785-c2f0-4e06-b574-8a030a321d74`. 

Then update the permissions of the files: 
[source]
----
chmod 644 <path-and-uuid-of-registration-files>.*
----
//end::linux-after-reg[]
//tag::k8s-after-reg[]
You will need the UUIDs, or the filenames without the file type, of these files to create your Kubernetes secret later.
//end::k8s-after-reg[]
// tag::connected-after-reg[]

You should also see your new Flex Gateway in Runtime Manager after clicking *Flex Gateway* in the left navigation. 
The gateway's status is disconnected for now. You need to start the gateway to connect it.
// end::connected-after-reg[]
// tag::start-command[]

=== Start Command

Before executing the start command below, update the placeholder text with the
absolute path to the directory with the `.conf` file, and the UUID of the `.conf` file.
Additionally, update the FLEX_NAME to the name you want to assign to your Flex Replica.

[source,ssh,subs=attributes+]
----
docker run --rm \
-v <absolute-path-to-directory-with-conf-file>/:/etc/flex-gateway/rtm \
-p 8080:8080 \
-e FLEX_RTM_ARM_AGENT_CONFIG=/etc/flex-gateway/rtm/<UUID-of-your-file>.conf \
-e FLEX_NAME=<name-for-flex-replica> \
mulesoft/flex-gateway
----
// end::start-command[]
// tag::start-command-local[]

=== Start Command

Before executing the start command below, update the placeholder text with the absolute path to the directory with the `.conf` file, and the UUID of the `.conf` file. Additionally, update the absolute path to the directory where your Flex Gateway configuration files will reside and the FLEX_NAME with the name you want to assign to your Flex Replica. 

[source,ssh,subs=attributes+]
----
docker run --rm \
-v <absolute-path-to-directory-with-conf-file>/:/etc/flex-gateway/rtm \
-v <absolute-path-to-directory-with-gateway-configuration-files>/:/usr/local/share/mulesoft/flex-gateway/conf.d \
-p 8080:8080 \
-e FLEX_RTM_ARM_AGENT_CONFIG=/etc/flex-gateway/rtm/<UUID-of-your-file>.conf \
-e FLEX_NAME=<name-for-flex-replica> \
mulesoft/flex-gateway
----

The Docker logs should include this line:

[source,ssh]
----
[flex-gateway-envoy][info] all dependencies initialized. starting workers
----
// end::start-command-local[]
// tag::create-config-folder-file[]

=== Create Configuration Folder and File

Before executing the start command, you must create a  configuration directory and file and edit the contents of that file.

First create the configuration directory using the following command: 

[source]
----
sudo mkdir /etc/systemd/system/flex-gateway-agent.service.d/
----

Afterwards, create a configuration file within that directory and name it `env.conf`.

Finally, edit the file with vim using the following command: 

[source]
----
sudo vi env.conf
----

// end::create-config-folder-file[]
// tag::config-content[]

=== Add Configuration Content

Add the content below to the `env.conf` file, after replacing the following sample content with your own: 

*  `<path-and-uuid-of-conf-file>.conf` = the path and UUID of the `.conf` file that was created when you registered the gateway
* `<name-for-flex-replica>` = a name for your Flex Replica

[source,subs=attributes+]
----
[Service]

Environment=FLEX_RTM_ARM_AGENT_CONFIG=<path-and-uuid-of-conf-file>.conf
Environment=FLEX_NAME=<name-for-flex-replica>
----

After you have added the content to the `env.conf` file, save the file with ESC + `:wq`.
// end::config-content[]
// tag::linux-start-commands[]

=== Start Commands

Reload the `env.conf` configuration with the following command:

[source]
----
sudo systemctl daemon-reload
----

Start Flex Gateway with the following command: 

[source]
----
sudo systemctl start flex-gateway
----

Verify that the Flex Gateway service is running successfully:

[source,ssh]
----
systemctl list-units flex-gateway*
----

You should see a list of services. Flex Gateway is successfully running if each service has a status of `active`.

[source,ssh]
----
  UNIT                              LOAD   ACTIVE SUB     DESCRIPTION
  flex-gateway-fluent-reloader.path loaded active waiting flex-gateway-fluent-reloader.path
  flex-gateway-agent.service        loaded active running flex-gateway-agent.service
  flex-gateway-envoy.service        loaded active running flex-gateway-envoy.service
  flex-gateway-fluent.service       loaded active running flex-gateway-fluent.service
  flex-gateway.service              loaded active exited  Application
----

// end::linux-start-commands[]
//tag::k8s-install-helm-chart[]

=== Install Helm Chart into the Namespace

. Create the namespace in which Flex Gateway will be installed: 
+
[source,kubernetes]
----
kubectl create namespace gateway
----

. Create a Kubernetes secret using the UUIDs from the files generated during registration:
+
[source,kubernetes]
----
kubectl -n gateway create secret generic <UUID-of-your-file> \
--from-file=platform.conf=<UUID-of-your-file>.conf \
--from-file=platform.key=<UUID-of-your-file>.key \
--from-file=platform.pem=<UUID-of-your-file>.pem
----

. Add the Flex Gateway Helm repository:
+
[source,kubernetes]
----
helm repo add flex-gateway https://flex-packages.anypoint.mulesoft.com/helm
----

. Update the Helm repository using the following command:
+
[source,kubernetes]
----
helm repo up
----

. Using Ingress, install the *flex-gateway* Helm chart into the *gateway* namespace. Specify the UUID from the filenames created for creating the Kubernetes secret. 
+
[source,kubernetes]
----
helm -n gateway upgrade -i --wait ingress flex-gateway/flex-gateway \
--set registerSecretName=<UUID-of-your-file> \
--devel
----
+
The command returns something similar to the following: 
+
[source,text]
----
NAME: ingress
LAST DEPLOYED: Tue Oct 19 13:08:07 2021
NAMESPACE: gateway
STATUS: deployed
REVISION: 1
TEST SUITE: None
----

. Verify *apiinstances* was created during installation: 
+
[source,text]
----
kubectl -n gateway get apiinstances
---- 
+
The command returns output similar to the following: 
+
[source,text]
----
NAME            ADDRESS
ingress-http    http://0.0.0.0:80
ingress-https   http://0.0.0.0:443
----

//end::k8s-install-helm-chart[]
//tag::gateway-connected[]
Now if you check in Runtime Manager after clicking *Flex Gateway* in the left navigation, your gateway's status is connected. You may need to refresh the page.

Currently, you cannot unregister or delete Flex Replicas from the Runtime Manager UI. If a Flex Replica
in Connected Mode is stopped it will be removed from the UI in Runtime Manager after 30 days. Otherwise,
it will appear in the Runtime Manager UI even if it is no longer running.

//end::gateway-connected[]
//tag::helm-chart-options[]

=== Helm Chart Configuration Options

The following table describes the configurable options of the Flex Gateway Ingress Controller Helm chart.

[cols="a,a,a"]
|===
|Parameter |Default Value |Description

|`image.pullPolicy`
|ifNotPresent
|The https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy[pull policy^] for the Ingress Controller image.

Possible values: `ifNotPresent`, `Always`, `Never`

|`image.pullSecretName`
|""
|The name of the secret that contains Docker registry credentials. The secret must exist in the same namespace as the helm release.

|`replicaCount`
|1
|The number of Ingress Controller deployment replicas

|`autoscaling.enabled`
|false
|Boolean indicating if the Horizontal Pod Autoscaler (HPA) is enabled

|`autoscaling.minReplicas`
|2
|The minimum number of replicas that the scaler is allowed to create

|`autoscaling.maxReplicas`
|11
|The maximum number of replicas that the scaler is allowed to create

|`autoscaling.targetCPUUtilizationPercentage`
|50
|The average CPU usage percentage of all deployed pods

|`autoscaling.targetMemoryUtilizationPercentage`
|50
|The average memory usage percentage of all deployed pods

|`resources.limits.cpu`
|500m
|CPU resource limits in millicores

|`resources.limits.memory`
|256mi
|Memory resource limits

|`service.enabled`
|true
|Boolean indicating if a service to expose Ingress Controller pods is created

|`service.type`
|LoadBalancer
|The https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types[type^] of Ingress Controller service to create.

Possible values: `ClusterIP`, `NodePort`, `LoadBalancer`, `ExternalName`

|`service.http.enabled`
|true
|Boolean indicating if the HTTP port should be enabled for the Ingress Controller service

|`service.http.port`
|80
|The Ingress Controller service HTTP port

|`service.https.enabled`
|true
|Boolean indicating if the HTTPS port should be enabled for the Ingress Controller service

|`service.http.port`
|443
|The Ingress Controller service HTTPS port

|`registerSecretName`
|null
|The name of the secret containing the registration files

|===
//end::helm-chart-options[]
