//tag::add-flex-rep-byb[]
== Before You Begin

Before getting started, ensure you have completed the following tasks:

* xref:flex-install.adoc[Install a Flex Gateway]
//end::add-flex-rep-byb[]
//tag::add-flex-rep-byb-conn[]
* xref:flex-conn-reg-run.adoc[Register and Run in Connected Mode]
//end::add-flex-rep-byb-conn[]
//tag::add-flex-rep-byb-local[]
* xref:flex-local-reg-run.adoc[Register and Run in Local Mode]
//end::add-flex-rep-byb-local[]
//tag::add-flex-rep1[]

== Add a Flex Replica as a Linux Service

Adding a Flex Replica as a Linux Service includes the following tasks:

* Copy and paste the three registration files created during registration to your Linux machine or VM.
* Create the configuration folder and file and edit the contents of the file
* Run the Flex Gateway start command.

=== Copy the Registration Files

Copy the three registration files to a directory on your Linux machine or VM. For example: 

* `6eb79785-c2f0-4e06-b574-8a030a321d74.conf`
* `6eb79785-c2f0-4e06-b574-8a030a321d74.key`
* `6eb79785-c2f0-4e06-b574-8a030a321d74.pem`

Determine the path where these files live by using the command, `pwd`, then save the path and the UUID,
or name, of the `.conf` file for later use. For example, `/Users/jane/flex-gateway/6eb79785-c2f0-4e06-b574-8a030a321d74.conf`.

//end::add-flex-rep1[]
//tag::add-flex-rep2[]

Now if you check in Runtime Manager after clicking *Flex Gateway* in the left navigation, your Flex Gateway will have an additional replica listed. You may need to refresh the page. 

Currently, you cannot unregister or delete Flex Replicas. If a Flex Replica is stopped it will be removed from the UI in
Runtime Manager after 30 days. Otherwise, it will appear in the Runtime Manager UI even if it is no longer running.

//end::add-flex-rep2[]