// partial for registering in connected/local modes with a username and password, connected app, or a token, in a Docker container or as a Linux service

// tag::prerequisites-heading[]

== Before You Begin

Before registering Flex Gateway, you must complete the following tasks:
// end::prerequisites-heading[]
// tag::app-prerequisites[] 

* link:https://docs.mulesoft.com/service-mesh/1.2/obtain-connected-apps-credentials[Configure a Connected App]
** Include the following scopes:
*** Read Gateways
*** Manage Gateways
*** View Organization
** Save the *Id* and *Secret* of the Connected app you configure.

// end::app-prerequisites[]
// tag::prerequisites[]

* xref:flex-install.adoc[Install a Flex Gateway]
* _Manage Gateways_ and _Read Gateways_ permissions in Runtime Manager
* Collect the following information from your Anypoint Platform instance: 
** The *Organization ID* for the organization where you want to run Flex Gateway
+
See link:https://docs.mulesoft.com/access-management/organization#find-your-organization-id[Find your Organization ID] for more information on how to find your Organization ID.

// end::prerequisites[]
// tag::environment-prerequisites[]

** The *Environment ID* for the environment where you want to run Flex Gateway
+
See xref:api-manager::latest-overview-concept#what-api-manager-looks-like[What API Manager Looks Like]
for more information on how to find your Environment ID.

// end::environment-prerequisites[]
// tag::token-prerequisites[]

** The registration *token* for the environment in Anypoint Platform where you want to run Flex Gateway
+
Navigate to Runtime Manager, select *Flex Gateway* in the left navigation, and click *Add Gateway*
to generate set of instructions that includes a command block with the registration token.

// end::token-prerequisites[]
// tag::user-prerequisites[]

** The *Username* and *Password* of a user with _Read Gateways_ and _Manage Gateways_ permissions for Runtime Manager

// end::user-prerequisites[]
// tag::app-docker-heading[]
== Register and Run with a Connected App in a Docker Container
// end::app-docker-heading[]
// tag::user-docker-heading[]
== Register and Run with a Username and Password in a Docker Container
// end::user-docker-heading[]
// tag::token-docker-heading[]
== Register and Run with a Token in a Docker Container
// end::token-docker-heading[]
// tag::app-linux-heading[]
== Register and Run with a Connected App as a Linux Service
// end::app-linux-heading[]
// tag::user-linux-heading[]
== Register and Run with a Username and Password as a Linux Service
// end::user-linux-heading[]
// tag::token-linux-heading[]
== Register and Run with a Token as a Linux Service
// end::token-linux-heading[]
// tag::reg-command-intro[]
To register a Flex Gateway with Anypoint Platform you must enter the registration command and then the start command. Each command includes information specific to your Anypoint Platform instance and *must be updated before* executing. See <<Before You Begin>> for more information on how to find the information you will need.

=== Replace Sample Content

Before executing the registration command, replace the following sample content with your own:

// end::reg-command-intro[] 
// tag::user-replace-content[]

* `--username` = the username for an Anypoint Platform user with _Read Gateways_ and _Manage Gateways_ permissions for Runtime Manager
* `--password` = the password for an Anypoint Platform user with _Read Gateways_ and _Manage Gateways_ permissions for Runtime Manager
// end::user-replace-content[]
// tag::token-replace-content[]
* `--token` = the registration token for your environment in Anypoint Platform
// end::token-replace-content[]
// tag::app-replace-content[]

* `--client-id` = the Id for the Connected App you configured in Access Management
* `--client-secret` = the Secret for the Connected App you configured in Access Management

// end::app-replace-content[]
// tag::environment-replace-content[]

* `--environment` = the Environment Id for the environment in Anypoint Platform where you want the Flex Gateway to run

// end::environment-replace-content[]
// tag::replace-content[]

* `--organization` = your Organization ID in Anypoint Platform
* `--anypoint-url` = your Anypoint Platform instance base URL 
* `my-gateway` = the name you want to assign to this Flex Gateway instance

// end::replace-content[]
// tag::reg-command-heading[]

=== Registration Command

After replacing the sample content, register your Flex Gateway by executing the following command: 

// end::reg-command-heading[]
// tag::reg-command-1[]

[source,ssh,subs=attributes+]
----
# end::reg-command-1[]
# tag::docker-reg-command[]
docker run --entrypoint flexctl -w /registration -v "$(pwd)":/registration mulesoft/flex-gateway:{gateway-ver-var} \
register \
# end::docker-reg-command[]
# tag::linux-reg-command[]
flexctl register \
# end::linux-reg-command[]
# tag::user-reg-command[]
--username=<your-username> \
--password=<your-password> \
# end::user-reg-command[]
# tag::app-reg-command[]
--client-id=<your-connected-app-client-id> \
--client-secret=<your-connected-app-client-secret> \
# end::app-reg-command[]
# tag::environment-reg-command[]
--environment=<your-environment-id> \
# end::environment-reg-command[]
# tag::token-reg-command[]
--token=<your-registration-token> \
# end::token-reg-command[]
# tag::connected-reg-command[]
--connected=true \
# end::connected-reg-command[]
# tag::reg-command-2[]
--organization=<your-org-id> \
--anypoint-url=https://<your-instance>.anypoint.mulesoft.com \
my-gateway
----
// end::reg-command-2[]
// tag::after-reg[]

You should also see three new files where you executed the command, similar to the following: 

* `6eb79785-c2f0-4e06-b574-8a030a321d74.conf`
* `6eb79785-c2f0-4e06-b574-8a030a321d74.key`
* `6eb79785-c2f0-4e06-b574-8a030a321d74.pem`

Determine the path where these files live by using the command, `pwd`, then save the path and the UUID,
or name, of the `.conf` file for later use. For example, `/Users/jane/flex-gateway/6eb79785-c2f0-4e06-b574-8a030a321d74.conf`.
// end::after-reg[]
// tag::connected-after-reg[]
You should also see your new Flex Gateway in Runtime Manager after clicking *Flex Gateway* in the left navigation. 
The gateway's status is disconnected for now. You need to start the gateway to connect it.
// end::connected-after-reg[]
// tag::start-command[]

=== Start Command

Before executing the start command below, update the placeholder text with the
absolute path to the directory with the `.conf` file, and the UUID of the `.conf` file.
Additionally, update the FLEX_NAME to the name you want to assign to your Flex Replica.

[source,ssh,subs=attributes+]
----
docker run --rm \
-v <absolute-path-to-directory-with-conf-file>/:/etc/flex-gateway/rtm \
-p 8081:8081 \
-e FLEX_RTM_ARM_AGENT_CONFIG=/etc/flex-gateway/rtm/<UUID-of-your-file>.conf \
-e FLEX_NAME=<name-for-flex-replica>
mulesoft/flex-gateway:{gateway-ver-var}
----
// end::start-command[]
// tag::start-command-local[]

=== Start Command

Before executing the start command below, update the placeholder text with the absolute path to the directory with the `.conf` file, and the UUID of the `.conf` file. Additionally, update the absolute path to the directory where your Flex Gateway configuration files will reside and the FLEX_NAME with the name you want to assign to your Flex Replica. 

[source,ssh,subs=attributes+]
----
docker run --rm \
-v <absolute-path-to-directory-with-conf-file>/:/etc/flex-gateway/rtm \
-v <absolute-path-to-directory-with-gateway-configuration-files>/:/usr/local/share/mulesoft/flex-gateway/conf.d \
-p 8081:8081 \
-e FLEX_RTM_ARM_AGENT_CONFIG=/etc/flex-gateway/rtm/<UUID-of-your-file>.conf \
-e FLEX_NAME=<name-for-flex-replica>
mulesoft/flex-gateway:{gateway-ver-var}
----

The Docker logs should include this line:

[source,ssh]
----
[flex-gateway-envoy][info] all dependencies initialized. starting workers
----
// end::start-command-local[]
// tag::create-config-folder-file[]

=== Create Configuration Folder and File

Before executing the start command, you must create a  configuration directory and file and edit the contents of that file.

First create the configuration directory using the following command: 

[source]
----
sudo mkdir /etc/systemd/system/flex-gateway-agent.service.d/
----

Afterwards, create a configuration file within that directory and name it `env.conf`.

Finally, edit the file with vim using the following command: 

[source]
----
sudo vi env.conf
----

// end::create-config-folder-file[]
// tag::config-content[]

=== Add Configuration Content

Add the content below to the `env.conf` file, after replacing the following sample content with your own: 

*  `<path-and-uuid-of-conf-file>.conf` = the path and UUID of the `.conf` file that was created when you registered the gateway
* `<name-for-flex-replica>` = a name for your Flex Replica

[source,subs=attributes+]
----
[Service]

Environment=FLEX_RTM_ARM_AGENT_CONFIG=<path-and-uuid-of-conf-file>.conf
Environment=FLEX_NAME=<name-for-flex-replica>
----

After you have added the content to the `env.conf` file, save the file with ESC + `:wq`.
// end::config-content[]
// tag::linux-start-commands[]

=== Start Commands

Reload the `env.conf` configuration with the following command:

[source]
----
sudo systemctl daemon-reload
----

Start Flex Gateway with the following command: 

[source]
----
sudo systemctl start flex-gateway
----

Verify that the Flex Gateway service is running successfully:

[source,ssh]
----
systemctl list-units flex-gateway*
----

You should see a list of services. Flex Gateway is successfully running if each service has a status of `active`.

[source,ssh]
----
  UNIT                              LOAD   ACTIVE SUB     DESCRIPTION
  flex-gateway-fluent-reloader.path loaded active waiting flex-gateway-fluent-reloader.path
  flex-gateway-agent.service        loaded active running flex-gateway-agent.service
  flex-gateway-envoy.service        loaded active running flex-gateway-envoy.service
  flex-gateway-fluent.service       loaded active running flex-gateway-fluent.service
  flex-gateway.service              loaded active exited  Application
----

// end::linux-start-commands[]
// tag::gateway-connected[]
Now if you check in Runtime Manager after clicking *Flex Gateway* in the left navigation, your gateway's status is connected. You may need to refresh the page.
// end::gateway-connected[]
