= Configuring Timeouts in Connected Mode
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:page-mode: conn
:page-aliases: flex-conn-timeout.adoc

include::partial$timeout-configuration.adoc[tags=timeout-types]

You can configure these timeouts in Connected Mode via:

* Runtime Manager runtime configurations: Applies to all API instances in the gateway.
* Environment variables: Applies to all API instances and is the most permanent configuration option.
* Configuration YAML resource: Applies to all API instances and is easy to adjust.
* Policy: Applies to one API instance or upstream and provides granular control.

include::partial$configuration-precedence.adoc[tags=precedence]

. *Policy*: A policy applied to the API instance.
. *Runtime Manager runtime configuration or Configuration resource*: Used if no policy value is set.
. *Environment variable*: Used if no Runtime Manager or Configuration resource value is set.
. *Built-in default*: Used if none of the other values is set.

include::partial$configuration-precedence.adoc[tags=precedence-details]

Runtime Manager runtime configurations and environment variables don't synchronize. Changing a value in Runtime Manager doesn't update the corresponding `FLEX_*` environment variable on the gateway. Because the Runtime Manager value takes precedence, the environment variable has no effect on that setting while the Runtime Manager value is set.

include::partial$timeout-configuration.adoc[tags=timeout-runtime-manager]

include::partial$timeout-configuration.adoc[tags=timeout-configuration-env-var]

include::partial$timeout-configuration.adoc[tags=timeout-configuration-yaml]

include::partial$timeout-configuration.adoc[tags=timeout-configuration-policies]
