= Agent Connection Telemetry Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:keywords: api gateway, flex gateway, gateway, policy, agent, telemetry, agent connection, A2A, MCP

[width="100%", cols="5,15"]
|===
>s| Policy Name | Agent Connection Telemetry
>s|Summary  | Tracks the number of requests made to agent or MCP server instances
>s|Category | A2A and MCP
>s|First Omni Gateway version available | 1.11.0
>s|Release Notes| xref:release-notes::gateway/policies/agent-connection-telemetry-release-notes.adoc[]
^s| Returned Status Codes | No return codes exist for this policy.
|===

== Summary

The Agent Connection Telemetry policy tracks the number of requests and what source makes the request to agent or MCP server instance. 

To track the source of the request, the policy uses a DataWeave expression to extract an identification value from a request header. By default, the policy extracts the `X-AGENT-ID` header. The `X-AGENT-ID` header contains the Mulesoft instance ID.

To track the requests, the policy uses the `mulesoft_agent_connection_count(source, destination)` metric. Where `source` is the identification value extracted from the request header and `destination` is the agent or MCP server instance ID. Use Anypoint Monitoring to view the metric.

If the policy can't extract the identification header, the policy doesn't block or track the request.

NOTE: The Agent Connection Telemetry policy is applied by default to all agent and MCP server instances created using Agent Fabric.

== Configure Policy Parameters

include::partial$policy-title-headers.adoc[tag=configFileTitleOnly]

The Agent Connection Telemetry policy isn't supported in Local Mode.

include::partial$policy-title-headers.adoc[tag=ui]

[%header%autowidth.spread,cols="a,a"]
|===
| Element | Description
| Source Agent ID | DataWeave expression to extract the source identification value from the request header. By default, the `#[attributes.headers['X-AGENT-ID']]` expression extracts the Mulesoft instance ID.
|===

