= Custom Policies
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: api-manager::policies-custom-landing-page.adoc, api-manager::policies-custom-overview.adoc, policies::policies-custom-overview.adoc

include::partial$pdk-banner.adoc[tag="pdk"]

Policies enforce regulations to help manage security, control traffic, and improve API adoption. For example, a policy can control authentication, access, and service level agreements (SLAs). You can create custom policies based on your specific business requirements and apply them to APIs to extend existing functionality or define new ones.

The workflow for creating custom policies for Omni Gateway is done in Exchange. The policy is then available to be applied to an API in Anypoint API Manager.

For more information, refer to the following:

* xref:policies-custom-implement-rust.adoc[Implement an Omni Gateway Custom Policy in Rust]
* xref:policies-custom-getting-started.adoc[Publish an Omni Gateway Custom Policy]
* xref:local-deploy-custom-policy.adoc[Apply an Omni Gateway Custom Policy in Local Mode]
