= MCP Attribute-Based Access Control Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:keywords: api gateway, flex gateway, gateway, policy

[width="100%", cols="5,15"]
|===
>s| Policy Name | MCP Attribute-Based Access Control
>s|Summary      | Controls access to tools, resources, and prompts based on user information such as Tiers, IP, Headers, or Claims
>s|Category | MCP
>s|First Omni Gateway version available | v1.9.3
>s|Release Notes| xref:release-notes::gateway/policies/mcp-attribute-access-control-release-notes.adoc[]
>s| Returned Status Codes | 400 - Invalid token
|===

include::partial$mcp-version-support.adoc[]

== Summary

The MCP Attribute-Based Access Control policy controls access to server tools, resources, and prompts based on user information such as Tiers, IP, Headers, or Claims. Use the https://docs.cedarpolicy.com/[Cedar policy language] to define access rules.

This policy requires that another authentication policy be applied before the MCP Attribute-Based Access Control policy. For detailed guidance, see <<writing-cedar-rules>>.

== Configuring Policy Parameters

include::partial$policy-title-headers.adoc[tag=configFileTitleOnly]

The MCP Attribute-Based Access Control policy is not supported in Local Mode.

include::partial$policy-title-headers.adoc[tag=ui]

[%header%autowidth.spread,cols="a,a"]

|===
| Element | Description
| Rules | Rules to control access to tools, resources, and prompts written in the https://docs.cedarpolicy.com/[Cedar policy language].
| Cedar Expression | Cedar expression defining the access rule. For example: `permit(principal,action == Action::"tools/call` or `resource == Tool::"calculator");`. To learn more about the Cedar bindings provided by the requests, see <<writing-cedar-rules>>.
| Authentication Type | Type of authentication used by the authentication policy applied before this policy.
|===


[[writing-cedar-rules]]
== Writing Cedar Rules

You must apply either an included authentication policy or a custom authentication policy before the MCP Attribute-Based Access Control policy.

=== Included Authentication Policies

include::partial$policy-cedar-principal-attributes.adoc[]

== See Also

* xref:policies-mcp-access-control-together.adoc[]
* xref:policies-included-mcp-global-access.adoc[MCP Global Access]
* xref:policies-included-mcp-tool-mapping.adoc[MCP Tool Mapping]
