= Upstream Idle Timeout Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:keywords: basic authentication, api gateway, flex gateway, gateway, policy

[width="100%", cols="5,15"]
|===
>s| Policy Name | Stream Idle Timeout
>s|Summary | Sets the maximum idle duration for a stream between the Omni Gateway and an upstream service
>s|Category | Quality of Service
>s|First Omni Gateway version available | v1.9.0
>s|Release Notes| xref:release-notes::gateway/policies/outbound-upstream-idle-timeout-release-notes.adoc[]
^s| Returned Status Codes | 504 - Upstream request timeout
|===

== Summary
The Upstream Idle Timeout policy lets you set a maximum idle duration between requests for a stream between Omni Gateway and the upstream service. By applying the policy, you prevent idle connections from consuming resources while simultaneously allowing persistent connections to remain open. The timeout starts at the last request.

By default, all Omni Gateway API instances have an upstream idle timeout of 60 seconds. Apply the policy to override the default timeout.

== Configuring Policy Parameters

include::partial$policy-title-headers.adoc[tag=configFile]

----
- policyRef:
    name: idle-timeout-flex
  config:
    timeout: number // REQUIRED
----

[%header%autowidth.spread,cols="a,a,a,a"]
|===
|Parameter | Required or Optional | Default Value | Description

| `timeout`
| Required
| 60
| Time in seconds before Omni Gateway closes the connection.

|===

==== Resource Configuration Example

----
- policyRef:
    name: idle-timeout-flex
  config:
    timeout: 3
----

include::partial$policy-title-headers.adoc[tag=ui]

[%header%autowidth.spread,cols="a,a,a"]
|===
| Element | Description | Required
| Upstream idle timeout | Time in seconds before Omni Gateway closes the connection. | Yes
|===
