= Renewing Flex Gateway Registration
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Renewing the Flex Gateway registration is a straightforward process that ensures the continued operation of your applications. You renew registration by using the `flexctl` CLI.

To avoid potential disruptions, verify the success of the renewal process by using the `flexctl inspect` command.

This document describes two registration CLI commands:

* <<renewal-cli-overview,Registration Renewal CLI Command Overview>>
* <<inspection-cli-overview,Registration Inspection CLI Command Overview>>

== Before You Begin

* xref:flex-install.adoc[Download Flex Gateway].
+
To invoke the registration renewal `flexctl` command, download the latest version of Flex Gateway. It is not necessary to register and run this version of the gateway.

[[renewal-cli-overview]]
== Registration Renewal CLI Command Overview

Flex Gateway includes the following CLI command to renew registration:

----
flexctl registration renew
----

The command renews an existing Flex Gateway registration with Runtime Manager. For authentication, you specify *either* user credentials or connected appl credentials. Authentication with user credentials requires the `--username` and `--password` flags. Authentication with connected app credentials requires the `--client-id` and `--client-secret` flags.

Invoke the following `help` command for information about usage:

[source,ssh]
----
flexctl registration renew --help
----

For Flex Gateway running in a container, invoke `help` as part of the container `run` command:

[tabs]
====
Docker::
+
[source,ssh]
----
docker run --entrypoint flexctl mulesoft/flex-gateway renew --help
----

Podman::
+
[source,ssh]
----
podman run --entrypoint flexctl docker.io/mulesoft/flex-gateway renew --help
----
====

Refer to the following topics for more information about renewal command usage:

* <<renew-with-user-password,Renew Registration with User Credentials>>
* <<renew-with-conn-app,Renew Registration with Connected App Credentials>>

[[renew-with-user-password]]
== Renew Registration with User Credentials

Flex Gateway includes the following CLI command to renew registration using Anypoint Platform user credentials:

[source,ssh]
----
flexctl registration renew --username=<your-username> --password=<your-password> \
 <path-to-registration-file>
----

[NOTE]
====
The user must include _Read Servers_ and _Manage Servers_ permissions for Runtime Manager.
====

Replace `<path-to-registration-file>` with the path and filename of the existing `registration.yaml` file. Typically, the existing registration file is overwritten by the renewal process. You can optionally output the new registration file to a directory by using the `--output-directory` flag.

For Flex Gateway running in a container, invoke `renew` as part of the container `run` command:

[tabs]
====
Docker::
+
[source,ssh]
----
docker run --entrypoint flexctl \
-v "$(pwd)":/renew \
-v <path-to-registration-directory>:/registration \
-u $UID flex-gateway \
renew \
--username=<your-username> \
--password=<your-password> \
--output-directory=/renew \
/registration/<registration-filename>
----

Podman::
+
[source,ssh]
----
xx
----
====

Invoking the command results in the following output:

[source,text]
----
Starting registration renewal, please be patient.
Registration renewal completed, the configuration files were written in directory ".".
For security, modify the file permissions to restrict production scenario access to the user running flex.

Side effect: the following files were written in the current directory
registration.yaml
----

[[renew-with-conn-app]]
== Renew Registration with Connected App Credentials

Flex Gateway includes the following CLI command to renew registration using connected app credentials:

[source,ssh]
----
flexctl registration renew --client-id=<your-client-id> --client-secret=<your-client-secret> \
 <path-to-registration-file>
----

If you do not have a username or password for Anypoint Platform, you can configure connected apps via Anypoint Access Management:

* xref:access-management::connected-apps-developers.adoc#create-a-connected-app[Configure a Connected App]
** Include the following scopes:
*** Read Servers
*** Manage Servers
*** View Organization
** Save the *Id* and *Secret* of the Connected app you configure, then use these credentials in the `flexctl registration renew` command.

Replace `<path-to-registration-file>` with the path and filename of the existing `registration.yaml` file. Typically, the existing registration file is overwritten by the renewal process. You can optionally output the new registration file to a directory by using the `--output-directory` flag.

For Flex Gateway running in a container, invoke `renew` as part of the container `run` command:

[tabs]
====
Docker::
+
[source,ssh]
----
docker run --entrypoint flexctl \
-v "$(pwd)":/renew \
-v <path-to-registration-directory>:/registration \
-u $UID flex-gateway \
renew \
--client-id=<your-client-id> \
--client-secret=<your-client-secret> \
--output-directory=/renew \
/registration/<registration-filename>
----

Podman::
+
[source,ssh]
----
xx
----
====

Invoking the command results in the following output:

[source,text]
----
Starting registration renewal, please be patient.
Registration renewal completed, the configuration files were written in directory ".".
For security, modify the file permissions to restrict production scenario access to the user running flex.

Side effect: the following files were written in the current directory
registration.yaml
----

[[inspection-cli-overview]]
== Registration Inspection CLI Command Overview

Flex Gateway includes the following CLI command to inspect registration:

----
flexctl registration inspect
----

The command inspects your Flex Gateway registration, extracting useful information you use to verify whether the renewal command was successful.

Invoke the following `help` command for information about usage:

[source,ssh]
----
flexctl registration inspect --help
----

For Flex Gateway running in a container, invoke `help` as part of the container `run` command:

[tabs]
====
Docker::
+
[source,ssh]
----
docker run --entrypoint flexctl mulesoft/flex-gateway inspect --help
----

Podman::
+
[source,ssh]
----
podman run --entrypoint flexctl docker.io/mulesoft/flex-gateway inspect --help
----
====

Refer to the following topics for more information about inspection command usage:

* <<inspect-with-custom-url,Inspect Registration Status with a Custom URL>>
* <<inspect-with-reg-file,Inspect Registration Status with a Registration File>>

[[inspect-with-custom-url]]
== Inspect Registration Status with a Custom URL

You can inspect a registration by specifying the base URL of the Flex Gateway Admin API. The default value is `http://localhost:9999`. Omit the `--flex-gateway-admin-api-url` flag if using the default value.

[source,ssh]
----
flexctl registration inspect \
--flex-gateway-admin-api-url=<your-custom-admin-api-url>
----

For Flex Gateway running in a container, invoke `inspect` as part of the container `exec` command. Replace `<container-name-or-id>` with the running container reference:

[tabs]
====
Docker::
+
[source,ssh]
----
docker exec -u $UID <container-name-or-id> flexctl inspect \
--flex-gateway-admin-api-url=<your-custom-admin-api-url>
----

Podman::
+
[source,ssh]
----
xx
----
====

Invoking the command results in the following example output:

[source,text]
----
{“expiration_date”: “2024-01-16 16:20:30 +0000 UTC”}
----

[[inspect-with-reg-file]]
== Inspect Registration Status with a Registration File

You can inspect a registration by extracting the information from your `registration.yaml` file. Specify the path and filename.

[source,ssh]
----
flexctl registration inspect --file=<path-to-registration-file>
----

For Flex Gateway running in a container, invoke `inspect` as part of the container `run` command:

[tabs]
====
Docker::
+
[source,ssh]
----
docker run --entrypoint flexctl \
-v <path-to-registration-directory>:/registration \
-u $UID mulesoft/flex-gateway \
inspect --file=registration/<registration-filename>
----

Podman::
+
[source,ssh]
----
xx
----
====

Invoking the command results in the following example output:

[source,text]
----
{“expiration_date”: “2024-01-16 16:20:30 +0000 UTC”}
----

== See Also

* xref:flex-install.adoc[Download Flex Gateway]
* xref:flex-conn-reg-run.adoc[Register and Run Flex Gateway in Connected Mode]
* xref:flex-local-reg-run.adoc[Register and Run Flex Gateway in Local Mode]
