= Renewing Flex Gateway Registration
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Renewing the Flex Gateway registration is a straightforward process that ensures the continued interaction of your applications with Anypoint Runtime Manager. Renewing registration will help maintain the smooth operation of your applications. Verify the success of the renewal process to avoid any potential disruptions in your application's operation.

== Before You Begin

* xref:flex-install.adoc[Download Flex Gateway]. To invoke the registration renewal `flexctl` commands, download the latest version of Flex Gateway. It is not necessary to run this version of the gateway.

Flex Gateway includes the following CLI command to renew registration:

[source,ssh]
----
flexctl registration renew
----




Renews a Flex Gateway existing registration with Runtime Manager. Only one of user credentials or app credentials is required, if more than one type of authentication is used then the following precedence will take place: user credentials -> app credentials.
For user authentication use the "--username" and "--password" flags.
For app authentication use the "--client-id" and "--client-secret" flags.

If the Flex Gateway instance is running normally, the command returns an exit code of `0`. Otherwise, the gateway is unhealthy and the command returns a `1`.

You can either run the liveness check command manually or configure the command to run automatically. By default, Flex Gateways deployed on Kubernetes have an automatic liveness probe configured. The liveness probe periodically runs the liveness check command and automatically restarts the Flex Gateway pod after a specified number of failed liveness checks.
