= Renewing Flex Gateway Registration
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Renewing the Flex Gateway registration is a straightforward process that ensures the continued operation of your applications. You renew registration by using the `flexctl` CLI.

Verify the success of the renewal process to avoid any potential disruptions.

== Before You Begin

* xref:flex-install.adoc[Download Flex Gateway].
+
To invoke the registration renewal `flexctl` command, download the latest version of Flex Gateway. It is not necessary to run this version of the gateway.

== CLI Command Overview

Flex Gateway includes the following CLI command to renew registration:

[source,ssh]
----
flexctl registration renew
----

The command renews an existing Flex Gateway registration with Runtime Manager. For authentication, you specify *either* user credentials or application credentials. Authentication with user credentials requires the `--username` and `--password` flags. Authentication with application credentials requires the `--client-id` and `--client-secret` flags.

Invoke one of the following for overview information about command usage:

* `flexctl registration renew --help`
* `flexctl registration renew -h`

Refer to the following for more information about command usage:

* <<renew-with-user-password,Renew Registration with User Credentials>>
* <<renew-with-app,Renew Registration with Application Credentials>>

[[renew-with-user-password]]
== Renew Registration with User Credentials

[cols="1a,1a"]
|===
| Command |Result

|
`flexctl registration renew
--username=user
--password=pass
/path/to/registration.yaml`

|

Starting registration renewal, please be patient.
Registration renewal completed, the configuration files were written in directory ".". For security, modify the file permissions to restrict production scenario access to the user running flex.

Side effect: the following files were written on the current directory
registration.yaml

|===
