= Reviewing Resource Sizing 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:table-caption!:

Before getting started with Flex Gateway, analyze and choose your configuration to obtain the best performance and auto-scaling rate.

When assigning resources for a replica node, consider:

* Number of APIs
* Amount of memory the node needs
* Processing power for the node
* Number of policies in each API
* Amount of traffic each node handles
* Amount of time the node takes to answer the request (latency)
* Type of traffic the node handles, and within the traffic:
** The number of requests per second the node handles
** Size of each request (bytes)

== Choose Appropriate Resources

The following table guides you to know the resources you must allocate to your replica node according to your environment:

[options="header"]
|====
| Node Size | CPU | RAM 
| Small | 1-2 cores | 2-4 GB
| Medium | 2-4 cores | 4-8 GB
| Large | 8-16 cores | 16-32 GB	
|====

NOTE: Nodes belonging to a cluster must be of the same size.

== Choose Your Cluster Size

The following guiding table helps you choose the appropriate node and cluster size:

[options="header"]
|====
| Node Size | Number of APIs | Number of Policies | Expected Latency | Expected Throughput | Target Environment
| Small | < 100 | 4 | < 100 ms | < 500 RPS | Dev/test cluster
| Medium | < 500 | 4 | < 20 ms | < 2500 RPS | Production cluster
| Large | > 500 | 4 | < 10 ms | < 10000 RPS | Mission-critical clusters
|====

High CPU usage can lead to increased latency. In such a case, proceed with horizontal scaling or increase the node size. 

High memory consumption can lead to out-of-memory errors. To solve this issue, increase the memory allocation or the node size. Horizontal scaling might not help solve issues in this situation. Horizontal scaling fails if high memory utilization is the problem. You must increase memory first, and scale horizontally later.

The guiding table considers a cluster with an average request size of 1kB and 4 policies implemented. Adjust your parameters depending on your use case. 

The most commonly used out-of-the-box policies, which are considered in these guidelines, are:

* Message logging
* Rate limiting
* JWT validation
* Header injection

Using TLS affects the response time and the process consumption.

== See Also

* xref:flex-gateway-getting-started.adoc[]
