= Automated Policies
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: api-manager::automated-policies-landing-page.adoc, policies::policies-automated-overview.adoc

Use automated policies to enforce security and logging requirements by applying the same policies to all APIs running in Flex Gateway. With policy automation, you can quickly design, build, and deploy secure and consistent APIs.

Automated policies enable you to deploy APIs with confidence because the target environment automatically enforces critical policies, resulting in reduced errors. An administrator no longer needs to remember to insert a policy to enforce common standards manually.

You can configure all xref:policies-included-directory.adoc[included policies] and xref:policies-custom-overview.adoc[custom policies] as automated policies and apply them to the APIs running in an environment.

[NOTE]
====
xref:flex-use-api-alerts.adoc[Alerts] cannot be added to API instances protected by automated policies.
====

== See Also

* xref:policies-automated-applying.adoc[]
