= Data Chaching Policy Template
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

== Policy Use Case

An antique store that buys and sells items needs to track the stock of each item in its collection and who buys it. To track the inventory movement, the company uses an API. 

During business hours, the catalog changes constantly and caching the available items isn't useful. Outside of business hours, the stock is frozen, and the catalog can be cached without any concern. Given this, the manager of the antique store's server decides to implement a caching policy that caches the stock during the non-business hours. 

The policy first checks the time of each incoming request. Then, if the request is outside of business hours, the policy caches the response.

To reuse the policy, the amount of cached requests and the business hours are configurable. 

An error in the caching flow should not make a request fail. So, by default, the caching policy does not block requests.  
