= Debugging Deployed Custom Policies
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

If a custom policy deployed on a Flex Gateway is malfunctioning, there are some different methods to debug the policy:

* <<debug-environment>>
* <<debug-logs>>

[[debug-environment]]
== Use the PDK Debugging Environment

The PDK debugging environment provides an easy way to view Flex Gateway logging and send a variety or requests. However, you may not be able to recreate your production environment. Use the PDK debugging environment before debugging on a Flex Gateway instance.

For more information about PDK's debugging environment, see xref:policies-pdk-debug-local.adoc[]

[[debug-logs]]
== Troubleshoot in a Production Environment

It is possible that errors that are not present in PDK's debugging environment are present when the policy is deployed to a production environment.

To use debug logs in a production environment, see xref:flex-troubleshoot-debug-logs[].