= Policy Development Kit Troubleshooting
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

When using the Policy Development Kit (PDK), you might encounter issues or receive error messages. See the following sections to help you resolve these issues:

* <<cargo-credential-provider-configuration, Cargo Credential-Provider Configuration>>

== Cargo Credential-Provider Configuration

When running the `setup` or `build` commands, you might receive the following error:

----
cargo +nightly install cargo-anypoint@1.0.0-beta.1 --registry anypoint -Z registry-auth --config .cargo/config.toml
warning: flag `-Z registry-auth` has been stabilized in the 1.74 release, and is no longer necessary
  Authenticated registries are available if a credential provider is configured.

    Updating `anypoint` index
error: failed to download `cargo-anypoint v1.0.0-beta.1 (registry `anypoint`)`

Caused by:
  unable to get packages from source

Caused by:
  authenticated registries require a credential-provider to be configured
  see https://doc.rust-lang.org/cargo/reference/registry-authentication.html for details
make: *** [install-cargo-anypoint] Error 101
----

To fix the error:

1. Find your Cargo main directory, `.cargo/`.
2. In the main directory, find the `credentials.toml` file and add the `credential-provider` field to the `[registries.anypoint]` section, for example:
+
[source,toml]
----
[registries.anypoint]
token = <someToken>
credential-provider = ["cargo:token"]
----
+
3. Save the changes.
4. Run the `setup` or `build` in your custom policy root directory. The command should now execute properly.

== See Also

* xref:policies-pdk-architecture.adoc[]
* xref:policies-pdk-prerequisites.adoc[]