= Debugging Custom Policies Locally with PDK
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

The Policy Development Kit (PDK) provides a preconfigured API instance located in the `<root-directory>/test/config` directory to begin testing your policy.

After you successfully xref:policies-pdk-compile-policies.adoc[compile your custom policy project] and add a <<register, Flex Gateway `registration.yaml`>> file to the configuration directory, you can use the `run` command to deploy the API instance and your policy to begin testing.

NOTE: PDK only supports Flex Gateways running in a Docker container.

To test your policy, complete the following tasks:

. <<before-you-begin>>
. <<register>>
. <<configure-the-policy>>
. <<add-additional-policies>> if necessary
. <<deploy-the-policy-with-pdk>>

== Before You Begin

Ensure that you have:

* xref:policies-pdk-compile-policies.adoc[Compiled your custom policy]
* https://www.docker.com/[Installed Docker ^]

[[register]]
== Register a Flex Gateway Instance in Local Mode

To begin using the `run` command to debug your custom policy, you must register a Flex Gateway in Local Mode.

For the `run` command to work, a Flex Gateway `registration.yaml` file must be in `<root-directory>/test/config` directory. An easy way to do this is to run the registration command in the directory, or you can move a `registration.yaml` file of a previously registered Flex gateway to the directory.

The `run` command only supports Flex Gateways running in Local Mode in a Docker Container. To register a Flex Gateway, see the relevant tutorial for your preferred credential type:

* xref:local-reg-run-up.adoc#docker[]
* xref:local-reg-run-app.adoc#docker[]
* xref:local-reg-run-token.adoc#docker[]

IMPORTANT: You only need to run the registration command. Do not run the Docker start command. The `run` command completes this step.

A different registration file must be created on each device testing the policy.

The registration file is ignored for storage in remote repositories and is listed in `.gitignore` file located at the root of the project directory.


== Configure the Policy

Depending on the configurations listed in the `gcl.yaml` file you configured in xref:policies-pdk-create-schema-definition.adoc[], you may have to configure some parameters before running the policy locally.

For example, if the `definition/gcl.yaml` file is as follows:

[source,yaml]
----
apiVersion: gateway.mulesoft.com.v1alpha1
kind: Extension
metadata:
  labels:
    title: my-custom-policy
    category: Security 
spec:
  extends:
    - name: extension-definition
  properties: 
    user:
      type: string
      default: user1
    password:
      type: string
    description:
      type: string
  required:
    - user
    - password
  
----

Update the `/test/config/api.yaml` file with your configuration value:

[source,yaml]
----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: ApiInstance
metadata:
  name: ingress-http
spec:
  address: http://0.0.0.0:8081
  services:
    upstream:
      address: http://backend
      routes:
        - config:
            destinationPath: /anything/echo/
  policies:
    - policyRef:
        name: my-custom-policy
      config:
        password: 12345678

---- 

In this example, the `user` is set to the default value `user1`, the `password` is set to `12345678`, and no description is provided.

== Add Additional Policies

You can also apply additional policies to the test API instance to test your custom policies behavior alongside other policies.

However, your custom policy under development must be the first policy specified, for example:

[source,yaml]
----
  policies:
    - policyRef:
        name: my-custom-policy
      config:
        password: 12345678
    - policyRef:
        name: additional-policy
      config: 
----

== Deploy the Policy with PDK

After you complete the previous steps, run the `run` command from the policy's root directory to deploy policy:

[source,cmd]
----
make run
----

This command starts the two Docker containers in the `<root-directory>/test/docker-compose.yaml` file:

* `Local-flex`: The Flex Gateway instance Docker container that executes the custom policy. This Flex Gateway listens for requests made to the `localhost:8081`.
* `Backend`: The Docker Container that runs the backend service for the Flex Gateway instance. This backend service echoes any request it receives.

NOTE: To stop the Docker containers, press `Cmd+c` or `Ctrl+c` depending on your device from the terminal running the containers.

Once the containers are running, you can make requests to the API instance, for example:

[source,cmd]
----
curl --location --request POST 'http://0.0.0.0:8081/some/route' \
--header 'Token: mytoken'
----

The backend service returns an echo response including the requests’s route, body, and headers sent with any modification performed by the custom policy or additional policies. Any logs included in the custom policy's source code are visible in the terminal running the containers.

== Loglevel

By default, the PDK debugging environment enables logs with the `debug` loglevel configured.

To change the loglevel, edit the `logging.runtimeLogs.logLevel` value in `test/config/logging.yaml`.

To learn more about editing a Flex Gateway's logging configuration file, see xref:flex-local-third-party-logs-config.adoc[].

== Use the Rust Debugger

Visual Studio Code (VS Code) includes a Rust debugger that can run unit tests. You cannot use the VS Code Debugger while the policy is deployed on a Flex Gateway. Meaning that to create the API mocking, you must use unit tests for the specific logic you need to debug.

To debug Rust code in VS Code, you must install the https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb[CodeLLDB Debugger Extension ^] or a different VS Code extension with the same functionality. To learn more about debugging Rust in VS Code, see https://code.visualstudio.com/docs/languages/rust#_debugging[Rust in Visual Studio Code ^].
