= Creating a New Project
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

To begin developing a new custom policy with the Policy Development Kit (PDK), generate a new custom policy project.

== Before You Begin

Before you can create a custom policy project, ensure that you have installed all xref:policies-pdk-prequisites.adoc[PDK prequisites].

== Create a New Policy Project

To create a custom policy project, run the PDK CLI `create` command, replacing `<my-custom-policy>` with the name of your new policy:

[source,ssh]
----
anypoint-cli-v4 pdk policy-project create --name <my-custom-policy>
----

Running the `create` command creates a custom policy project with the specified name. The project appears in a new directory or a directory specified using the `--output-dir` flag. The following tutorials refer to this as your project's root directory.

The `assetID` of the new policy is the policy's name in lower case with the spaces amended together with a `-`. For example, a policy with the name `My Header Injection Policy` asstID is `my-header-injection-policy`. 

The `groupID` of the new policy is `groupID` of the organization configured in Anypoint CLI.

Additionally, the `create` command supports the following flags:

[%header%autowidth.spread,cols="a,a,a,a"]
|===
| Flag | Default Value | Required | Description
| `--name=<value>` or `-n` | N/A | Yes | Name of the new policy
| `--description=<value>` or `-d` | N/A | No | Description of the new policy
| `--output-dir=<value>` of `-o` | `assetID` | No | Directory the new policy is created in. +
If the directory does not exist, it is created. If no directory is specified, the directory name is the policy `assetID`.
| `--version=<value>` | `1.0.0` | No | Version of the new policy. +
The version format is `<major-release>.<minor-release>.<patch-release>`.
|===

== Setup a New Policy Project

If you haven't run the `setup` command for a prior project, you must run the `setup` command from the policy's root directory after you create a custom policy project:

Run the setup command:

[source,ssh]
----
make setup
----

The setup command installs the PDK project's dependencies. It is only necessary to run this command if this is the first time you are creating a project on this device.

If prompted, provide your Anypoint Platform credentials. 

== Project Structure

After running the setup command, the policy's root directory contains the following directories and files shown in the directory tree: 

----
├─ definition/  # Contains the files that describe the Policy Definition
│  ├── target/  # Contains the build definition asset files
│  └── gcl.yaml # GCL file managed by the developer that describes the Policy Definition
├─ target/      # Contains the implementation asset files and the output of the policy build
├─ src/         # Contains the implementation source code
├─ test/        # Contains the artifacts required for running the policy locally
├─ Makefile     # Provides all the callable actions required during the policy development lifecycle
├─ Cargo.toml   # Rust language standard file that contains the metadata required to build the policy
└─.project.yaml # Project manifest used by PDK
----

=== target/ and definition/target/

There are two separate `target` directories:

* `definition/target/`: contains the policy asset definition published to exchange
* `target/`: Contains the files for the Policy asset implementation and the output of the Rust compilation process

Both `target` directories and their content are included in the `.gitignore` file. You must compile the targets on each individual devices. For example, if you are developing a policy as part of a team, your team can publish the policy and it's source code to a remote repository, but each team member must build the target on their device for local testing.

=== definition/

The `definition` directory contains the `gcl.yaml` file that defines the policy's metadata and the configuration properties.

To configure the `gcl.yaml` file, see xref:policies-pdk-create-schema-definition.adoc[].

=== Cargo.toml

Custom policies for Flex Gateway are developed in the Rust Programming language and compiled to a WebAssembly binary. 

The `Cargo.toml` is Rust project manifest. Its `[package]` section contains the basic information of the policy implementation. The version specified in `Cargo.toml` matches the policy asset version. You can manage the policy version by editing the version number in `Cargo.toml`. The version follows the Semantic Versionsing (SemVer) format: `<major-version>.<minor-version>.<patch-version>`.

=== src/

The `src` directory contains the policy's source code:

* `lib.rs`: Contains a set of methods that implement the behavior of the policy. These methods are the API our development kit offers to implement custom policies behavior. 

* `generated/config.rs` and `generated/mod.rs`: Are auto generated modules that make the policy configuration, as defined in the `gcl.yaml`, available for use in the lib.rs and any of the policy source files.

=== Makefile

This file contains all the callable actions, `make` commands, required for the policy development lifecycle:

* `make setup`: Installs the PDK internal dependencies for the rest of the Makefile goals. 
+
You ran this command in <<setup-a-new-policy-project>>.
* `make build-asset-files`: Generates all the policy asset files required to build, execute, and publish the policy. This command also updates the `config.rs` source code file with the latest configurations defined in the `gcl.yaml` file. 
+
For more information about compiling a policy, see xref:policies-pdk-create-schema-definition.ado[].
* `make build`: Runs the `make build-asset-files` command and compiles the WebAssembly binary of the policy. 
+
For more information about compiling a policy, see xref:policies-pdk-compile-policies.adoc[]. 
* `make run`: Provides a simple way to execute the current build of the policy in Docker containerized environment. 
+
For more information about testing your policy, see xref:policies-pdk-debug-local.adoc[].
* `make publish`: Publishes the policy asset in Exchange. 
+
For more information about publishing policies in Exchange, see xref:policies-pdk-publish-policies.adoc[].
* `make release`: Releases the policy asset in Exchange. 
+
For more information about releasing policies in Exchange, see xref:policies-pdk-publish-policies.adoc[].

Execute all `make` commands at the root level of you root directory.