= Policy Development Kit Prequisites
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

To begin using the Policy Development Kit (PDK), start by ensuring you have the following prequisites installed:

. Rust programming language 
+
To install or update Rust, run the following command:
+
[source,ssh]
----
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
----

. Rust nightly
+
To install Rust nightly, run the following command:
+
[source,ssh]
----
rustup toolchain install nightly
----

. Rust WebAssembly System Interface (WASI) Crate
+
To install or update Rust WASI, run the following command:
+
[source,ssh]
----
rustup target add wasm32-wasi
----

. Cargo Generate
+
To install or update Cargo Generate, run the following command:
+
[source,ssh]
----
cargo install cargo-generate
----

. Node.js and npm
+
To download and install, see the https://nodejs.org/en/download/[NodeJS download page].

. Anypoint CLI 4.x
+
To install Anypoint CLI 4.x, see xref:anypoint-cli::install.adoc[].

. Anypoint CLI PDK Plugin
+
To install the Anypoint CLI PDK Plugin, run the following command:
+
[source,ssh]
----
anypoint-cli-v4 plugins:install @mulesoft/anypoint-cli-pdk-plugin
----
