= Applying Custom Policies
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

Applying custom policies is the same as applying xref:policies-included-directory.adoc[included policies].

When applying custom policies, the configuration parameters are the parameters defined in `gcl.yaml`.

To learn more about defining configuration parameters, see xref:policies-pdk-create-schema-definition.adoc[].

== Before You Begin

* xref:policies-pdk-publish-policies.adoc[Upload your Custom Policy to Exchange]

== Connected Mode

When you apply a custom policy in Connected Mode, the configuration parameters and metadata defined in `gcl.yaml` appear in the API Manager UI.

To apply a custom policy in Connected Mode, see xref:policies-included-apply.adoc[Apply a Policy in Connected Mode]. 

== Local Mode

For Flex Gateway running in Local Mode, you apply API policies using xref:flex-local-configuration-reference-guide.adoc[local declarative configuration files]. You specify the location of these configuration files when you first run Flex Gateway.

To apply a custom policy in Local Mode, use either xref:flex-local-secure-api-with-basic-auth-policy.adoc[] or xref:flex-local-secure-api-with-auto-policy.adoc[] as an example. Replace the example configuration with your policy's configuration parameters.

== Reorder Custom Policies

Reordering custom policies is the same as reordering included policies.

To reorder policies, see xref:policies-reorder.adoc[].

Polices execute in order on the request and then in inverse order on the response. However, some policies do not execute on both the request and the response.

For example, policies ordered:

. Policy X
. Policy Y

Execute Policy X then Policy Y on the request, and Policy Y then Policy X on the response.