= Managing Flex Replicas
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

== Flex Replicas

A Flex Replica is an instance of the Flex Gateway. Each running Flex Gateway instance in Connected Mode
is a replica of a gateway registered in Runtime Manager. Setting up your gateway layer with multiple
Flex Gateway replicas will enable the APIs deployed on Flex Gateway to serve more traffic.

When using Anypoint Flex Gateway to manage APIs in production, you should at least have
more than one Flex Replica to avoid a single point of failure. Running multiple Flex Replicas also
increases performance if your API service receives a significant amount of traffic.

Currently, you cannot unregister or delete Flex Replicas from the Runtime Manager UI. If a Flex Replica
in Connected Mode is stopped it will be removed from the UI in Runtime Manager after 30 days. Otherwise,
it will appear in the Runtime Manager UI even if it is no longer running.

== Add a Flex Replica

After installing, registering, and running your Flex Gateway, you will need to add a replica
to avoid a single point of failure. 

There are two options for adding a Flex replica including the following:

* xref:flex-local-rep-run.adoc[Add Flex Replicas in Local Mode]: If you are running Flex Gateway in Local Mode, add Flex Replicas in Local Mode.
* xref:flex-conn-rep-run.adoc[Add Flex Replicas in Connected Mode]: If you are running Flex Gateway in Connected Mode, add Flex Replicas in Connected Mode.

== See Also

* xref:flex-gateway-getting-started.adoc[Get Started with Flex Gateway]
* xref:flex-local-manage.adoc[Manage Flex Gateway in Local Mode]
* xref:flex-conn-manage.adoc[Manage Flex Gateway in Connected Mode]

