= Gateway
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Platform offers three different runtimes for managing your APIs in API Manager. 

== Flex Gateway

Anypoint Flex Gateway is an ultrafast API gateway designed to manage and secure APIs running anywhere.
Built to seamlessly integrate with DevOps and CI/CD workflows, Anypoint Flex Gateway delivers the
performance required for the most demanding applications while providing enterprise security and manageability across any environment.

== Mule Gateway

Mule Runtime includes an embedded API Gateway. Using this gateway, any user can, for example, apply a basic authentication policy on top of a Mule application, enrich an incoming/outgoing message, or add any other complex capability to an API without having to write any code.

Overall, API Gateway allows you to add a dedicated orchestration layer on top of your backend APIs and services to help you separate orchestration from implementation concerns. You can leverage the governance capabilities of API Manager to apply, among other capabilities, throttling, security, caching, and logging to your APIs.

If you want to apply policies and generate analytics info, you must use either:

* An API defined in a Mule application.
* A Mule application that proxies your existing backend implementation. 

== Anypoint Service Mesh

Anypoint Service Mesh enables you to extend your microservices network by including your non-MuleSoft applications into the Anypoint Platform sphere. You can then manage and secure your application network, including your non-Mule applications, seamlessly from a single pane.

Your non-MuleSoft microservices might be written using different languages and platforms, or might be deployed in different environments. To alleviate issues arising from differences in these microservices, Anypoint Service Mesh ensures the following application management advantages:

* Provides resilient service-to-service communication using zero-trust policies to handle traffic control, fault tolerance and load balancing
* Extends MuleSoft API Management capabilities to any non-Mule service, with policies, security and analytics all applied directly from Anypoint Platform
* Amplifies reuse of services with discovery of non-Mule services within Exchange, available for use in future projects