= Publishing Split-Model Policies to Exchange
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

During the custom split-model policy development cycle, you can upload the definition and implementation of your policy to Exchange to create a new Exchange assets to manage the asset versions and to distribute it to other users. For more information about Exchange, see xref:exchange::index.adoc[].

For custom policies running in Local Mode, it is not required to publish your policy to Exchange. However, Exchange is a useful version control tool. It is your responsibility to distribute custom policies for Local Mode use.

When uploading your policy to Exchange, you can choose to either:

* <<publish, Publish a Custom Policy>> +
Publish a policy if the policy version is still in development. This enables you to test and edit the policy version.
+
To learn about development assets, see xref:policies-pdk-publish-policies.adoc#publish[Publish a Custom Policy].
* <<release, Release a Custom Policy>> +
Release the policy to create a definitive version of the policy. After releasing the policy, you must create a new policy version to edit the policy.
+
To learn about production assets, see xref:policies-pdk-publish-policies.adoc#release[Release a Custom Policy].

Every time you publish or release a definition and implementation asset, you create a new `stable` version of that asset in Exchange. For more information about `stable` state assets, see xref:exchange::lifecycle.adoc#stablet-state[Stable State Assets].

After you upload your definition and implementation assets to Exchange, see xref:policies-pdk-apply-policies.adoc[].

== Before You Begin

* Ensure that the Connected App you used to authenticate to the xref:policies-pdk-prerequisites.adoc#cli[Anypoint Platform CLI] has the `Exchange Contributor` scope applied.
* xref:policies-pdk-compile-policies.adoc[Compile your Policy].

[[publish-a-new-split-model-policy]]
== Publish a New Split-Model Policy

. xref:policies-pdk-create-project-split.adoc#create-a-new-policy-definition-project[Create a definition project]:
.. Make changes on the `gcl.yaml`
.. Execute `make publish` in the definition project to publish the development definition asset to Exchange.
. xref:policies-pdk-create-project-split.adoc#create-a-new-policy-implementation-project[Create an implementation project]:
.. Update the `definition_asset_id` version field in the `cargo.toml` file to `1.0.0-DEV`.
.. Execute `make build-asset-files` in the implementation project.
.. Code your policy logic and test locally.
.. Execute `make publish` to release the development implementation asset to Exchange for testing in lower environments. 
.. Validate the policy works as expected. Complete steps C and D until testing is complete.
. After validating the policy works as expected, release the both assets to Exchange:
.. In the definition project, execute `make release` to release the definition asset to Exchange.
.. In the implementation project, update the `definition_asset_id` version field in the `cargo.toml` file to `1.0.0`.
.. Execute `make release` to release the implementation asset to Exchange.

== Publish a Patch Version Update (Implementation Update)

After you have <<publish-a-new-split-model-policy, Published a new split-model policy>>, you can update the implementation asset for bug fixes or performance updates:

. Develop the new policy implementation:
.. In the implementation project, update the patch number of version in the `cargo.toml` file. For example: `1.0.1`. 
.. Add the `-DEV` suffix to the `definition_asset_id` version field in the `cargo.toml`. For example: `1.0.0-DEV`.
.. Execute `make build-asset-files` in the implementation project.
.. Code your policy logic and test locally.
.. Execute `make publish` to release the development implementation asset to Exchange for testing in lower environments. 
.. Validate the policy works as expected. Complete steps D and E until testing is complete.
. After validating the policy works as expected, release the implementation asset to Exchange:
.. In the implementation project, remove the `-DEV` suffix from the `definition_asset_id` version field in the `cargo.toml` file. For example: `1.0.0-DEV` to `1.0.0`.
.. Execute `make release` to release the implementation asset to Exchange.

== Publish a Minor or Major Version Update (Definition and Implementation Update)

After you have <<publish-a-new-split-model-policy, Published a new split-model policy>>, you can update the definition and implementation assets for updates that require new parameters:

. Update the definition asset:
.. Update the version in the `exchange.json` file of your definition project to `1.1.0`.
.. Make changes to the `gcl.yaml` file.
.. `make publish` on the definition project to publish the development definition asset to Exchange.
. Update the implementation asset:
.. In the implementation project, update the minor or major number of version in the `cargo.toml` file. For example: `1.0.0` to `1.1.0`. 
.. Update and add the `-DEV` suffix to the `definition_asset_id` version field in the `cargo.toml`. For example: `1.0.0-DEV` to `1.1.0-DEV`.
.. Execute `make build-asset-files` in the implementation project.
.. Code your policy logic and test locally.
.. Execute `make publish` to release the development implementation asset to Exchange for testing in lower environments. 
.. Validate the policy works as expected. Complete steps D and E until testing is complete.
. After validating the policy works as expected, release both assets to Exchange:
.. In the implementation project, remove the `-DEV` suffix from the `definition_asset_id` version field in the `cargo.toml` file. For example: `1.1.0-DEV` to `1.1.0`.
.. Execute `make release` to release the implementation asset to Exchange.

== Develop Split Model Policies Locally Without Publishing to Exchange 

. Develop the policy definition:
.. Ensure the version in the `exchange.json` file is the correct version. For example: `1.0.0` for your first version.
.. Make changes to the `gcl.yaml` file.
.. Execute `make release-local` in the definition project.
. Develop the policy implementation:
.. Add the `-DEV` suffix to the `definition_asset_id` version field in the `cargo.toml` and ensure it matches the definition asset version used in step one.
.. Execute `make build-asset-files` in the implementation project.
.. Code your policy logic and test locally.
.. Validate the policy works as expected. Complete steps C until testing is complete.
. If you wish to distribute the policy locally as a production asset:
.. Remove the `-DEV` suffix from the `definition_asset_id` version field in the `cargo.toml` file. For example: `1.0.0-DEV` to `1.0.0`.
.. Execute `make build` to rebuild the implementation asset.
.. Distribute the policy assets as desired.


== See Also

* xref:policies-pdk-apply-policies.adoc[]
* xref:policies-pdk-troubleshooting.adoc[]
