= Anypoint Platform Gateways
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

An API gateway allows you to add a dedicated orchestration layer on top of your backend APIs and services
to help you separate orchestration from implementation concerns. You can then leverage the governance capabilities
of API Manager to apply, among other capabilities, throttling, security, caching, and logging to your APIs.

Anypoint Platform offers three different runtime options for managing and securing your APIs.

== Anypoint Flex Gateway

Anypoint Flex Gateway is an ultrafast API gateway designed to manage and secure APIs running anywhere.
Built to seamlessly integrate with DevOps and CI/CD workflows, Anypoint Flex Gateway delivers the
performance required for the most demanding applications and microservices while providing enterprise
security and manageability across any environment.

For more information, see xref:gateway::flex-gateway-getting-started.adoc[Getting Started with Flex Gateway].

[[anypoint_mule_gateway]]
== Anypoint Mule Gateway

Mule runtime engine includes an embedded Mule Gateway. You can leverage the governance capabilities of API Manager to apply, among other capabilities, throttling, security, caching, and logging to your APIs.

For example, using Mule Gateway you can:

* Apply a basic authentication policy on top of a Mule application.
* Enrich an incoming or outgoing message.
* Add other complex capabilities to an API without writing code.

If you want to apply policies and generate analytics info, you must use either:

* An API defined in a Mule application.
* A Mule application that proxies your existing backend implementation.

For more information, see xref:mule-gateway::mule-gateway-capabilities-mule4.adoc[].