= Connect the Mule Gateway Through a Proxy Server
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can configure the Mule Gateway to route traffic through the proxy server to API Manager if your Mule Runtime engine runs inside a firewall that restricts external communication through a proxy server.

Mule Gateway supports Basic, NTLM, and Kerberos v5 (via SPNEGO) authentication schemes for proxied communication.


== Configure the Mule Gateway to Connect Through a Proxy Server

To configure Mule Gateway to connect through a proxy server, you must set up your proxy server configuration in a `$MULE_HOME/conf/wrapper.conf` file:



To configure the proxy server in the `$MULE_HOME/conf/wrapper.conf` file, add your proxy server information to the following properties:

* `wrapper.java.additional.<n>=-Danypoint.platform.proxy_host={hostname}`
* `wrapper.java.additional.<n>=-Danypoint.platform.proxy_port={port}`
* `wrapper.java.additional.<n>=-Danypoint.platform.proxy_username={username}`
* `wrapper.java.additional.<n>=-Danypoint.platform.proxy_password={password}`

[IMPORTANT]
These parameters are additional options to pass to Java during launch. The <n> element refers to the number of additional parameters in the configuration, starting from `1` and incrementing sequentially without any gaps. 

With the provided credentials, Mule Gateway will prioritize Basic Authentication over NTLM. If Basic Authentication fails, the Gateway will attempt to authenticate with NTLM. +
For Kerberos authentication, proceed to the next section.

=== Using Kerberos for Proxy Authentication

To authenticate using Kerberos, you need to add all the properties described in the previous section, plus the following new properties:
* `wrapper.java.additional.<n>=-Danypoint.platform.proxy_kerberos_krb5_path={/path/to/krb5.conf}`
* `wrapper.java.additional.<n>=-Danypoint.platform.proxy_kerberos_jaas_path={/path/to/kerberos.jaas}`

NOTE: Kerberos authentication is only supported in Mule runtime versions 4.3.x and 4.4.x released after July 2, 2024 and Mule runtime versions 4.6.5, 4.7.1 and later.

==== Kerberos KRB5 Path
The property `anypoint.platform.proxy_kerberos_krb5_path` specifies the path to the `krb5.conf` file used to locate the KRB5 server. An example of this file is:

[source,text,linenums]
----
[libdefaults]
    kdc_realm = service.ws.apache.org
    default_realm = service.ws.apache.org
    udp_preference_limit = 1
    kdc_tcp_port = 64718

[realms]
    service.ws.apache.org = {
        kdc = localhost:64718
    }
----

==== Kerberos JAAS Path
Representing property `anypoint.platform.proxy_kerberos_jaas_path`, the value entered here is the path to the JAAS file for authentication. An example of such file is:

[source,text,linenums]
----
alice {
    com.sun.security.auth.module.Krb5LoginModule required
    refreshKrb5Config=true
    useKeyTab=false
    keyTab="/my/krbwd/alice.keytab"
    principal="alice";
};
com.sun.security.jgss.login {
  com.sun.security.auth.module.Krb5LoginModule required
  useKeyTab=true
  storeKey=true
  keyTab="/my/krbwd/alice.keytab"
  principal="alice";
};
com.sun.security.jgss.initiate {
  com.sun.security.auth.module.Krb5LoginModule required
  useKeyTab=true
  storeKey=true
  keyTab="/my/krbwd/alice.keytab"
  principal="alice";
};
com.sun.security.jgss.accept {
  com.sun.security.auth.module.Krb5LoginModule required
  useKeyTab=true
  storeKey=true
  keyTab="/my/krbwd/alice.keytab"
  principal="alice";
};
----

It's important to set the `useKeyTab` to false for the principal being authenticated, in this case `alice` so that it takes the credentials set up for `anypoint.platform.proxy_username` and `anypoint.platform.proxy_password`.

== See Also

* https://docs.mulesoft.com/runtime-manager/rtm-agent-proxy-config[Connect the Agent Through a Proxy Server].