= Anypoint Mule Gateway
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:page-aliases: api-manager::runtime-agw-landing-page.adoc

Mule runtime engine includes an embedded Mule Gateway. Mule Gateway enables you to add a dedicated orchestration layer on top of your backend APIs and services to help you separate orchestration from implementation. You can leverage the governance capabilities of API Manager to apply, among other capabilities, throttling, security, caching, and logging to your APIs.

Using Mule Gateway, you can, for example:

* Apply a basic authentication policy on top of a Mule application.
* Enrich an incoming or outgoing message.
* Add any other complex capability to an API without having to write any code.

If you want to apply policies and generate analytics info, you must use either:

* An API defined in a Mule application.
* A Mule application that proxies your existing backend implementation. 

For more information, see xref:mule-gateway::mule-gateway-capabilities-mule4.adoc[].