= Reordering Policies
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: api-manager::re-order-policies-task.adoc, policies-included-reorder.adoc, api-manager::policy-mule3-reorder-policies-task.adoc, policies::policies-mule3-reorder-policies-task.adoc

In Mule Gateway, to execute certain policies before others, you can configure the order of execution of included and custom API level policies. However, you cannot configure API level policies to execute before automated policies.

You reorder policies via API Manager.

IMPORTANT: You cannot configure the execution order of the xref:policies-included-cors.adoc[Cross-Origin Resource Sharing (CORS) policy]. In Mule Gateway, the CORS policy executes before automated and API level policies.

== Reorder Policies

To reorder policies in Mule Gateway:

. Go to *Anypoint Platform > API Manager*.

. In *API Administration* click the name of the API whose policies you want to reorder.

. From the left navigation menu, click *Policies*.

. From the top of the list of the applied policies, click *Reorder policies*.

. From the *Reorder Applied Policies* section, use the up and down arrows to rearrange the order of policies.

. Click *Apply order*.

== Apply Duplicate Policies

Mule Gateway supports applying duplicate policies. Automated, API-level, and resource-level policies all support duplicate policy application.

When applying duplicate policies:

* Add a label to the duplicated policies to differentiate them.
* Consider if it makes sense to apply duplicated policies. For example, the duplicated IP allowlist policies allow only IPs that are allowed by both policies. Rather than applying duplicated policies, configure the IPs in one policy.

== See Also

* xref:policies-included-directory.adoc[Included Policies Directory]