= Packaging a Custom Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:page-aliases: api-manager::custom-policy-packaging-policy.adoc, policies::policies-custom-package.adoc

You can use the Mule Maven Plugin to package your custom policy into a deployable JAR file that you can later apply to an API.

. Make sure you added the Mule Maven Plugin to your pom.xml file. This is done automatically by custom policy's Archetype
+
[source,console,linenums]
----
<plugin>
    <groupId>org.mule.tools.maven</groupId>
    <artifactId>mule-maven-plugin</artifactId>
    <version>${mule.maven.plugin.version}</version>
    <extensions>true</extensions>
</plugin>
----
+
. From the command line in your project's folder, run the package phase:
+
[source,console,linenums]
----
> mvn clean package
----

The packager then packages your application and creates the deployable JAR file into the target directory within your project's folder.

It will also verify that all the necessary files were provided for the packaging, and that the information provided in the mule-artifact and in the policy yaml are valid.

== See Also
* xref:policies-custom-getting-started.adoc[Getting started with custom policies development]
* xref:policies-custom-upload-to-exchange.adoc[Uploading a Custom Policy to Exchange]
* xref:policies-custom-mule-4-reference.adoc[Reviewing Custom Policy concepts]
