= Health Check Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:keywords: health check, api gateway, flex gateway, gateway, policy

[width="100%", cols="5,15"]
|===
>s|Policy name | Health Check
>s|Summary      | Monitors API upstream health at specific intervals
>s|Category | Quality of Service
>s|First Mule version available | Health Check cannot be applied as a policy in Mule. 
>s| First Flex version available | v1.4.0
.1+>.^s| Returned Status Codes |
| No return codes exist for this policy 
|===

== Summary

The Health Check policy enables you to check connection attempts to a specific endpoint and sends you an email alert if the connection status changes.

The Health Check policy monitors your API by making GET requests to the specified API base path. The first request is made immediately after applying the Health Check policy and then continually at the specified minute intervals. You may specify any GET method.

 When you configure Health Check, specify a response code for the GET request that indicates a healthy connection. For example, the status code of an active API should return 200, indicating the API can receive connections. The platform sends an email alert when the status code is not 200. Health Check only validates the response code, so what is returned to the endpoint is unimportant.
 
 You can use any 1xx, 2xx, 3xx, 4xx, or 5xx response codes. However, if you expect successful connections to your endpoints, 2xx response codes are ideal.

You are required to create an alert for the Health Check policy. Applying the policy navigates you to the Create Alert page, where you must create an alert. For information on how to configure your alert, see xref:api-manager::osv2-faq#add-api-alert-task.adoc[Add API Alerts].

== Configuring Policy Parameters

=== Flex Gateway Local Mode

The Health Check policy is not supported in Local Mode.

=== Flex Gateway Connected Mode

When you apply the policy to your API from the UI, a list of parameters is displayed:

[%header%autowidth.spread,cols="a,a"]
|===
| *Parameter* | *Description* 
|Upstream URL  | The full URL of the API upstream you are monitoring
|Base path  | The HTTP path of the GET method that is requested during health checks 
|Response code  | The expected status code of the GET request specified in the base path
|Schedule | The interval in minutes between health checks
|===
