= Health Check
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:keywords: health check, api gateway, flex gateway, gateway, policy

[width="100%", cols="5,15"]
|===
>s|Policy name | Health Check
>s|Summary      | Monitors API upstream health at specific intervals.
>s|Category | Quality of Service
>s| First Flex version available | v1.4.0
.1+>.^s| Returned Status Codes |
| No return codes exist for this policy 
|===

== Summary

The Health Check policy monitors the upstream health of an API at specified intervals. Health check allows you to monitor if an API is active and sends you an email alert if the status of the API changes.

The Health Check policy monitors your API by making a GET request to the API. If the request returns the expected response code that you provide, the status of the API is considered healthy. If the request returns an unexpected response code, the status of the API is considered unhealthy and the policy alerts you. You can only specify one expected response code.

You are required to create an alert for the health check policy.

== Configuring Policy Parameters

=== Flex Gateway Local Mode

The Health Check policy is not supported in Local Mode.

=== Flex Gateway Connected Mode

When you apply the policy to your API from the UI, a list of parameters is displayed:

[%header%autowidth.spread,cols="a,a"]
|===
| *Parameter* | *Description* 
|Upstream URL  | The full URL of the API upstream
|Base path  | The HTTP path that is requested during health checks
|Response code  | The expected response code of the API GET request
|Schedule | The interval in minutes between health checks
|===

== How This Policy Works
