= Health Check
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:keywords: health check, api gateway, flex gateway, gateway, policy

[width="100%", cols="5,15"]
|===
>s|Policy name | Health Check
>s|Summary      | Monitors API upstream health at specific intervals
>s|Category | Quality of Service
>s|First Mule version available | Health Check cannot be applied as a policy in Mule. 
>s| First Flex version available | v1.4.0
.1+>.^s| Returned Status Codes |
| No return codes exist for this policy 
|===

== Summary

The Health Check policy enables you to check connection attempts to a specific endpoint and sends you an email alert if the connection status changes.

The Health Check policy monitors your API by making a GET requests to the API. The first request is made immediately after applying the Health Check policy and then continually at the specified minute intervals.

 When you configure Health Check, specify a status code of the GET request that indicates a healthy connection. For example, when the American Flights API is active, the status code should return 200, indicating the API can receive connections. When you configure Health Check with these parameters, you receive an email when the status code is not 200. You can use any 1xx, 2xx, 3xx, 4xx, or 5xx response codes for your health checks. If you expect successful connections to your endpoints, 2xx status codes are ideal connection results.

You are required to create an alert for the health check policy. After applying the the Health Check policy, you are navigated to the Create Alert page. For information on how to configure your alert, see xref:api-manager::osv2-faq#add-api-alert-task.adoc[Add API Alerts].

== Configuring Policy Parameters

=== Flex Gateway Local Mode

The Health Check policy is not supported in Local Mode.

=== Flex Gateway Connected Mode

When you apply the policy to your API from the UI, a list of parameters is displayed:

[%header%autowidth.spread,cols="a,a"]
|===
| *Parameter* | *Description* 
|Upstream URL  | The full URL of the API upstream you are monitoring
|Base path  | The HTTP path of the GET method that is requested during health checks
|Response code  | The expected status code of the GET request
|Schedule | The interval in minutes between health checks
|===

== How This Policy Works
