= Reordering Policies
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: api-manager::re-order-policies-task.adoc, policies-included-reorder.adoc

In Mule Gateway and Flex Gateway, to execute certain policies before others, you can configure the order of execution of included and custom API level policies. However, you cannot configure API level policies to execute before automated policies.

For Mule Gateway and Flex Gateway Connected Mode, you reorder policies via API Manager. For Flex Gateway Local Mode you order policies via `PolicyBinding` YAML resource.

IMPORTANT: You cannot configure the execution order of the xref:policies::policies-included-cors.adoc[Cross-Origin Resource Sharing (CORS) policy]. In Mule Gateway and Flex Gateway, the CORS policy executes before automated and API level policies.

== Flex Gateway Local Mode
In Flex Gateway Local Mode, you configure policy ordering via a `PolicyBinding` YAML resource. 

When defining a policy using a `PolicyBinding` YAML resource, edit the `order` parameter to match when you want the policy to execute. Ensure that you don't define the same order number to different policies.

For information about Local Mode policy order, see the xref:gateway::flex-local-configuration-reference-guide.adoc#policy-binding[Declarative Configuration Reference Guide].



== Mule Gateway and Flex Gateway Connected Mode

To reorder API level policies in Mule Gateway and Flex Gateway Connected Mode:

. In Anypoint Platform, select *API Manager > API Administration* and then click the API version or instance.

. From the left navigation menu, select *Policies*.

. From the top of the list of the applied policies, click *Reorder policies*.

. From the *Reorder Applied Policies* section, use the up and down arrows to rearrange the order of policies.

. Click *Apply order*.


== See Also

* xref:policies::policies-included-directory.adoc[Included Policies Directory]
* xref:gateway::flex-local-configuration-reference-guide.adoc#policy-binding[Policy Ordering in Local Mode]
* xref:policies::policies-overview.adoc[]