= Custom Policies
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
// :page-aliases: api-manager::change-custom-policy-mule3.adoc, api-manager::policies-custom-landing-page.adoc, api-manager::policies-custom-overview.adoc

Policies enforce regulations to help manage security, control traffic, and improve API adoption. For example, a policy can control authentication, access, and service level agreements (SLAs). You can create custom policies based on your specific business requirements and apply them to APIs to extend existing functionality or define new ones.

The workflow to create custom policies for Mule 4 and earlier in Anypoint API Manager has not changed. Continue to use the process of developing the policy, packaging the custom policy, uploading it to Exchange, and applying the policy to an API through Anypoint API Manager as described in the Anypoint API Manager documentation. 

The workflow for creating custom policies for Anypoint Flex Gateway is done in Exchange. Creating custom policies for Mule 4 is also supported in Exchange. The policy is then available to be applied to an API in Anypoint API Manager.

For more information, refer to the following:

* xref:policies::policies-custom-flex-implement-rust.adoc[Implement a Flex Gateway Custom Policy in Rust]
* xref:policies::policies-custom-flex-getting-started.adoc[Publish a Flex Gateway or Mule 4 Custom Policy]
* xref:gateway::flex-local-deploy-custom-policy.adoc[Apply a Flex Gateway Custom Policy in Local Mode]
* xref:policies::policies-custom-getting-started.adoc[Publish a Mule 4 Custom Policy]
* xref:policies::policies-custom-examples.adoc[]
* xref:policies::policies-custom-manage.adoc[]
* xref:policies::policies-custom-manage-offline.adoc[Managing Offline Custom Policies]
* xref:policies::policies-mule3-custom-policies.adoc[Mule 3 Custom Policies]