= Reordering Policies
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: api-manager::re-order-policies-task.adoc

In Connected Mode and Mule Gateway, you configure the order of execution of included policies via *API Manager*. The following steps demonstrate this.

In Local Mode, you configure policy ordering via a `PolicyBinding` YAML resource. For information about Local Mode policy order, see the xref:gateway::flex-local-configuration-reference-guide.adoc#policy-binding[Declarative Configuration Reference Guide].

To reorder a policy for Connected Mode or Mule Gateway:

. In Anypoint Platform, select *API Manager > API Administration* and then click the API version or instance.

. From the left navigation menu, select *Policies*.

. From the top of the list of the applied policies, click *Edit Policy Order*.

. From the *Reorder Applied Policies* section, use the up and down arrows to rearrange the order of policies.
. Click *Apply order*.

== See Also

* xref:gateway::flex-local-configuration-reference-guide.adoc#policy-binding[Policy Ordering in Local Mode]
* xref:policies::policies-overview.adoc[]