= Health Check Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:keywords: health check, api gateway, flex gateway, gateway, policy

[width="100%", cols="5,15"]
|===
>s|Policy name | Health Check
>s|Summary | Monitors API upstream health at specific intervals
>s|Category | Quality of Service
>s|First Mule version available | Health Check cannot be applied as a policy in Mule. 
>s| First Flex version available | v1.4.0
.1+>.^s| Returned Status Codes | No return codes exist for this policy. 
|===

== Summary

include::anypoint-security::partial$health-check-partial.adoc[intro1]

include::anypoint-security::partial$health-check-partial.adoc[intro2]

You are required to create an alert for the Health Check policy. Applying the policy navigates you to the Create Alert page, where you must create an alert. For information on how to configure your alert, see xref:gateway::flex-use-api-alerts.adoc[Using Flex Gateway API Alerts].

include::anypoint-security::partial$health-check-partial.adoc[tlsImportant1]

== Configuring Policy Parameters

=== Flex Gateway Local Mode

The Health Check policy is not supported in Local Mode.

=== Flex Gateway Connected Mode

When you apply the policy to your API from the UI, a list of parameters is displayed:

[%header%autowidth.spread,cols="a,a,a"]
|===
| Element | Description | Required?
|Upstream URL  | The full URL of the API upstream you are monitoring | Yes
|Base path  | The HTTP path of the GET method that is requested during health checks | Yes
|Response code  | The expected status code of the GET request specified in the base path. Only a number response code is accepted. | Yes
|===
