= Schema Validation (OAS3) Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:keywords: oas3, schema validation, api gateway, flex gateway, gateway, policy

[width="100%", cols="5,15"]
|===
>s|Policy Name| Schema Validation (OAS3)
>s|Summary| Validates incoming traffic against a supplied OAS3 schema
>s|Category| Security
>s|First Mule version available | Schema Validation (OAS3) cannot be applied as a policy in Mule.
>s|First Flex version available | v1.4.0
>s|Returned Status Codes|
|===

== Summary

Applications processing REST API requests are susceptible to attacks such as header injection and payload injection. Additional vulnerabilities can lead to the access of sensitive information. The Schema Validation (OAS3) policy protects against such attacks and vulnerabilities by validating traffic against a supplied OpenAPI Specification 3.0 (OAS3) schema.

The policy validates request headers, queries, or path parameters.

You configure the policy to perform one of the following actions:

* Block the request, log the error, then return the error
* Log the error without blocking

== Configuring Policy Parameters

=== Flex Gateway Local Mode

In Local Mode, you apply the Schema Validation (OAS3) policy to your API via declarative configuration files. Refer to the following policy definition and table of parameters:

----
- policyRef:
    name:
  config:
----

[%header%autowidth.spread,cols="a,a,a,a"]
|===

|Parameter | Required or Optional | Default Value | Description

|
|
|
|

|===

==== Resource Configuration Example

----
- policyRef:
    name:
  config:
----

=== Flex Gateway Connected Mode

When you apply the Schema Validation (OAS3) policy to your API from the UI, the following parameters are displayed:

[width="100%", cols="2,6,1,1"]
|===
s|Field s|Description s|Default s|Required
| | ^| ^|
|===

== See Also
