= Transport Layer Security Policy - Outbound
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:keywords: tls, mtls, transport layer security, outbound tls, api gateway, flex gateway, gateway, policy

[%autowidth.spread,cols="a,a"]
|===
>s| Policy Name | Transport Layer Security (TLS) - Outbound
>s|Summary      | Enables two-way authentication between the API proxy and an upstream service
>s|Category | Security
>s| First Mule version available | TLS cannot be applied as a policy in Mule.
>s| First Flex version available | v1.4.0
.4+>.^s| Returned Status Codes | No return codes exist for this policy.
[%autowidth.spread,cols="a,a"]
|
|===

== Summary
Flex Gateway supports both TLS and mutual authentication TLS (mTLS) in Connected Mode and Local Mode.

To apply TLS in Connected Mode, see xref:gateway::flex-conn-tls-config.adoc[Configuring TLS Context for Flex Gateway in Connected Mode].

To apply TLS in Local Mode, see xref:gateway::flex-local-tls-config.adoc[Configuring TLS Context for Flex Gateway in Local Mode] and refer to the following configuration files in this documentation.

You can configure an outbound TLS or mTLS context to enable authentication between an API proxy and an upstream service, by binding the Transport Layer Security policy to your API instance. 

include::gateway::partial$task-tls-config.adoc[tags=port-sharing]

[NOTE]
====
Policy ordering cannot be applied to the Transport Layer Security policy.
====

== Configuring Policy Parameters

To enable outbound mTLS when creating an API Instance using Flex Gateway as your runtime, you must manually configure the TLS context
in a YAML configuration file. 

Refer to the following policy definition and table of parameters:

----
- policyRef:
    name: tls-outbound
  config:
    skipValidation: <boolean> // REQUIRED
    certificate: // REQUIRED
        key: <string> // REQUIRED
        crt: <string> // REQUIRED
    alpn: <array> // OPTIONAL
    minversion: <string> // OPTIONAL
    maxversion: <string> // OPTIONAL
    ciphers: <array> // OPTIONAL
----

When configuring the `ciphers` parameter, ensure that your API upstream supports the listed ciphers. For the supported ciphers, see <<local-support, TLS Cipher Support on Flex Gateway>>.

[%header%autowidth.spread,cols="a,a,a,a"]
|===
|Parameter | Required or Optional | Default Value | Description

| `skipValidation`
| Required
| false
|

| `certificate`
| Required
| N/A
| A TLS certificate key pair

| `certificate.key`
| Required
| N/A
| The private key part of the certificate

| `certificate.crt`
| Required
| N/A
| The public key part of the certificate

| `alpn`
| Optional
|
|A prioritized list of supported application level protocols; for example, h2, http/1.1, and so forth.

| `minversion`
| Optional
|
|The minimum TLS version allowed

| `maxversion`
| Optional
|
|The maximum TLS version allowed

| `ciphers`
| Optional
|
|A list of supported TLS ciphers (IANA format)

|===

=== Resource Configuration Examples

// sample config applied to all apis on gateway intro
include::gateway::partial$task-tls-config.adoc[tags=sample-config-mtls-outbound-intro]
//sample config applied to all apis on gateway
include::gateway::partial$task-tls-config.adoc[tags=sample-config-mtls-outbound]

include::anypoint-security::partial$flex-tls-cipher.adoc[tags=cipherSupportLocal;outboundImportantLocal;ciphers]




== See Also
* xref:gateway::flex-conn-tls-config.adoc[]
* xref:gateway::flex-local-tls-config.adoc[]
* xref:policies-included-tls.adoc[]