= Reordering Policies
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: api-manager::re-order-policies-task.adoc

In Mule Gateway and Flex Gateway Connected Mode, you configure the order of execution of included and custom API level policies via *API Manager*. However, you cannot configure API level policies to execute before automated policies. The following steps demonstrate how to reorder API level policies.

IMPORTANT: You cannot configure the execution order of the xref:policies::policies-included-cors.adoc[Cross-Origin Resource Sharing (CORS) policy]. In Mule Gateway and Flex Gateway, the CORS policy executes before automated and API level policies.

In Local Mode, you configure policy ordering via a `PolicyBinding` YAML resource. For information about Local Mode policy order, see the xref:gateway::flex-local-configuration-reference-guide.adoc#policy-binding[Declarative Configuration Reference Guide].

To reorder API level policies:

. In Anypoint Platform, select *API Manager > API Administration* and then click the API version or instance.

. From the left navigation menu, select *Policies*.

. From the top of the list of the applied policies, click *Edit Policy Order*.

. From the *Reorder Applied Policies* section, use the up and down arrows to rearrange the order of policies.

. Click *Apply order*.

== See Also

* xref:policies::policies-included-directory.adoc[Included Policies Directory]
* xref:gateway::flex-local-configuration-reference-guide.adoc#policy-binding[Policy Ordering in Local Mode]
* xref:policies::policies-overview.adoc[]