= Transport Layer Security Policy - Inbound
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:keywords: tls, mtls, transport layer security, inbound tls, api gateway, flex gateway, gateway, policy

[%autowidth.spread,cols="a,a"]
|===
>s| Policy Name | Transport Layer Security (TLS) - Inbound
>s|Summary      | Enables authentication between a client and the API proxy
>s|Category | Security
>s| First Mule version available | TLS cannot be applied as a policy in Mule.
>s| First Flex version available | v1.0.0 (inbound mTLS: v1.3.0)
.4+>.^s| Returned Status Codes | No return codes exist for this policy.
[%autowidth.spread,cols="a,a"]
| 
|===

== Summary
Flex Gateway supports both TLS and mutual authentication TLS (mTLS) in Connected Mode and Local Mode.

To apply TLS in Connected Mode, see xref:gateway::flex-conn-tls-config.adoc[Configuring TLS Context for Flex Gateway in Connected Mode].

To apply TLS in Local Mode, see xref:gateway::flex-local-tls-config.adoc[Configuring TLS Context for Flex Gateway in Local Mode] and refer to the following configuration files in this documentation.

You can configure an outbound TLS or mTLS context to enable authentication between an API proxy and an upstream service, by binding the Transport Layer Security policy to your API instance. 

include::gateway::partial$task-tls-config.adoc[tags=port-sharing]

[NOTE]
====
Policy ordering cannot be applied to the Transport Layer Security policy.
====

== Configuring Policy Parameters

To use HTTPS as your schema
when creating an API Instance using Flex Gateway as your runtime, you must manually configure the TLS context
in a YAML configuration file. 

Refer to the following policy definition and table of parameters:

----
- policyRef:
    name: tls
  config:
    requireClientCertificate: <boolean> // OPTIONAL
    trustedCA: <string> // OPTIONAL
    certificate: // REQUIRED
        key: <string> // REQUIRED
        crt: <string> // REQUIRED
    alpn: <array> // OPTIONAL
    minversion: <string> // OPTIONAL
    maxversion: <string> // OPTIONAL
    ciphers: <array> // OPTIONAL
----

When configuring the `ciphers` parameter, see <<local-support, TLS Cipher Support on Flex Gateway>> for the supported ciphers.

[%header%autowidth.spread,cols="a,a,a,a"]
|===
|Parameter | Required or Optional | Default Value | Description

| `requireClientCertificate`
| Optional
| false
| Enables/disables inbound mTLS

| `trustedCA`
| Optional
|
| The client certificate used in mTLS

| `certificate` 
| Required
| N/A
| A TLS certificate key pair

| `certificate.key` 
| Required
| N/A
| The private key part of the certificate

| `certificate.crt` 
| Required
| N/A
| The public key part of the certificate

| `alpn` 
| Optional
| 
|A prioritized list of supported application level protocols; for example, h2, http/1.1, and so forth.

| `minversion` 
| Optional
| 
|The minimum TLS version allowed

| `maxversion` 
| Optional
| 
|The maximum TLS version allowed

| `ciphers` 
| Optional
| 
|A list of supported TLS ciphers (IANA format)

|===

=== Resource Configuration Examples

// intro 
include::gateway::partial$task-tls-config.adoc[tags=intro2]

==== Apply TLS Configuration to All API Instances

// sample config applied to all apis on gateway intro
include::gateway::partial$task-tls-config.adoc[tags=sample-config-all-intro]
//sample config applied to all apis on gateway
include::gateway::partial$task-tls-config.adoc[tags=sample-config-all]

==== Apply TLS Configuration to a Specific API Instance

//sample config applied a specific api intro
include::gateway::partial$task-tls-config.adoc[tags=sample-config-instance-intro]
//sample config applied to a specific api
include::gateway::partial$task-tls-config.adoc[tags=sample-config-instance]

==== Apply mTLS Inbound Configuration to a Specific API Instance

//sample mtls config applied a specific api intro
include::gateway::partial$task-tls-config.adoc[tags=sample-config-mtls-intro]
//sample mtls config applied to a specific api
include::gateway::partial$task-tls-config.adoc[tags=sample-config-mtls]

include::anypoint-security::partial$flex-tls-cipher.adoc[tags=cipherSupportLocal;ciphers]


== See Also
* xref:gateway::flex-conn-tls-config.adoc[]
* xref:gateway::flex-local-tls-config.adoc[]
* xref:policies-included-tls-outbound.adoc[]