= Monitoring Flex Gateway Metrics
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

== View a Managed Flex Gateway Metrics in Runtime Manager

The Managed Flex Gateway Dashboard in Runtime Manager presents a comprehensive view of the gateway, detailing its status, endpoints, private space, API capacity, request volume, data consumption, and average CPU and memory usage. In addition, it provides metrics on latency and error count for thorough monitoring.


To view information about a Managed Flex Gateway Instance:

. From Anypoint Platform, select *Runtime Manager*.
. Select *Flex Gateways* in the navigation menu.
. Select the name of the Managed Flex Gateway to view its status.

[[audit-logs]]
== View Managed Flex Gateway Audit Logs

Access Management audit logs provide a queryable history of actions performed within Anypoint Platform. Use audit logs to track Managed Flex Gateway actions, such as creating, editing, starting, and stopping gateways. 

To learn more about Audit Logs, see xref:access-management::audit-logging.adoc[].

To view Managed Flex Gateway audit logs:

. From Anypoint Platform, select *Access Management*.
. Click *Audit Logs*.
. Click the *Products* drop down.
. Select *Managed Gateway*.