= OpenTelemetry Support in Flex Gateway
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: otel, otel support, OpenTelemetry

OpenTelemetry is an observability standard consisting of specifications, APIs, and SDKs. It helps you instrument, generate, collect, and export telemetry data, such as metrics, logs, and traces, to analyze software behavior. 

OpenTelemetry enables Flex Gateway to provide observability into the behavior of Flex Gatway APIs. With distributed tracing, Flex Gateway also brings observability to interactions between Flex Gatway APIs and non-MuleSoft components that leverage the OpenTelemetry standard.

Flex Gateway supports generating and exporting OpenTelemetry distributed traces.

== Before You Begin

To use the OpenTelemetry with Flex Gateway, you must be familiar with:

* Distributed tracing concepts, including traces and spans. 
+
If you're new to distributed tracing and OpenTelemetry, we recommend starting with https://opentelemetry.io/docs/concepts/what-is-opentelemetry/[What is OpenTelemetry] and https://opentelemetry.io/docs/concepts/observability-primer/#understanding-distributed-tracing[Understanding distributed tracing].
* xref:monitoring::telemetry-exporter.adoc[How to export telemetry data to third-party monitoring systems].

== Tracing a Flex Gateway API

Flex Gateway leverages OpenTelemetry to provide:

* Distributed tracing
+
Tracing enables you to track Flex Gateway API interactions. When multiple systems and services are involved, distributed tracing tracks API requests as they flow through distributed environments, providing a comprehensive view of the API's execution.

== See Also

* xref:monitoring::telemetry-exporter.adoc[]