= Tracing Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:keywords: api gateway, flex gateway, gateway, policy, otel, otel support, OpenTelemetry, distributed tracing

[width="100%", cols="5,15"]
|===
>s| Policy Name | Tracing
>s|Summary  | Override global tracing configuration
>s|Category | Troubleshooting
>s|First Flex Gateway version available | v1.10.0
^s| Returned Status Codes | No return codes exist for this policy
|===

== Summary

The Tracing policy sets distributed tracing parameters for an API. You can use this policy to override the global distributed tracing parameters:

* `timeout` - Time in seconds before Flex Gateway closes the connection.

Distributed tracing is disabled by default. If you have enabled distributed tracing with a Flex Gateway configuration, you can use this policy to override the global distributed tracing parameters for an API. See xref:flex-conn-otel-config.adoc[Configure Distributed Tracing] for more information.

== Before You Begin


== Configuring Policy Parameters

include::partial$policy-title-headers.adoc[tag=configFile]

----
- policyRef:
    name: stream-idle-timeout-flex
  config:
    timeout: number // REQUIRED
----

[%header%autowidth.spread,cols="a,a,a,a"]
|===
|Parameter | Required or Optional | Default Value | Description

| `timeout`
| Required
| 300
| Time in seconds before Flex Gateway closes the connection.

|===

==== Resource Configuration Example

----
- policyRef:
    name: stream-idle-timeout-flex
  config:
    timeout: 3
----

include::partial$policy-title-headers.adoc[tag=ui]

[%header%autowidth.spread,cols="a,a,a"]
|===
| Element | Description | Required
| Stream idle timeout | Time in seconds before Flex Gateway closes the connection. | Yes
|===
