= SOAP Schema Validation Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images
:keywords: xml threat protection, api gateway, flex gateway, gateway, policy 

[width="100%", cols="1,3"]
|===
>s|Policy Name| SOAP Schema Validation
>s|Summary| Validates incoming traffic against a specified WSDL schema
>s|Category| Security
>s|First Flex Gateway version available |v1.10.0
>.^s| Returned Status Codes
| The policy returns a `400` for a client error or `500` for a server error. Error messages are define by SOAP standard responses.
|===

== Summary

NOTE: The Schema Validation policy only supports SOAP APIs.

Use the SOAP Schema Validation policy to block incoming requests that don't conform to the the defined WSDL schema. This policy prevents malformed or malicious SOAP messages from reaching the backend and enforces contract compliance between clients and services.

== Configuring Policy Parameters

include::partial$policy-title-headers.adoc[tag=configFile]

----
- policyRef:
    name: soap-validation
  config:
    serviceName: <string> // REQUIRED
    servicePort: <string> // REQUIRED
    
----

[%header%autowidth.spread,cols="a,a,a,a"]
|===
|Parameter | Required | Default Value | Description

| `serviceName`
| Yes
| NA
| The name of the SOAP service to validate, as defined in the WSDL.

| `servicePort`
| Yes
| NA
| The port name of the SOAP service to validate, as defined in the WSDL.

|===

==== Resource Configuration Example

----
- policyRef:
    name: soap-validation
  config:
    serviceName: 1
    servicePort: 1
----

include::partial$policy-title-headers.adoc[tag=ui]

[%header%autowidth.spread,cols="a,a"]
|===
|Field |Description
| Service Name | The name of the SOAP service to validate, as defined in the WSDL.
| Service Port | The port name of the SOAP service to validate, as defined in the WSDL.
|===


