= Registering and Running Flex Gateway in Connected Mode
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: runtime-manager::flex-gateway-register.adoc
:imagesdir: ../assets/images

Before you can use your Flex Gateway to configure API instances, you must register and start the gateway.

There are three ways to register Flex Gateway in Connected Mode:

* xref:flex-conn-reg-run-up.adoc[Register and Run using a Username and Password]: If you have
a username and password for Anypoint Platform, you can use these credentials to register
your Flex Gateway.
* xref:flex-conn-reg-run-app.adoc[Register and Run using a Connected App]: If you do not have
a username or password for Anypoint Platform, you can use connected app credentials to register
your Flex Gateway.
* xref:flex-conn-reg-run-token.adoc[Register and Run using a Token]: If you do not have a username
or password for Anypoint Platform, you can use a registration token generated by the Runtime Manager UI. The token is valid for four hours.
