= Troubleshooting Platform Connection
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

When configuring Flex Gateway in either mode, it is possible for the Flex Replica's `registration.yaml` to not be present or for the replica to lose connection to Anypoint Platform.

To troubleshoot if a registration file is present and if Flex Gateway can make platform connections, Flex Gateway provides the following command:

[source,ssh]
----
flexctl check connections
----

The `flexctl check connections` first ensures a `registration.yaml` file is present, and then checks if the replica can connect to the URLs defined in the registration file. If the command is successful, it returns the following `info` message:

----
$ flectl check connections
[flexctl][info] Connection to platform endpoints successful.
----

== No Registration File Found

If the `registration.yaml` file is not found, Flex Gateway returns the following error message:

----
$ flexctl check connections
Error: no registration config
----

To troubleshoot an absent registration file, check your Flex Replica configuration folder. To learn more about registering a Flex Gateway, see following section for your relevant mode:

* xref:flex-conn-reg-run.adoc[]
* xref:flex-local-reg-run.adoc[]

== Failed Connection

There are multiple reasons Flex Gateway max experience connection issues, such as an error in the gateway's environment or a network issue. How you troubleshoot your error is dependent on the error returned.

If Flex Gateway cannot connect to a specific URL, it returns an error message that includes the URL that was unreachable and the error message returned from the connection attempt. The following error message is an example of an error due to no internet connection:

----
$ flexctl check connections
Error: failed connecting to https://anypoint.mulesoft.com/: dial tcp 52.22.227.22:443: connect: network is unreachable
----

== See Also

* xref:flex-troubleshoot-reg.adoc[]
* xref:flex-troubleshoot-requests.adoc[]