= Viewing Key Metrics for Flex Gateway APIs
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images


API Manager and Anypoint Monitoring collect metrics on active Flex Gateway API instances. You can view charts related to these metrics and filter the data by date. 

include::reuse::partial$billing/pricing.adoc[tag=apimKeyMetrics]


[NOTE]
====
The *Mule API Analytics* tab in API Manager is currently not available for Flex Gateway APIs. Use the *Key Metrics* or the additional metrics in Anypoint Monitoring.
====


== Key Metrics

include::partial$include-nav-steps-api-instance.adoc[]

To see an API instance in Anypoint Monitoring, from the *Key Metrics* section click *View more metrics in Anypoint Monitoring dashboard* or navigate to Anypoint Monitoring directly.

The *Key Metrics* section shows four charts. If charts do not appear for your API instance, refresh your browser.

== Understanding Key Metrics

The *Key Metrics* section of the API summary contains the following charts:

Total Requests::
Sum of requests in the selected time period for the given API.
+
Data is aggregated in one minute increments.

Total Policy Violations::
Sum of requests that return policy violations.
+
Data is aggregated in one minute increments.

Total Errors::
Sum of HTTP response codes that occur in the selected time period. The response codes counted in this metric are 400, 401, 402, 403, 404, 405, 408, 409, 410, 411, 412, 413, 415, 416, 417, 420, 422, 429, 500, 502, 503, 504, 504, 510, and 511.
+
Data is aggregated in one minute increments. In the chart, HTTP response codes are abbreviated as 4xx and 5xx.

Average Response Time::
Average response time of requests in the selected time period for the given API.
+
Data is aggregated in one minute increments.


== Setting the Time Period for Key Metrics

You can view the data points collected for the last given period of time (such as the last 5 or 30 minutes) or over a given date and time range. Use the drop-down in the calendar icon to select the time period to display.

== What's Next?

* Create alerts using the metrics related to an API instance with the xref:flex-use-api-alerts.adoc[Alerts feature in API Manager] or with the xref:monitoring::basic-alerts.adoc[Basic Alerts feature in Anypoint Monitoring].
* View built-in API dashboards in xref:monitoring::api-analytics-dashboard.adoc[Anypoint Monitoring] where you can see additional metrics, filter data by date, and export data into a CSV.
include::reuse::partial$billing/pricing.adoc[tag=availabilityParenthetical]
