= Developing Custom Policies
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

After installing the xref:policies-pdk-prerequisites.adoc[Prerequisites], you can develop custom policies by using Omni Gateway Policy Development Kit (PDK).

The custom policy lifecycle consists of all the steps of developing a custom policy that occur in PDK. The following steps do not include steps that occur outside of PDK, such as xref:policies-pdk-apply-policies.adoc[applying a policy], which is the same for all Omni Gateway policies.

After you xref:policies-pdk-create-project.adoc[create a new project], you might iteratively complete some steps. For example, while writing the policy's source code, you might need to return to xref:policies-pdk-create-schema-definition.adoc[add additional parameters], or you might need to recompile the policy after debugging the source code.

To create a custom policy with PDK, follow these steps:

. xref:policies-pdk-create-project-overview.adoc[Create a new project].

. xref:policies-pdk-create-schema-definition.adoc[Define a schema definition].
+
Modify the `definition/gcl.yaml` file to define metadata and configuration parameters for your custom policy.

. xref:policies-pdk-configure-features.adoc[Configure custom policy features in Rust].
+
Use the rust code examples to implement your custom logic in the `src/lib.rs` file.

. xref:policies-pdk-compile-policies.adoc[Compile your custom policy].
+
Compiling your policy creates the `WebAssembly` binary file and configuration files necessary to upload your policy to Exchange and deploy it to an Omni Gateway.

. xref:policies-pdk-test-debug-overview.adoc[Test and debug your policy].
+
Use xref:policies-pdk-unit.adoc[pdk-unit] for fast unit tests, xref:policies-pdk-debug-local.adoc[the PDK debugging playground] for interactive checks with Omni Gateway in Local Mode in Docker, and xref:policies-pdk-integration-tests.adoc[integration tests] to guard against regressions with your services and gateway configuration.

. xref:policies-pdk-publish-policies-overview.adoc[Publish your policy on Exchange].
+
Publish your policy on Exchange to distribute a development version of your policy for testing with your Omni Gateway configuration and to release production-ready policies. To deploy a policy to Omni Gateway, see step seven.

. Deploy your custom policy to a production environment by xref:policies-pdk-apply-policies.adoc[applying it to an API instance] deployed on Omni Gateway. 

. Configure a new version of this API instance by returning to step two.