= Compiling Custom Policies
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

You can compile the custom policy project after you complete all the steps in xref:policies-pdk-create-project.adoc[].

You must compile the custom policy before you can deploy it to a Flex Gateway.

After you compile your project, test your policy with the following tutorials:

* xref:policies-pdk-debug-local.adoc[]
* xref:policies-pdk-apply-policies.adoc[]

== Before You Begin

Ensure you have completed all the steps in xref:policies-pdk-create-project.adoc[].

== Build Command

To compile the policy, run the `build` command from the policy's root folder:

[source,ssh]
----
make build
----

The `build` command preforms the following actions:

. Runs the `build-asset-files`.
. Runs the `build` command to compile the policy to a `WebAssembly` binary file.
. Generates additional configuration files that aren't generated by the `build-asset-files` command and are required to execute the policy. 

The `build` command outputs the generated files to the `target` directories.

You can execute the `build` command as many times as necessary to generate compiled artifacts. You must compile the custom policy for your source code and configuration edits to be present in the compiled artifacts.

== See Also

* xref:policies-pdk-troubleshooting.adoc[]
