= Applying Custom Policies
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

Applying custom policies is the same as applying xref:gateway::policies-included-directory.adoc[included policies].

When applying custom policies, the configuration parameters are defined in `definition/gcl.yaml`.

To learn more about defining configuration parameters, see xref:policies-pdk-create-schema-definition.adoc[].

== Before You Begin

For both Connected Mode and Local Mode:

* xref:policies-pdk-publish-policies.adoc[Upload your Custom Policy to Exchange]

== Connected Mode

When you apply a custom policy in Connected Mode, the configuration parameters and metadata defined in `gcl.yaml` appear in the API Manager UI.

To apply a custom policy in Connected Mode, see xref:gateway::policies-included-apply.adoc[Apply a Policy in Connected Mode]. 

=== Update Policies in Connected Mode

To update a custom policy in API Manager, you can either:

* Delete the policy, and then re-apply the latest version of the policy. This automatically updates the policies binary file.
* Update the version of the applied policy. If you update the version on the applied policy, you must check for implementation updates to ensure your policy's binary file is up to date.
+
To check for implementation updates, see xref:exchange::manage-versions.adoc#update-policy-implementations[Update Policy Implementations].

== Local Mode

For Flex Gateway running in Local Mode, you apply custom policies using xref:gateway::flex-local-configuration-reference-guide.adoc[local declarative configuration files]. You specify the location of these configuration files when you first run Flex Gateway.

To create the local declarative files:

. In the `target/wasm32-wasi/release` directory, copy both of the following files:
+
* `<your_custom_policy>_definition.yaml`
* `<your_custom_policy>_implementation.yaml`
+
. Paste the two files in the `/etc/mulesoft/flex-gateway/conf.d/` Flex Gateway configuration directory.
+
. Create a policy binding configuration file with a `.yaml` file extension to bind the policy to an API instance:
+
* Give the file a custom name.
* Save the file in the Flex Gateway configuration directory `/etc/mulesoft/flex-gateway/conf.d/custom`. This directory can contain multiple configuration files.
. Copy and paste the following YAML snippet into the file, substituting your values where indicated::
+
[source,yaml]
----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: PolicyBinding
metadata:
  name: <custom-policy-id>
spec:
  targetRef:
    kind: ApiInstance
    name: <your-api-instance>
  policyRef:
    kind: Extension
    name: <your_custom_policy>-implementation
  config:
    <custom-cofiguration-parameters>: "your parameter"
----
+
* `metadata.name`: Contains the custom policy instance name.
* `spec.targetRef.name`: Contains the name of the API instance on which to apply the custom policy. The API instance must already have been defined and applied.
* `spec.policyRef.name`: Contains the custom policy implementation to apply.
* `spec.config`: Contains policy configuration data.
+
. Save the file. The gateway automatically refreshes the configuration.

== Reorder Custom Policies

Reordering custom policies is the same as reordering included policies.

To reorder policies, see xref:gateway::policies-reorder.adoc[].

Polices execute in order on the request and then in inverse order on the response. However, some policies do not execute on both the request and the response.

For example, policies ordered:

. Policy X
. Policy Y

Execute Policy X then Policy Y on the request, and Policy Y then Policy X on the response.

== See Also

* xref:policies-custom-flex-implement-rust.adoc[]
* xref:flex-local-configuration-reference-guide.adoc[]