= Performing an HTTP Call
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

To interact with external services, the policy must use HTTP calls. You can perform HTTP calls in the `[entrypoint]` function, the request filter, or the response filter. To perform an HTTP call, inject the `HttpClient` as follows:

* Injection for `[entrypoint]` function:
+
[source,Rust]
----
#[entrypoint]
async fn configure(
    launcher: Launcher,
    Configuration(configuration): Configuration,
    client: HttpClient,
) -> Result<(), LaunchError> {
----

* Injection for `on_request` or `on_response` wrapped functions:
+
[source,Rust]
----
// Handler with the logic for incoming requests
​​async fn request_filter(state: RequestState, conf: &Config, client: HttpClient) {
 ...
}

#[entrypoint]
async fn configure(launcher: Launcher, Configuration(bytes): Configuration) -> Result<()> {
    let config: Config = serde_json::from_slice(&bytes).unwrap();

    // For incoming request events, using the on_request wrapper, inject the client and pass it to the request_filter handler
    launcher
        .launch(on_request(|request, client| {
            request_filter(request, &config, client)
        }))
        .await?;
    Ok(())
}
----

Define your service as a parameter in you schema definition to reuse your policy with different services. The following code snippet provides an example schema definition for an external service:

[source,yaml]
----
properties:
      externalService:
          type: string
          format: service
      endpointPath:
          type: string
----

To learn more about defining parameters, see xref:policies-pdk-create-schema-definition.adoc[]

In Rust, you can access the defined external service in the `Config` struct. To perform requests, call the HTTP client in your policy similar to the following example:

[source,rust]
----
let response = client
    .request(&config.external_service)
    .path(&config.endpoint_path)
    .headers(vec![("Content-Type", "application/json")])
    .body(r#"{"key": "value"}"#.as_bytes())
    .put().await?;
----

To view an example policy that makes HTTP request, see the xref:policies-pdk-policy-templates.adoc[JWT Example Policy]. 
