= Debugging Deployed Custom Policies
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

You can debug a malfunctioning policy via the following methods:

* <<debug-environment>>
* <<integration-testing>>
* <<debug-logs>>

[[debug-playground]]
== Use the PDK Debugging Playground

The PDK debugging playground provides an easy way to view Flex Gateway logging and send a variety of requests. However, there may be some differences between it and your production environment. Use the PDK debugging playground before debugging on a Flex Gateway instance.

For more information about PDK's debugging playground, see xref:policies-pdk-debug-local.adoc[].

[[integration-testing]]
== Use PDK Integration Testing

PDK provides an automated testing framework to detect integration regressions in your custom policy.

For more information about PDK's integration testing, see xref:policies-pdk-integration-testing.adoc[].

[[debug-logs]]
== Debug in a Production Environment

Errors that are not present in the PDK debugging environment might be present when the policy is deployed to a production environment.

To use debug logs in a production environment, see xref:gateway::flex-troubleshoot-debug-logs.adoc[].

For more information about monitoring Flex Gateway, see xref:gateway::flex-gateway-monitor.adoc[].