= Perform an HTTP Call
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:imagesdir: ../assets/images

To interact with external services, the policy must use HTTP calls. You can perform HTTP calls in the request and response filters and in the function. To perform an HTTP call, inject the `HttpClient` as follows:

* Injection for `on_request` or `on_response` wrapped functions functions:
+
[source,Rust]
----
​​async fn request_filter(state: RequestState, conf: &Config, client: HttpClient) {
 ...
}
----

* Injection for `[entrypoint]` function:
+
[source,Rust]
----
​​async fn request_filter(state: RequestState, conf: &Config, client: HttpClient) {
 ...
}
----

You can only make HTTP calls to services defined in the Flex Gateway configuration files. For more information about defining services, see xref:flex-local-configuration-reference-guide.adoc#service[Services].

For both Connected and Local modes, define services using the `Service` resource. If the service is not defined when the request is made, the API request fails.

For an example of how to make HTTP calls from the policy, given the `Service` resource:

[source,yaml]
----
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Service
metadata:
  name: login
  namespace: custom-policy
spec:
  address: https://login.com
----

Make calls in `lib.rs` with the following:

[source,Rust]
----
let response = client.request("login.custom-policy.svc", "https://login.com")
    .path("/login")
    .headers(vec![("Content-Type", "application/json")])
    .body(r#"{"client_id": "client", "client_secret": "secret"}"#.as_bytes())
    .post().await?;
----

NOTE: In this example, the upstream service and URL are hardcoded. For reusability when making calls to an upstream service in your policy, add the necessary information to the xref:policies-pdk-create-schema-definition.adoc[configuration parameters].