Flex Gateway supports distributed tracing using the OpenTelemetry standard.

* *Stream Idle Timeout* +
The Stream Idle Timeout enables you to set a maximum amount of a time a stream can remain idle without receiving any data in either the inbound (client to Flex Gateway) or outbound (Flex Gateway to upstream service) direction.
+
By default, all Flex Gateway API instances have a stream timeout of 300 seconds.

You can configure these timeouts via:

* Configuration YAML file: Applies to all API instances and is easy to adjust.
* Policy: Applies to just one API instance or upstream providing granularity and is easy to adjust.

== Enable Distributed Tracing with a YAML Configuration Resource

Edit and then apply this configuration resource to enable distributed tracing. This configuration resource applies to all API instances.
This example sets sampling to 0 for all traces, and sampling will be configured on a per-API basis using policies.

[source,yaml]
----
apiVersion: gateway.mulesoft.com/v1beta1
kind: Configuration
metadata:
  name: tracing
  namespace: test-ns
spec:
  tracing:
    provider:
      type: anypoint
      properties:
        timeout:     10s
    sampling:
      client: 0
      random: 0
      overall: 0
    labels:
      - name: c-env-tag
        type: environment
        keyName: FLEX_NAME
        defaultValue: DEFAULT_VAL
      - name: c-header-tag
        type: requestHeader
        keyName: :method
        defaultValue: DEFAULT_METHOD
      - name: c-literal-tag
        type: literal
        defaultValue: the-tag
----

== Configure Distributed Tracing with Policies

After enabling distributed tracing with a global YAML configuration resource, you can configure distributed tracing for your APIs using policies.

For example, you can apply this policy to the APIs you want to instrument:

* xref:policies-tracing-config.adoc[]
